//! Emit a Rust struct + canonical little-endian encoder from a
//! parsed CL `struct`.

use std::fmt::Write;

use thiserror::Error;

use crate::parser::{FieldType, ParsedField, ParsedStruct};

#[derive(Debug, Error, PartialEq, Eq)]
pub enum EmitError {
    #[error("formatter failed")]
    FmtFailed,
}

#[derive(Debug, Clone)]
pub struct EmitOptions {
    /// Emit `#[derive(Debug, Clone, PartialEq, Eq)]` on the struct.
    pub derive_debug: bool,
    /// Add a top-of-file header comment indicating the file is
    /// codegen'd and must not be hand-edited.
    pub header: bool,
}

impl Default for EmitOptions {
    fn default() -> Self {
        Self {
            derive_debug: true,
            header: true,
        }
    }
}

/// Emit a complete Rust source file containing the struct + encoder.
/// The encoder produces little-endian bytes for the integer fields
/// and length-prefixed bytes (u32 LE length) for strings. Fixed-
/// length byte arrays emit their bytes verbatim.
pub fn emit_rust_struct(parsed: &ParsedStruct, opts: &EmitOptions) -> Result<String, EmitError> {
    let mut out = String::new();
    if opts.header {
        writeln!(
            out,
            "// AUTOGENERATED by ol_codegen — DO NOT EDIT BY HAND.\n\
             // Regenerate by running the codegen tool over the matching\n\
             // CL spec; the byte-equivalence CI gate ensures the CL\n\
             // canonical encoder and this Rust encoder produce\n\
             // identical bytes for any input.\n"
        )
        .map_err(|_| EmitError::FmtFailed)?;
    }
    if opts.derive_debug {
        writeln!(out, "#[derive(Debug, Clone, PartialEq, Eq)]")
            .map_err(|_| EmitError::FmtFailed)?;
    }
    writeln!(out, "pub struct {} {{", parsed.name).map_err(|_| EmitError::FmtFailed)?;
    for field in &parsed.fields {
        let rust_ty = field_to_rust_ty(&field.ty);
        writeln!(out, "    pub {}: {},", field.name, rust_ty).map_err(|_| EmitError::FmtFailed)?;
    }
    writeln!(out, "}}\n").map_err(|_| EmitError::FmtFailed)?;

    // Encoder impl.
    writeln!(out, "impl {} {{", parsed.name).map_err(|_| EmitError::FmtFailed)?;
    writeln!(
        out,
        "    /// Canonical little-endian byte encoding. Matches the\n    \
         /// Coherence spec's `canonical_encode` definition byte for\n    \
         /// byte (verified by the byte-equivalence CI gate)."
    )
    .map_err(|_| EmitError::FmtFailed)?;
    writeln!(out, "    pub fn encode(&self) -> Vec<u8> {{").map_err(|_| EmitError::FmtFailed)?;
    writeln!(out, "        let mut out = Vec::new();").map_err(|_| EmitError::FmtFailed)?;
    for field in &parsed.fields {
        emit_encode_field(&mut out, field)?;
    }
    writeln!(out, "        out").map_err(|_| EmitError::FmtFailed)?;
    writeln!(out, "    }}").map_err(|_| EmitError::FmtFailed)?;
    writeln!(out, "}}").map_err(|_| EmitError::FmtFailed)?;
    Ok(out)
}

fn field_to_rust_ty(ty: &FieldType) -> String {
    match ty {
        FieldType::U8 => "u8".into(),
        FieldType::U16 => "u16".into(),
        FieldType::U32 => "u32".into(),
        FieldType::U64 => "u64".into(),
        FieldType::ByteArray(n) => format!("[u8; {}]", n),
        FieldType::String => "String".into(),
    }
}

fn emit_encode_field(out: &mut String, field: &ParsedField) -> Result<(), EmitError> {
    let name = &field.name;
    match field.ty {
        FieldType::U8 => writeln!(out, "        out.push(self.{});", name).map_err(|_| EmitError::FmtFailed),
        FieldType::U16 => writeln!(
            out,
            "        out.extend_from_slice(&self.{}.to_le_bytes());",
            name
        )
        .map_err(|_| EmitError::FmtFailed),
        FieldType::U32 => writeln!(
            out,
            "        out.extend_from_slice(&self.{}.to_le_bytes());",
            name
        )
        .map_err(|_| EmitError::FmtFailed),
        FieldType::U64 => writeln!(
            out,
            "        out.extend_from_slice(&self.{}.to_le_bytes());",
            name
        )
        .map_err(|_| EmitError::FmtFailed),
        FieldType::ByteArray(_) => writeln!(
            out,
            "        out.extend_from_slice(&self.{});",
            name
        )
        .map_err(|_| EmitError::FmtFailed),
        FieldType::String => {
            writeln!(
                out,
                "        let __{}_bytes = self.{}.as_bytes();",
                name, name
            )
            .map_err(|_| EmitError::FmtFailed)?;
            writeln!(
                out,
                "        out.extend_from_slice(&(__{}_bytes.len() as u32).to_le_bytes());",
                name
            )
            .map_err(|_| EmitError::FmtFailed)?;
            writeln!(out, "        out.extend_from_slice(__{}_bytes);", name)
                .map_err(|_| EmitError::FmtFailed)
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::parser::parse_struct;

    #[test]
    fn emit_simple_struct_compiles() {
        let cl = "struct Cap { id: [u8; 32], not_after: u64, name: String }";
        let parsed = parse_struct(cl).unwrap();
        let rust = emit_rust_struct(&parsed, &EmitOptions::default()).unwrap();
        // Spot-check the output contains the expected pieces.
        assert!(rust.contains("pub struct Cap {"));
        assert!(rust.contains("pub id: [u8; 32],"));
        assert!(rust.contains("pub not_after: u64,"));
        assert!(rust.contains("pub name: String,"));
        assert!(rust.contains("pub fn encode(&self) -> Vec<u8>"));
        // Verify the encoder uses to_le_bytes for integers.
        assert!(rust.contains("self.not_after.to_le_bytes()"));
        // Strings are length-prefixed (u32 LE).
        assert!(rust.contains("as u32).to_le_bytes()"));
    }

    #[test]
    fn emit_header_present_when_option_set() {
        let cl = "struct X { a: u8 }";
        let parsed = parse_struct(cl).unwrap();
        let opts = EmitOptions { header: true, derive_debug: false };
        let rust = emit_rust_struct(&parsed, &opts).unwrap();
        assert!(rust.contains("AUTOGENERATED"));
        assert!(!rust.contains("#[derive"));
    }

    #[test]
    fn emit_options_disable_header() {
        let cl = "struct X { a: u8 }";
        let parsed = parse_struct(cl).unwrap();
        let opts = EmitOptions { header: false, derive_debug: true };
        let rust = emit_rust_struct(&parsed, &opts).unwrap();
        assert!(!rust.contains("AUTOGENERATED"));
    }
}
