//! Emit a Rust struct / enum + canonical little-endian encoder from a
//! parsed CL declaration.

use std::fmt::Write;

use thiserror::Error;

use crate::parser::{
    FieldType, ParsedDecl, ParsedEnum, ParsedField, ParsedStruct, ParsedVariant,
};

/// Errors the emitter can surface.
#[allow(missing_docs)]
#[derive(Debug, Error, PartialEq, Eq)]
pub enum EmitError {
    #[error("formatter failed")]
    FmtFailed,
    /// More than 255 enum variants — the u8-tag wire format can't
    /// represent these. Surface this as a typed error so codegen
    /// rejects the spec instead of silently truncating the
    /// discriminant.
    #[error("enum has {0} variants, exceeds u8 tag limit of 255")]
    TooManyVariants(usize),
}

/// Knobs for the Rust emitter. `default()` enables the standard
/// derives + the AUTOGENERATED header comment.
#[derive(Debug, Clone)]
pub struct EmitOptions {
    /// Emit `#[derive(Debug, Clone, PartialEq, Eq)]` on the struct /
    /// enum.
    pub derive_debug: bool,
    /// Add a top-of-file header comment indicating the file is
    /// codegen'd and must not be hand-edited.
    pub header: bool,
}

impl Default for EmitOptions {
    fn default() -> Self {
        Self {
            derive_debug: true,
            header: true,
        }
    }
}

/// Emit a complete Rust source file containing the struct + encoder.
/// The encoder produces little-endian bytes for the integer fields
/// and length-prefixed bytes (u32 LE length) for strings. Fixed-
/// length byte arrays emit their bytes verbatim.
pub fn emit_rust_struct(parsed: &ParsedStruct, opts: &EmitOptions) -> Result<String, EmitError> {
    let mut out = String::new();
    if opts.header {
        write_header(&mut out)?;
    }
    if opts.derive_debug {
        writeln!(out, "#[derive(Debug, Clone, PartialEq, Eq)]")
            .map_err(|_| EmitError::FmtFailed)?;
    }
    writeln!(out, "pub struct {} {{", parsed.name).map_err(|_| EmitError::FmtFailed)?;
    for field in &parsed.fields {
        let rust_ty = field_to_rust_ty(&field.ty);
        writeln!(out, "    pub {}: {},", field.name, rust_ty).map_err(|_| EmitError::FmtFailed)?;
    }
    writeln!(out, "}}\n").map_err(|_| EmitError::FmtFailed)?;

    writeln!(out, "impl {} {{", parsed.name).map_err(|_| EmitError::FmtFailed)?;
    write_encode_doc(&mut out)?;
    writeln!(out, "    pub fn encode(&self) -> Vec<u8> {{").map_err(|_| EmitError::FmtFailed)?;
    writeln!(out, "        let mut out = Vec::new();").map_err(|_| EmitError::FmtFailed)?;
    for field in &parsed.fields {
        emit_encode_field(&mut out, field, "self.")?;
    }
    writeln!(out, "        out").map_err(|_| EmitError::FmtFailed)?;
    writeln!(out, "    }}").map_err(|_| EmitError::FmtFailed)?;
    writeln!(out, "}}").map_err(|_| EmitError::FmtFailed)?;
    Ok(out)
}

/// Emit a complete Rust source file containing the enum + encoder.
/// The encoder writes a 1-byte little-endian discriminant followed by
/// the variant payload's canonical encoding (or no payload bytes for
/// unit variants). Variants are tagged by their 0-based source order
/// — same layout the CL canonical encoder produces.
pub fn emit_rust_enum(parsed: &ParsedEnum, opts: &EmitOptions) -> Result<String, EmitError> {
    if parsed.variants.len() > 255 {
        return Err(EmitError::TooManyVariants(parsed.variants.len()));
    }
    let mut out = String::new();
    if opts.header {
        write_header(&mut out)?;
    }
    if opts.derive_debug {
        writeln!(out, "#[derive(Debug, Clone, PartialEq, Eq)]")
            .map_err(|_| EmitError::FmtFailed)?;
    }
    writeln!(out, "pub enum {} {{", parsed.name).map_err(|_| EmitError::FmtFailed)?;
    for variant in &parsed.variants {
        match &variant.payload {
            Some(ty) => writeln!(out, "    {}({}),", variant.name, field_to_rust_ty(ty))
                .map_err(|_| EmitError::FmtFailed)?,
            None => writeln!(out, "    {},", variant.name).map_err(|_| EmitError::FmtFailed)?,
        }
    }
    writeln!(out, "}}\n").map_err(|_| EmitError::FmtFailed)?;

    writeln!(out, "impl {} {{", parsed.name).map_err(|_| EmitError::FmtFailed)?;
    write_encode_doc(&mut out)?;
    writeln!(out, "    pub fn encode(&self) -> Vec<u8> {{").map_err(|_| EmitError::FmtFailed)?;
    writeln!(out, "        let mut out = Vec::new();").map_err(|_| EmitError::FmtFailed)?;
    writeln!(out, "        match self {{").map_err(|_| EmitError::FmtFailed)?;
    for (idx, variant) in parsed.variants.iter().enumerate() {
        let tag = idx as u8;
        emit_match_arm(&mut out, &parsed.name, variant, tag)?;
    }
    writeln!(out, "        }}").map_err(|_| EmitError::FmtFailed)?;
    writeln!(out, "        out").map_err(|_| EmitError::FmtFailed)?;
    writeln!(out, "    }}").map_err(|_| EmitError::FmtFailed)?;
    writeln!(out, "}}").map_err(|_| EmitError::FmtFailed)?;
    Ok(out)
}

/// Emit any top-level declaration the parser produces. Dispatches to
/// the struct- or enum-emitter based on the parsed shape.
pub fn emit_rust_decl(parsed: &ParsedDecl, opts: &EmitOptions) -> Result<String, EmitError> {
    match parsed {
        ParsedDecl::Struct(s) => emit_rust_struct(s, opts),
        ParsedDecl::Enum(e) => emit_rust_enum(e, opts),
    }
}

fn write_header(out: &mut String) -> Result<(), EmitError> {
    writeln!(
        out,
        "// AUTOGENERATED by ol_codegen — DO NOT EDIT BY HAND.\n\
         // Regenerate by running the codegen tool over the matching\n\
         // CL spec; the byte-equivalence CI gate ensures the CL\n\
         // canonical encoder and this Rust encoder produce\n\
         // identical bytes for any input.\n"
    )
    .map_err(|_| EmitError::FmtFailed)
}

fn write_encode_doc(out: &mut String) -> Result<(), EmitError> {
    writeln!(
        out,
        "    /// Canonical little-endian byte encoding. Matches the\n    \
         /// Coherence spec's `canonical_encode` definition byte for\n    \
         /// byte (verified by the byte-equivalence CI gate)."
    )
    .map_err(|_| EmitError::FmtFailed)
}

fn field_to_rust_ty(ty: &FieldType) -> String {
    match ty {
        FieldType::U8 => "u8".into(),
        FieldType::U16 => "u16".into(),
        FieldType::U32 => "u32".into(),
        FieldType::U64 => "u64".into(),
        FieldType::ByteArray(n) => format!("[u8; {}]", n),
        FieldType::String => "String".into(),
    }
}

fn emit_encode_field(
    out: &mut String,
    field: &ParsedField,
    prefix: &str,
) -> Result<(), EmitError> {
    let name = &field.name;
    let access = format!("{}{}", prefix, name);
    write_encode_expr(out, &field.ty, &access, name, "        ")
}

fn emit_match_arm(
    out: &mut String,
    enum_name: &str,
    variant: &ParsedVariant,
    tag: u8,
) -> Result<(), EmitError> {
    match &variant.payload {
        None => {
            writeln!(
                out,
                "            {}::{} => {{ out.push({}); }},",
                enum_name, variant.name, tag
            )
            .map_err(|_| EmitError::FmtFailed)?;
        }
        Some(ty) => {
            writeln!(
                out,
                "            {}::{}(__payload) => {{",
                enum_name, variant.name
            )
            .map_err(|_| EmitError::FmtFailed)?;
            writeln!(out, "                out.push({});", tag)
                .map_err(|_| EmitError::FmtFailed)?;
            // For the variant payload we encode the value through a
            // shared expression-level emitter; access path is
            // ``__payload`` (the binding from the match arm).
            write_encode_expr(out, ty, "__payload", "v", "                ")?;
            writeln!(out, "            }},").map_err(|_| EmitError::FmtFailed)?;
        }
    }
    Ok(())
}

/// Shared encode-expression emitter used by both struct fields and
/// enum-variant payloads. `access` is the Rust expression that yields
/// the value (e.g. ``self.foo`` or ``__payload``). `local_name` is
/// used to make string-encode temporaries unique. `indent` is the
/// leading whitespace per emitted line.
fn write_encode_expr(
    out: &mut String,
    ty: &FieldType,
    access: &str,
    local_name: &str,
    indent: &str,
) -> Result<(), EmitError> {
    match ty {
        FieldType::U8 => writeln!(out, "{}out.push({});", indent, deref_value(access, "u8"))
            .map_err(|_| EmitError::FmtFailed),
        FieldType::U16 => writeln!(
            out,
            "{}out.extend_from_slice(&{}.to_le_bytes());",
            indent,
            deref_value(access, "u16")
        )
        .map_err(|_| EmitError::FmtFailed),
        FieldType::U32 => writeln!(
            out,
            "{}out.extend_from_slice(&{}.to_le_bytes());",
            indent,
            deref_value(access, "u32")
        )
        .map_err(|_| EmitError::FmtFailed),
        FieldType::U64 => writeln!(
            out,
            "{}out.extend_from_slice(&{}.to_le_bytes());",
            indent,
            deref_value(access, "u64")
        )
        .map_err(|_| EmitError::FmtFailed),
        FieldType::ByteArray(_) => {
            // For struct fields `self.foo` we emit `&self.foo` (which
            // coerces &[u8;N] → &[u8]). For enum-variant bindings
            // `__payload: &[u8;N]` we drop the ampersand since the
            // binding is already a reference. Matches the prior wire
            // layout byte-for-byte.
            if access.starts_with("__") {
                writeln!(out, "{}out.extend_from_slice({});", indent, access)
                    .map_err(|_| EmitError::FmtFailed)
            } else {
                writeln!(out, "{}out.extend_from_slice(&{});", indent, access)
                    .map_err(|_| EmitError::FmtFailed)
            }
        }
        FieldType::String => {
            writeln!(
                out,
                "{}let __{}_bytes = {}.as_bytes();",
                indent, local_name, access
            )
            .map_err(|_| EmitError::FmtFailed)?;
            writeln!(
                out,
                "{}out.extend_from_slice(&(__{}_bytes.len() as u32).to_le_bytes());",
                indent, local_name
            )
            .map_err(|_| EmitError::FmtFailed)?;
            writeln!(
                out,
                "{}out.extend_from_slice(__{}_bytes);",
                indent, local_name
            )
            .map_err(|_| EmitError::FmtFailed)
        }
    }
}

/// Variants bind payloads by reference (`__payload: &T`) in the match
/// arm, so we need ``*__payload`` to read the integer scalar value.
/// Field access (`self.foo`) is already a place expression and reads
/// directly. The check is a string-prefix on the access expression —
/// minimal but covers both call sites the emitter actually generates.
fn deref_value(access: &str, _expected_ty: &str) -> String {
    if access.starts_with("__") {
        format!("(*{})", access)
    } else {
        access.to_string()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::parser::{parse_decl, parse_enum, parse_struct};

    #[test]
    fn emit_simple_struct_compiles() {
        let cl = "struct Cap { id: [u8; 32], not_after: u64, name: String }";
        let parsed = parse_struct(cl).unwrap();
        let rust = emit_rust_struct(&parsed, &EmitOptions::default()).unwrap();
        assert!(rust.contains("pub struct Cap {"));
        assert!(rust.contains("pub id: [u8; 32],"));
        assert!(rust.contains("pub not_after: u64,"));
        assert!(rust.contains("pub name: String,"));
        assert!(rust.contains("pub fn encode(&self) -> Vec<u8>"));
        assert!(rust.contains("self.not_after.to_le_bytes()"));
        assert!(rust.contains("as u32).to_le_bytes()"));
    }

    #[test]
    fn emit_header_present_when_option_set() {
        let cl = "struct X { a: u8 }";
        let parsed = parse_struct(cl).unwrap();
        let opts = EmitOptions { header: true, derive_debug: false };
        let rust = emit_rust_struct(&parsed, &opts).unwrap();
        assert!(rust.contains("AUTOGENERATED"));
        assert!(!rust.contains("#[derive"));
    }

    #[test]
    fn emit_options_disable_header() {
        let cl = "struct X { a: u8 }";
        let parsed = parse_struct(cl).unwrap();
        let opts = EmitOptions { header: false, derive_debug: true };
        let rust = emit_rust_struct(&parsed, &opts).unwrap();
        assert!(!rust.contains("AUTOGENERATED"));
    }

    #[test]
    fn emit_enum_unit_and_payload_variants() {
        let cl =
            "enum Caveat { NotAfter(u64), Scope(String), Audit([u8; 32]), Sentinel }";
        let parsed = parse_enum(cl).unwrap();
        let rust = emit_rust_enum(&parsed, &EmitOptions::default()).unwrap();
        assert!(rust.contains("pub enum Caveat {"));
        assert!(rust.contains("NotAfter(u64),"));
        assert!(rust.contains("Scope(String),"));
        assert!(rust.contains("Audit([u8; 32]),"));
        assert!(rust.contains("Sentinel,"));
        // Encoder match arm emits the discriminant byte.
        assert!(rust.contains("Caveat::NotAfter(__payload) => {"));
        assert!(rust.contains("out.push(0);"));
        assert!(rust.contains("out.push(1);"));
        assert!(rust.contains("out.push(2);"));
        // Unit variant Sentinel = idx 3.
        assert!(rust.contains("Caveat::Sentinel => { out.push(3); }"));
        // u64 payload variant derefs the &u64 binding.
        assert!(rust.contains("(*__payload).to_le_bytes()"));
        // String payload variant emits length-prefixed bytes.
        assert!(rust.contains("as u32).to_le_bytes()"));
    }

    #[test]
    fn emit_rust_decl_dispatches_to_correct_emitter() {
        let s = parse_decl("struct X { a: u8 }").unwrap();
        let e = parse_decl("enum E { A }").unwrap();
        assert!(emit_rust_decl(&s, &EmitOptions::default())
            .unwrap()
            .contains("pub struct X"));
        assert!(emit_rust_decl(&e, &EmitOptions::default())
            .unwrap()
            .contains("pub enum E"));
    }

    #[test]
    fn emit_enum_too_many_variants_rejected() {
        // Construct a parsed enum with 256 variants and check the
        // emitter rejects it with TooManyVariants.
        use crate::parser::{ParsedEnum, ParsedVariant};
        let variants = (0..256u32)
            .map(|i| ParsedVariant {
                name: format!("V{}", i),
                payload: None,
            })
            .collect();
        let p = ParsedEnum { name: "Big".into(), variants };
        let err = emit_rust_enum(&p, &EmitOptions::default()).unwrap_err();
        assert_eq!(err, EmitError::TooManyVariants(256));
    }
}
