"""Types for :mod:`one_link_native.aead`."""

from typing import Literal, TypeAlias, final
from typing_extensions import Buffer

AEAD_FRAME_PLAINTEXT_LEN: int
AEAD_TAG_LEN: int
FRAME_KEY_LEN: int
MAX_CHUNK_PLAINTEXT_LEN: int
MAX_CHUNK_CIPHERTEXT_LEN: int
MAX_PARALLEL_CHUNKS: int
MAX_PARALLEL_INPUT_BYTES: int

AeadKind: TypeAlias = Literal["aes", "chacha"]
ChunkInput: TypeAlias = tuple[bytes, Buffer]
EncryptedChunkInput: TypeAlias = tuple[bytes, int, Buffer]

@final
class AeadCipher:
    @property
    def kind(self) -> AeadKind: ...
    def encrypt_chunk(self, chunk_id: bytes, plaintext: Buffer) -> bytes: ...
    def decrypt_chunk(self, chunk_id: bytes, plaintext_len: int, ciphertext: Buffer) -> bytes: ...
    def encrypt_frame(
        self, chunk_id: bytes, frame_index: int, plaintext: Buffer
    ) -> tuple[bytes, bytes]: ...
    def decrypt_frame(
        self, chunk_id: bytes, frame_index: int, ciphertext: Buffer, tag: bytes
    ) -> bytes: ...
    def encrypt_chunks(self, chunks: list[ChunkInput]) -> list[bytes]: ...
    def decrypt_chunks(self, chunks: list[EncryptedChunkInput]) -> list[bytes]: ...
    def __repr__(self) -> str: ...

def new_cipher(key: bytes, kind: str) -> AeadCipher: ...
def default_cipher_for_host(key: bytes) -> AeadCipher: ...
def default_aead_kind() -> AeadKind: ...
def host_has_hardware_aes() -> bool: ...
