"""Types for :mod:`one_link_native.align`."""

__version__: str

def trust_score(hop_distance: float, staleness_seconds: float, l_session: float) -> float: ...
def trust_for(relationship: str, hop_distance: float, staleness_seconds: float) -> float: ...
def l_paired() -> float: ...
def l_known() -> float: ...
def l_stranger() -> float: ...
