"""Types for :mod:`one_link_native.bloom`."""

from typing import Self, final
from typing_extensions import Buffer

__version__: str
BLOOM_HEADER_LEN: int
MAX_FILTER_BYTES: int
MAX_FILTER_BITS: int

@final
class Bloom:
    def __new__(cls, n: int, target_fp: float | None = ...) -> Self: ...
    @property
    def m_bits(self) -> int: ...
    @property
    def k(self) -> int: ...
    def insert(self, chunk_id: Buffer) -> None: ...
    def contains(self, chunk_id: Buffer) -> bool: ...
    def popcount(self) -> int: ...
    def encoded_len(self) -> int: ...
    def encode(self) -> bytes: ...
    @staticmethod
    def decode(encoded: Buffer) -> Bloom: ...
    def __repr__(self) -> str: ...

def optimal_m_bits(n: int, target_fp: float = ...) -> int: ...
def optimal_k(n: int, m_bits: int) -> int: ...
def default_target_fp_rate() -> float: ...
