"""Types for :mod:`one_link_native.coherence_field`."""

from typing import Self, TypedDict, final, type_check_only

__version__: str
G_A_GALAXY_PLANCK: float
MAX_FIELD_NODES: int
MAX_FIELD_EDGES: int
MAX_SOLVER_ITERS: int

@type_check_only
class SolveResult(TypedDict):
    field: list[float]
    residual: float
    iterations: int
    converged: bool

@type_check_only
class Calibration(TypedDict):
    domain: str
    d: float
    gamma: float
    alpha_density: float
    beta_flux: float
    support_phase_c0: float
    support_phase_w: float
    c_propagation: float
    h_0_equivalent: float
    screening_length: float | None
    apparent_horizon_anchor: float | None

@final
class GraphLaplacian:
    def __new__(cls, n: int) -> Self: ...
    def add_edge(self, i: int, j: int, weight: float) -> None: ...
    def node_count(self) -> int: ...
    def degree(self, i: int) -> float: ...
    def __repr__(self) -> str: ...

@final
class FieldObservations:
    def __new__(cls, alpha: float = ..., initial_value: float = ...) -> Self: ...
    def update(self, peer_id: str, observed_tau: float, trust_weight: float = ...) -> None: ...
    def tau_at(self, peer_id: str) -> float | None: ...
    def set_neighbors(self, peer_id: str, neighbors: list[str]) -> None: ...
    def gradient_at(self, peer_id: str) -> float | None: ...
    @property
    def len(self) -> int: ...
    @property
    def is_empty(self) -> bool: ...
    @property
    def alpha(self) -> float: ...
    def __repr__(self) -> str: ...

@final
class WaveStepper:
    def __init__(self) -> None: ...
    def set_wave_speed(self, c: float) -> None: ...
    def set_damping(self, gamma: float) -> None: ...
    def set_threshold(self, threshold: float) -> None: ...
    def set_clamp_range(self, min: float | None = ..., max: float | None = ...) -> None: ...
    def set_cfl_enforce(self, enforce: bool) -> None: ...
    def seed(self, values: dict[str, float]) -> None: ...
    def step(self, dt: float, neighbors: dict[str, list[str]]) -> int: ...
    def psi_at(self, node: str) -> float | None: ...
    def __len__(self) -> int: ...
    @property
    def wave_speed(self) -> float: ...
    @property
    def damping(self) -> float: ...
    @property
    def cascade_threshold(self) -> float: ...
    @property
    def cascade_warnings(self) -> int: ...
    def reset_warnings(self) -> None: ...
    @property
    def step_count(self) -> int: ...
    def courant_number(self, dt: float) -> float: ...
    def max_stable_dt(self) -> float: ...
    def total_energy(self, dt: float, neighbors: dict[str, list[str]]) -> float: ...
    def snapshot(self) -> dict[str, float]: ...

def solve_helmholtz(
    graph: GraphLaplacian,
    d: float,
    gamma: float,
    source: list[float],
    max_iters: int = ...,
    tolerance: float = ...,
) -> SolveResult: ...
def green_function(
    graph: GraphLaplacian,
    d: float,
    gamma: float,
    destination: int,
    sources: list[int],
    max_iters: int = ...,
    tolerance: float = ...,
) -> list[float]: ...
def be_rar(y: float) -> float: ...
def screening_length(d: float, gamma: float) -> float | None: ...
def apparent_horizon_anchor(c_wire: float, h_swarm: float) -> float | None: ...
def linear_source(density: list[float], weight: float) -> list[float]: ...
def identity_dual_source(
    density: list[float], flux: list[float], alpha: float, beta: float
) -> list[float]: ...
def identity_dual_source_with_phase(
    density: list[float],
    flux: list[float],
    c_support: list[float],
    alpha: float,
    beta: float,
    c0: float = ...,
    w_phase: float = ...,
) -> list[float]: ...
def support_phase_kernel(
    c_support: list[float], c0: float = ..., w_phase: float = ...
) -> list[float]: ...
def inject_fragility_events(
    source: list[float], events: list[tuple[list[int], float]], coupling_strength: float
) -> tuple[list[float], list[float]]: ...
def prefetch_priorities(
    field: list[float], requester: int, holders: list[int], route_weight: float
) -> list[tuple[int, float, float]]: ...
def rotation_cadence_multiplier(
    field: list[float], baseline_bytes: int, mu_max: float, power: float
) -> list[tuple[int, float, int]]: ...
def one_link_calibration() -> Calibration: ...
def one_field_calibration() -> Calibration: ...
def bio_mesh_calibration() -> Calibration: ...
