"""Types for :mod:`one_link_native.compress`."""

from typing import final

__version__: str
MAX_COMPRESSED_PAYLOAD_BYTES: int
MAX_DECOMPRESSED_BYTES: int

@final
class Compressor:
    def __init__(self) -> None: ...
    def pick(self, kind: str, size: int, precompressed: bool = ...) -> str: ...
    def compress(self, algo: str, payload: bytes) -> bytes: ...
    def decompress(self, payload: bytes, max_size: int) -> bytes: ...
    def __repr__(self) -> str: ...
