"""Type stubs for one_link_native.discovery (Phase F1.3)."""

from enum import Enum
from typing import List, Optional, Self, Tuple, final

NODE_ID_BYTES: int
NODE_ID_BITS: int
K_BUCKET_DEFAULT: int
MAX_BUCKETS: int
RECORD_DEFAULT_TTL_SECS: int
MAX_K_BUCKET_SIZE: int
MAX_RECORD_TTL_SECS: int
MAX_ENDPOINTS: int
MAX_ENDPOINT_LEN: int
MAX_SEED_PEERS: int
MAX_STORED_RECORDS: int
MAX_RECORD_FUTURE_SKEW_SECS: int

@final
class InsertOutcome(Enum):
    Inserted = ...
    BumpedToTail = ...
    SelfInsertIgnored = ...
    BucketFull = ...

@final
class NodeId:
    def __new__(cls, raw: bytes) -> Self: ...
    @staticmethod
    def from_pubkey(pubkey: bytes) -> "NodeId": ...
    def as_bytes(self) -> bytes: ...
    def distance(self, other: "NodeId") -> bytes: ...
    def xor_leading_zeros(self, other: "NodeId") -> int: ...
    def bucket_index(self, other: "NodeId") -> Optional[int]: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object, /) -> bool: ...
    def __lt__(self, other: "NodeId", /) -> bool: ...
    def __le__(self, other: "NodeId", /) -> bool: ...
    def __gt__(self, other: "NodeId", /) -> bool: ...
    def __ge__(self, other: "NodeId", /) -> bool: ...
    def __hash__(self) -> int: ...

@final
class PeerRecord:
    def __new__(
        cls,
        publisher_pubkey: bytes,
        endpoints: List[str],
        publish_time_unix: int,
        ttl_secs: int = ...,
    ) -> Self: ...
    def publisher_pubkey(self) -> bytes: ...
    def endpoints(self) -> List[str]: ...
    def publish_time_unix(self) -> int: ...
    def ttl_secs(self) -> int: ...
    def canonical_bytes(self) -> bytes: ...
    def is_fresh(self, now_unix: int) -> bool: ...
    def node_id(self) -> NodeId: ...

@final
class SignedRecord:
    @staticmethod
    def sign(
        record: PeerRecord, signing_key_seed: bytes
    ) -> "SignedRecord": ...
    def __new__(cls, record: PeerRecord, signature: bytes) -> Self: ...
    def record(self) -> PeerRecord: ...
    def signature(self) -> bytes: ...
    def verify(self) -> None: ...
    def verify_and_check_freshness(self, now_unix: int) -> bool: ...
    def node_id(self) -> NodeId: ...

@final
class DhtNode:
    def __new__(
        cls,
        bind_addr: str,
        own_id: NodeId,
        seed_peers: List[Tuple[NodeId, str]],
    ) -> Self: ...
    def local_addr(self) -> str: ...
    def own_id(self) -> NodeId: ...
    def publish_self_record(self, record: SignedRecord) -> None: ...
    def add_seed_peer(self, id: NodeId, addr: str) -> None: ...
    def lookup(self, target: NodeId) -> List[NodeId]: ...
    def lookup_record(self, target: NodeId) -> Optional[SignedRecord]: ...
    def routing_table_len(self) -> int: ...
    def records_len(self) -> int: ...
    # Row 3 maintenance loops.
    def refresh_stale_buckets(self, now_unix: int, max_age_secs: int) -> int: ...
    def republish_records(self, now_unix: int, max_age_secs: int) -> int: ...
    def tick_maintenance(
        self,
        now_unix: int,
        bucket_max_age_secs: int,
        record_max_age_secs: int,
    ) -> Tuple[int, int]: ...
    def shutdown(self) -> None: ...

@final
class RoutingTable:
    def __new__(cls, own_id: NodeId, k: int = ...) -> Self: ...
    def own_id(self) -> NodeId: ...
    def k(self) -> int: ...
    def len(self) -> int: ...
    def is_empty(self) -> bool: ...
    def insert(
        self, id: NodeId, last_seen_unix: int
    ) -> Tuple[InsertOutcome, Optional[NodeId]]: ...
    def replace_head_on_timeout(
        self,
        timed_out_head: NodeId,
        new_peer: NodeId,
        last_seen_unix: int,
    ) -> bool: ...
    def closest_to(self, target: NodeId) -> List[NodeId]: ...
    def closest_n_to(self, target: NodeId, n: int) -> List[NodeId]: ...
    def stale_buckets(
        self, now_unix: int, max_age_secs: int
    ) -> List[int]: ...
    def remove(self, id: NodeId) -> bool: ...
    def contains(self, id: NodeId) -> bool: ...
    def bucket_sizes(self) -> List[int]: ...

PyNodeId = NodeId
PyPeerRecord = PeerRecord
PySignedRecord = SignedRecord
PyRoutingTable = RoutingTable
PyInsertOutcome = InsertOutcome
PyDhtNode = DhtNode
