"""Types for :mod:`one_link_native.fec`."""

from typing import Self, final

__version__: str
MAX_FEC_SHARD_BYTES: int
MAX_FEC_WORKING_SET_BYTES: int

@final
class Codec:
    def __new__(cls, k: int, m: int) -> Self: ...
    @property
    def k(self) -> int: ...
    @property
    def m(self) -> int: ...
    @property
    def total_shards(self) -> int: ...
    def encode(self, data_shards: list[bytes]) -> list[bytes]: ...
    def decode(self, present: list[bytes | None]) -> list[bytes]: ...
    def __repr__(self) -> str: ...
