"""Types for :mod:`one_link_native.fountain`."""

from typing import Self, final
from typing_extensions import Buffer

__version__: str
PACKET_HEADER_LEN: int
MAX_ENCODED_PER_CHUNK: int
MAX_SOURCE_SYMBOLS_PER_CHUNK: int
MAX_SOURCE_BYTES: int
MAX_SYMBOL_LEN: int
MAX_DECODER_BUFFER_BYTES: int
C: float
DELTA: float

@final
class LtEncoder:
    def __new__(cls, source: Buffer, symbol_len: int) -> Self: ...
    @property
    def k(self) -> int: ...
    @property
    def symbol_len(self) -> int: ...
    @property
    def source_len(self) -> int: ...
    def encode_symbol(self, symbol_id: int) -> bytes: ...
    def __repr__(self) -> str: ...

@final
class LtDecoder:
    def __new__(cls, k: int, symbol_len: int, source_length: int) -> Self: ...
    @property
    def resolved_count(self) -> int: ...
    @property
    def k(self) -> int: ...
    def ingest(self, symbol_id: int, payload: Buffer) -> bool: ...
    def is_complete(self) -> bool: ...
    def finish(self) -> bytes: ...
    def __repr__(self) -> str: ...

def encode_packet(
    chunk_id: Buffer, k: int, symbol_id: int, source_length: int, payload: Buffer
) -> bytes: ...
def decode_packet(encoded: Buffer) -> tuple[bytes, int, int, int, bytes]: ...
