"""Type stubs for ``one_link_native.hwkey`` (ADR-0023)."""

from typing import Self, final

@final
class TofuStore:
    def __new__(cls, root: bytes) -> Self: ...

    def guarantee(self) -> str: ...
    def get_or_create(self, label: str) -> str: ...
    def public_key(self, label: str) -> bytes: ...
    def check_tofu(self, label: str, presented: bytes) -> bool: ...
