"""Type stubs for one_link_native.onion (Phase F3)."""

from typing import List, Tuple

MAX_HOPS: int
MAX_USER_PAYLOAD: int
HOP_ID_LEN: int
TRANSPORT_PAD_HINT: int
DEFAULT_COVER_BODY_LEN: int
COVER_MAGIC: bytes

def build_onion(
    circuit: List[Tuple[bytes, bytes]], payload: bytes
) -> bytes: ...
def peel_one_layer(
    relay_static_sk: bytes, packet_bytes: bytes
) -> Tuple[str, bytes, bytes]: ...
def derive_pubkey(static_sk_bytes: bytes) -> bytes: ...
def pad_to_transport(packet_bytes: bytes, pad_seed: bytes) -> bytes: ...
def unpad_from_transport(padded_bytes: bytes) -> bytes: ...
def build_cover_packet(
    circuit: List[Tuple[bytes, bytes]], body_len: int = ...
) -> bytes: ...
def is_cover_payload(payload: bytes) -> bool: ...
