"""Type stubs for one_link_native.pqsig (Phase F row 1)."""

from typing import Tuple

HYBRID_SK_LEN: int
HYBRID_VK_LEN: int
HYBRID_SIG_LEN: int

def generate_keypair() -> Tuple[bytes, bytes]: ...
def derive_vk(sk_bytes: bytes) -> bytes: ...
def sign(sk_bytes: bytes, message: bytes) -> bytes: ...
def verify(vk_bytes: bytes, message: bytes, sig: bytes) -> None: ...
