"""Type stubs for ``one_link_native.ratchet`` (ADR-0020)."""

from typing import Self, final

__version__: str
DEFAULT_SKIPPED_CAP: int


@final
class Chain:
    @staticmethod
    def from_shared_secret(shared_secret: bytes) -> "Chain": ...

    def next_message_key(self) -> bytes: ...
    def peek_message_key(self, target_step: int) -> bytes: ...
    def fast_forward(self, target_step: int) -> None: ...
    @property
    def step(self) -> int: ...
    def __repr__(self) -> str: ...


@final
class SkippedKeyStore:
    def __new__(cls, cap: int = ...) -> Self: ...
    def insert(self, step: int, key: bytes) -> None: ...
    def take(self, step: int) -> bytes: ...
    def drop_older_than(self, min_step: int) -> None: ...
    @property
    def capacity(self) -> int: ...
    def __len__(self) -> int: ...
