"""Type stubs for one_link_native.sphinx (Phase F3.5 Sphinx Coherence)."""

from typing import List, Optional, Self, Tuple, final

HOP_ID_LEN: int
MAX_HOPS: int
SPHINX_MAX_USER_PAYLOAD: int
SPHINX_PACKET_LEN: int
PQ_SPHINX_PACKET_LEN: int
ML_KEM_CT_LEN: int
ML_KEM_EK_LEN: int

# Standard Sphinx (Ristretto255 alpha blinding).
def generate_keypair() -> Tuple[bytes, bytes]: ...
def derive_pubkey_from_scalar(sk_bytes: bytes) -> bytes: ...
def build_sphinx(
    eph_sk_bytes: bytes,
    circuit: List[Tuple[bytes, bytes]],
    payload: bytes,
) -> bytes: ...
def peel_sphinx(
    relay_sk_bytes: bytes, packet_bytes: bytes
) -> Tuple[str, bytes, bytes]: ...

# PQ-hybrid Sphinx (ML-KEM-768 at entry).
def generate_pq_keypair() -> Tuple[bytes, bytes]: ...
def build_pq_sphinx(
    eph_sk_bytes: bytes,
    circuit: List[Tuple[bytes, bytes, Optional[bytes]]],
    payload: bytes,
) -> bytes: ...
def peel_pq_sphinx_entry(
    relay_x_sk_bytes: bytes, relay_pq_dk_bytes: bytes, packet_bytes: bytes
) -> Tuple[str, bytes, bytes]: ...
def peel_pq_sphinx_intermediate(
    relay_x_sk_bytes: bytes, packet_bytes: bytes
) -> Tuple[str, bytes, bytes]: ...

# Cover traffic (row 6).
COVER_SENTINEL: bytes
COVER_PAYLOAD_MIN: int
COVER_TRAILER_LEN: int
COVER_DEFAULT_RATE_HZ: float
COVER_MIN_RATE_HZ: float
COVER_MAX_RATE_HZ: float

def build_cover_packet(
    eph_sk_bytes: bytes, circuit: List[Tuple[bytes, bytes]], cover_size: int
) -> bytes: ...
def is_cover_payload(payload: bytes) -> bool: ...
def is_cover_payload_authenticated(shared_key: bytes, payload: bytes) -> bool: ...

@final
class CoverScheduler:
    def __new__(cls, rate_hz: float, seed: bytes) -> Self: ...
    def next_wait_ms(self) -> int: ...
    def rate_hz(self) -> float: ...
    def set_rate_hz(self, rate_hz: float) -> None: ...

@final
class RateEqualizer:
    def __new__(cls, target_total_hz: float) -> Self: ...
    def observe_real_emission(self, now_ms: int) -> None: ...
    def observe_idle_tick(self, now_ms: int) -> None: ...
    def current_cover_rate(self) -> float: ...
    def observed_real_rate(self) -> float: ...
    def target_total_hz(self) -> float: ...
    def set_half_life_sec(self, half_life_sec: float) -> None: ...

RATE_EQ_DEFAULT_HALF_LIFE_SEC: float
RATE_EQ_MAX_HALF_LIFE_SEC: float
