"""Types for :mod:`one_link_native.wal`."""

from typing import Self, final

FILE_HEADER_LEN: int
RECORD_HEADER_LEN: int
RECORD_TRAILER_LEN: int
MAX_PAYLOAD_LEN: int
ROTATION_SIZE: int

@final
class WalRecord:
    def __new__(cls, kind: int, flags: int, payload: bytes) -> Self: ...
    @property
    def kind(self) -> int: ...
    @property
    def flags(self) -> int: ...
    @property
    def payload(self) -> bytes: ...
    @property
    def length(self) -> int: ...
    def __repr__(self) -> str: ...

@final
class Wal:
    def active_file_id(self) -> int: ...
    def active_file_size(self) -> int: ...
    def append(self, record: WalRecord) -> None: ...
    def flush(self) -> None: ...
    def rotate(self) -> None: ...
    def close(self) -> None: ...

def create(dir: str, kind: str) -> Wal: ...
def open(dir: str, kind: str) -> Wal: ...
def replay_log_dir(dir: str, kind: str) -> list[WalRecord]: ...
def log_kind_magic(kind: str) -> bytes: ...
