#!/usr/bin/env python3
"""
dump_project_sources.py — 10/10 AI-first project dumper

NO-FLAGS DEFAULTS (what you asked for):
  - root = folder this script is in
  - output = <root>/script_dump/
  - line numbers ON (best for exact before/after patches)
  - respect .gitignore ON when git is available (falls back automatically)

It writes:
  - project_source_dump_partXX.txt  (chunked, default 15MB/part)
  - project_manifest.txt
  - project_manifest.json

Two modes:
  - internal (default): exact content, no redaction/sanitization
  - share: redacts common secret patterns + sanitizes absolute root paths + omits timestamps

Focus mode (--focus):
  - Dump a specific subfolder + all external files it imports/depends on
  - Example: --focus coherence_lang/ui_alpha
  - Automatically traces imports to include connected files outside the focus folder
"""

from __future__ import annotations

import argparse
import fnmatch
import hashlib
import json
import os
import platform
import re
import subprocess
import sys
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import (
    Any,
    Dict,
    List,
    Optional,
    Sequence,
    Set,
    Tuple,
)


# ----------------------------
# Tuned defaults (10/10)
# ----------------------------

DUMP_FORMAT_VERSION = 2

DEFAULT_DUMP_DIRNAME = "script_dump"
DEFAULT_OUT_BASENAME = "project_source_dump"

DEFAULT_CHUNK_MB = 15
DEFAULT_MAX_FILE_MB = 5

# NO-FLAGS: patch-friendly + repo-clean
DEFAULT_LINE_NUMBERS = True
DEFAULT_RESPECT_GITIGNORE = True

BINARY_SAMPLE_BYTES = 8192
BINARY_CTRL_THRESHOLD = 0.30

DEFAULT_EXCLUDE_DIR_NAMES: Set[str] = {
    ".git",
    ".hg",
    ".svn",
    ".venv",
    "venv",
    "__pycache__",
    ".pytest_cache",
    ".hypothesis",
    ".mypy_cache",
    ".ruff_cache",
    ".tox",
    "build",
    "dist",
    ".idea",
    ".vscode",
    "htmlcov",
    ".eggs",
    "node_modules",
    ".ipynb_checkpoints",
    # project-specific noise dirs you already care about
    ".glyph_cache",
    ".cl_build",
    ".cl_build_test",
    "generated_worlds",
    "tmp_fs_profile_test",
    "Project Blueprints",
    # never re-dump our own output
    DEFAULT_DUMP_DIRNAME,
}

BINARY_EXTS = {
    ".png",
    ".jpg",
    ".jpeg",
    ".gif",
    ".webp",
    ".ico",
    ".pdf",
    ".zip",
    ".tar",
    ".gz",
    ".bz2",
    ".xz",
    ".7z",
    ".rar",
    ".exe",
    ".dll",
    ".so",
    ".dylib",
    ".whl",
    ".pt",
    ".pth",
    ".ckpt",
    ".onnx",
    ".pkl",
    ".pickle",
    ".npy",
    ".npz",
    ".bin",
    ".mp3",
    ".wav",
    ".mp4",
    ".mov",
    ".avi",
}

# Share-safe excludes (only auto-applied in --mode share)
SAFE_SHARE_EXCLUDE_GLOBS = [
    "**/.env",
    "**/.env.*",
    "**/*.pem",
    "**/*.key",
    "**/*.p12",
    "**/*.pfx",
    "**/id_rsa",
    "**/id_ed25519",
    "**/*.sqlite",
    "**/*.db",
]


# Always excluded (even in internal mode). These are runtime-generated datasets.
# Example output paths shown in scripts/npe/dump_npe_dataset.py docs.
DEFAULT_EXCLUDE_GLOBS = [
    "data/npe_runtime_metrics*",
]

# Required build-target roots for audit-complete dumps.
# Relative to repository root.
BUILD_TARGET_ROOTS: Dict[str, List[str]] = {
    "ace_runtime": [
        "ace/core",
        "ace/covenant",
        "ace/worlds",
        "ace/effect_boundary",
        "ace/system/boot",
    ],
    "ace_tools": [
        "ace/tools/cli",
        "ace/tools/api",
        "ace/tools/repl",
        "ace/tools/debugger",
        "ace/tools/profiler",
        "ace/tools/visualizer",
        "ace/tools/lsp",
    ],
}

EXT_TO_LANG: Dict[str, str] = {
    ".py": "python",
    ".pyi": "python",
    ".js": "javascript",
    ".jsx": "javascript",
    ".ts": "typescript",
    ".tsx": "typescript",
    ".json": "json",
    ".toml": "toml",
    ".yaml": "yaml",
    ".yml": "yaml",
    ".md": "markdown",
    ".rst": "rst",
    ".txt": "text",
    ".ini": "ini",
    ".cfg": "ini",
    ".xml": "xml",
    ".html": "html",
    ".css": "css",
    ".sh": "bash",
    ".ps1": "powershell",
    ".bat": "batch",
    ".cmd": "batch",
    ".cl": "cl",
}

GENERATED_MARKERS = [
    "AUTOGENERATED",
    "AUTO-GENERATED",
    "GENERATED FILE",
    "DO NOT EDIT",
    "DO NOT MODIFY",
    "Generated by",
    "This file was generated",
    "Code generated",
]


# ----------------------------
# Redaction + secret detection
# ----------------------------

# (name, regex, replacement)
_SECRET_PATTERNS: List[Tuple[str, re.Pattern[str], str]] = [
    (
        "private_key_block",
        re.compile(
            r"-----BEGIN(?:[A-Z ]+)?PRIVATE KEY-----.*?-----END(?:[A-Z ]+)?PRIVATE KEY-----",
            re.S,
        ),
        "[REDACTED_PRIVATE_KEY_BLOCK]",
    ),
    (
        "aws_access_key_id",
        re.compile(r"\bAKIA[0-9A-Z]{16}\b"),
        "[REDACTED_AWS_ACCESS_KEY_ID]",
    ),
    (
        "aws_temp_access_key_id",
        re.compile(r"\bASIA[0-9A-Z]{16}\b"),
        "[REDACTED_AWS_TEMP_ACCESS_KEY_ID]",
    ),
    (
        "openai_like_api_key",
        re.compile(r"\bsk-[A-Za-z0-9]{20,}\b"),
        "[REDACTED_API_KEY]",
    ),
    (
        "github_token",
        re.compile(r"\bghp_[A-Za-z0-9]{30,}\b"),
        "[REDACTED_GITHUB_TOKEN]",
    ),
    (
        "bearer_token",
        re.compile(r"\bBearer\s+[A-Za-z0-9\-\._~\+/]+=*\b"),
        "Bearer [REDACTED_BEARER_TOKEN]",
    ),
]


def find_secret_hits(text: str) -> List[str]:
    hits: List[str] = []
    for name, pat, _repl in _SECRET_PATTERNS:
        try:
            if pat.search(text):
                hits.append(name)
        except re.error:
            # Extremely defensive: if a regex ever fails, don't crash dump.
            continue
    return hits


def redact_secrets(text: str) -> str:
    out = text
    for _name, pat, repl in _SECRET_PATTERNS:
        out = pat.sub(repl, out)
    return out


# ----------------------------
# Records
# ----------------------------


@dataclass
class IncludedFile:
    path: str
    bytes: int
    sha256: str
    mtime_utc: str
    encoding: str
    lang: str
    generated: bool
    part: int
    part_file: str
    offset_bytes: int
    offset_lines: int
    content_lines: int
    secret_hits: List[str]


@dataclass
class SkippedFile:
    path: str
    reason: str
    bytes: Optional[int] = None


@dataclass
class DumpConfig:
    root: str
    dump_dir: str
    out_basename: str
    single_file: bool
    chunk_size_bytes: int
    max_file_bytes: int
    normalize_eol: bool
    line_numbers: bool
    redact_secrets: bool
    sanitize_paths: bool
    include_globs: List[str]
    exclude_globs: List[str]
    exclude_dir_names: List[str]
    include_binary_metadata: bool
    respect_gitignore: bool
    enforce_build_targets: bool
    include_git_info: bool
    omit_timestamps: bool
    mode: str
    dump_format_version: int


# ----------------------------
# Helpers
# ----------------------------


def _default_root_dir() -> Path:
    # Prefer repository root when script lives in a subfolder (e.g. Spec Docs/).
    script_dir = Path(__file__).resolve().parent
    if (script_dir / "ace").is_dir():
        return script_dir
    if (script_dir.parent / "ace").is_dir():
        return script_dir.parent
    return script_dir


def utc_now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def detect_lang(path: Path) -> str:
    return EXT_TO_LANG.get(
        path.suffix.lower(), path.suffix.lower().lstrip(".") or "text"
    )


def normalize_eol(text: str) -> str:
    return text.replace("\r\n", "\n").replace("\r", "\n")


def add_line_numbers(text: str) -> str:
    lines = text.splitlines()
    width = max(4, len(str(len(lines) if lines else 1)))
    numbered = "\n".join(f"{i + 1:{width}d}: {line}" for i, line in enumerate(lines))
    if text.endswith("\n"):
        numbered += "\n"
    return numbered


def looks_binary_sample(sample: bytes) -> bool:
    if not sample:
        return False
    if b"\x00" in sample:
        return True
    ctrl = 0
    for b in sample:
        if b in (9, 10, 13):
            continue
        if b < 32 or b == 127:
            ctrl += 1
    return (ctrl / len(sample)) > BINARY_CTRL_THRESHOLD


def is_probably_text(path: Path) -> bool:
    ext = path.suffix.lower()
    if ext in BINARY_EXTS:
        return False
    try:
        with path.open("rb") as f:
            sample = f.read(BINARY_SAMPLE_BYTES)
    except OSError:
        return False
    return not looks_binary_sample(sample)


def decode_bytes(raw: bytes) -> Tuple[str, str]:
    # BOM-aware decoding
    if raw.startswith(b"\xff\xfe\x00\x00") or raw.startswith(b"\x00\x00\xfe\xff"):
        try:
            return raw.decode("utf-32"), "utf-32"
        except UnicodeDecodeError:
            pass
    if raw.startswith(b"\xff\xfe") or raw.startswith(b"\xfe\xff"):
        try:
            return raw.decode("utf-16"), "utf-16"
        except UnicodeDecodeError:
            pass
    if raw.startswith(b"\xef\xbb\xbf"):
        try:
            return raw.decode("utf-8-sig"), "utf-8-sig"
        except UnicodeDecodeError:
            pass
    try:
        return raw.decode("utf-8"), "utf-8"
    except UnicodeDecodeError:
        return raw.decode("latin-1", errors="replace"), "latin-1"


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        while True:
            chunk = f.read(1024 * 1024)
            if not chunk:
                break
            h.update(chunk)
    return h.hexdigest()


def matches_any_glob(rel_posix: str, globs: Sequence[str]) -> bool:
    return any(fnmatch.fnmatchcase(rel_posix, g) for g in globs)


def is_generated_file(rel_posix: str, text: str) -> bool:
    lowered = rel_posix.lower()
    if (
        "/.glyph_cache/" in lowered
        or "/.cl_build" in lowered
        or "/generated_" in lowered
        or "/generated/" in lowered
        or "/tmp_" in lowered
    ):
        return True
    head = text[:2000]
    return any(marker in head for marker in GENERATED_MARKERS)


def _norm_rel_root(path: str) -> str:
    return path.replace("\\", "/").strip("/")


def path_matches_target_roots(rel_posix: str) -> bool:
    rel = _norm_rel_root(rel_posix)
    for roots in BUILD_TARGET_ROOTS.values():
        for root in roots:
            rr = _norm_rel_root(root)
            if rel == rr or rel.startswith(rr + "/"):
                return True
    return False


def _expected_target_file_map(all_files_rel: List[str]) -> Dict[str, Set[str]]:
    out: Dict[str, Set[str]] = {}
    for target, roots in BUILD_TARGET_ROOTS.items():
        expected: Set[str] = set()
        for rel in all_files_rel:
            rel_norm = _norm_rel_root(rel)
            for root in roots:
                rr = _norm_rel_root(root)
                if rel_norm == rr or rel_norm.startswith(rr + "/"):
                    expected.add(rel_norm)
                    break
        out[target] = expected
    return out


def compute_build_target_completeness(
    root: Path,
    *,
    all_files_rel: List[str],
    included: List[IncludedFile],
) -> Dict[str, Dict[str, Any]]:
    expected_map = _expected_target_file_map(all_files_rel)
    included_map = {inc.path: inc.sha256 for inc in included}

    report: Dict[str, Dict[str, Any]] = {}
    for target, roots in BUILD_TARGET_ROOTS.items():
        missing_roots = [
            _norm_rel_root(r)
            for r in roots
            if not (root / _norm_rel_root(r)).exists()
        ]
        expected_files = sorted(expected_map.get(target, set()), key=str.casefold)
        missing_files = [p for p in expected_files if p not in included_map]
        included_sha256 = [
            {"path": p, "sha256": included_map[p]}
            for p in expected_files
            if p in included_map
        ]
        report[target] = {
            "target": target,
            "roots": [_norm_rel_root(r) for r in roots],
            "missing_roots": missing_roots,
            "expected_file_count": len(expected_files),
            "included_file_count": len(included_sha256),
            "missing_file_count": len(missing_files) + len(missing_roots),
            "complete": (len(missing_roots) == 0 and len(missing_files) == 0),
            "missing_files": missing_files,
            "included_sha256": included_sha256,
        }
    return report


# ----------------------------
# Import/dependency tracing for --focus mode
# ----------------------------

# Patterns to extract imports from various file types
_IMPORT_PATTERNS: Dict[str, List[re.Pattern[str]]] = {
    "python": [
        re.compile(r"^\s*from\s+([\w.]+)\s+import", re.MULTILINE),
        re.compile(r"^\s*import\s+([\w.]+)", re.MULTILINE),
    ],
    "typescript": [
        re.compile(r'import\s+.*?\s+from\s+["\']([^"\']+)["\']', re.MULTILINE),
        re.compile(r'import\s*\(\s*["\']([^"\']+)["\']\s*\)', re.MULTILINE),
        re.compile(r'require\s*\(\s*["\']([^"\']+)["\']\s*\)', re.MULTILINE),
        re.compile(r'export\s+.*?\s+from\s+["\']([^"\']+)["\']', re.MULTILINE),
    ],
    "javascript": [
        re.compile(r'import\s+.*?\s+from\s+["\']([^"\']+)["\']', re.MULTILINE),
        re.compile(r'import\s*\(\s*["\']([^"\']+)["\']\s*\)', re.MULTILINE),
        re.compile(r'require\s*\(\s*["\']([^"\']+)["\']\s*\)', re.MULTILINE),
        re.compile(r'export\s+.*?\s+from\s+["\']([^"\']+)["\']', re.MULTILINE),
    ],
}


def extract_imports(file_path: Path, text: str, lang: str) -> List[str]:
    """Extract import paths from a source file."""
    imports: List[str] = []
    patterns = _IMPORT_PATTERNS.get(lang, [])

    for pat in patterns:
        for match in pat.finditer(text):
            imports.append(match.group(1))

    return imports


def resolve_import_to_file(
    import_path: str,
    source_file: Path,
    root: Path,
    lang: str,
) -> Optional[Path]:
    """Attempt to resolve an import path to an actual file."""
    # Skip node_modules, external packages, etc
    if import_path.startswith(("@", "node_modules", "react", "redux")):
        return None
    if not import_path.startswith((".", "/")):
        # Could be a package - try to resolve as relative to root for Python
        if lang == "python":
            # Convert dots to path separators
            rel_path = import_path.replace(".", "/")
            candidates = [
                root / f"{rel_path}.py",
                root / rel_path / "__init__.py",
            ]
            for cand in candidates:
                if cand.exists():
                    return cand
        return None

    source_dir = source_file.parent

    # Handle relative imports
    if import_path.startswith("./") or import_path.startswith("../"):
        resolved = (source_dir / import_path).resolve()
    elif import_path.startswith("/"):
        # Absolute from root (common in TS/JS with baseUrl)
        resolved = (root / import_path.lstrip("/")).resolve()
    else:
        resolved = (source_dir / import_path).resolve()

    # Try various extensions
    if lang in ("typescript", "javascript"):
        extensions = [
            ".ts",
            ".tsx",
            ".js",
            ".jsx",
            "/index.ts",
            "/index.tsx",
            "/index.js",
        ]
    elif lang == "python":
        extensions = [".py", "/__init__.py"]
    else:
        extensions = [""]

    # If already has extension, check it directly
    if resolved.suffix in (".ts", ".tsx", ".js", ".jsx", ".py"):
        if resolved.exists():
            return resolved

    for ext in extensions:
        candidate = (
            Path(str(resolved) + ext)
            if not ext.startswith("/")
            else resolved / ext.lstrip("/")
        )
        if candidate.exists():
            return candidate

    return None


def trace_dependencies(
    focus_files: List[Path],
    root: Path,
    max_depth: int = 5,
) -> Set[Path]:
    """
    Given a list of focus files, trace their imports and return
    all external files they depend on.
    """
    visited: Set[Path] = set(focus_files)
    external_deps: Set[Path] = set()
    to_process: List[Tuple[Path, int]] = [(f, 0) for f in focus_files]

    while to_process:
        file_path, depth = to_process.pop(0)

        if depth >= max_depth:
            continue

        if not file_path.exists():
            continue

        try:
            text = file_path.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue

        lang = detect_lang(file_path)
        imports = extract_imports(file_path, text, lang)

        for imp in imports:
            resolved = resolve_import_to_file(imp, file_path, root, lang)
            if resolved and resolved not in visited:
                visited.add(resolved)
                external_deps.add(resolved)
                # Continue tracing from external deps
                to_process.append((resolved, depth + 1))

    return external_deps


def try_run(cmd: List[str], cwd: Path) -> Optional[str]:
    try:
        proc = subprocess.run(
            cmd,
            cwd=str(cwd),
            capture_output=True,
            text=True,
            check=False,
        )
    except OSError:
        return None
    if proc.returncode != 0:
        return None
    return (proc.stdout or "").strip()


def git_info(root: Path) -> Dict[str, object]:
    top = try_run(["git", "rev-parse", "--show-toplevel"], cwd=root)
    if not top:
        return {}
    head = try_run(["git", "rev-parse", "HEAD"], cwd=root) or ""
    branch = try_run(["git", "rev-parse", "--abbrev-ref", "HEAD"], cwd=root) or ""
    describe = (
        try_run(["git", "describe", "--always", "--dirty", "--tags"], cwd=root) or ""
    )
    status = try_run(["git", "status", "--porcelain"], cwd=root)
    return {
        "repo_root": top,
        "head": head,
        "branch": branch,
        "describe": describe,
        "dirty": bool(status),
        "status_porcelain": status.splitlines() if status else [],
    }


def git_ls_files(root: Path) -> Optional[List[str]]:
    top = try_run(["git", "rev-parse", "--show-toplevel"], cwd=root)
    if not top:
        return None
    repo_root = Path(top)

    def run_z(cmd: List[str]) -> Optional[List[str]]:
        try:
            proc = subprocess.run(
                cmd, cwd=str(repo_root), capture_output=True, check=False
            )
        except OSError:
            return None
        if proc.returncode != 0:
            return None
        raw = proc.stdout or b""
        if not raw:
            return []
        parts = raw.split(b"\x00")
        return [p.decode("utf-8", errors="replace") for p in parts if p]

    tracked = run_z(["git", "ls-files", "-z"])
    if tracked is None:
        return None
    others = run_z(["git", "ls-files", "-z", "--others", "--exclude-standard"])
    if others is None:
        return None

    combined = sorted(set(tracked + others), key=lambda s: s.casefold())
    return combined


def enumerate_files(
    root: Path,
    *,
    respect_gitignore: bool,
    exclude_dir_names: Set[str],
) -> List[Path]:
    # Prefer git-aware listing (tracked + untracked not ignored), fallback to os.walk
    if respect_gitignore:
        rels = git_ls_files(root)
        if rels is not None:
            repo_top = try_run(["git", "rev-parse", "--show-toplevel"], cwd=root)
            if repo_top:
                repo_root = Path(repo_top)
                out: List[Path] = []
                for rel in rels:
                    p = repo_root / rel
                    try:
                        p.relative_to(root)
                    except ValueError:
                        continue

                    rel_parts = p.relative_to(root).parts
                    if any(
                        (part in exclude_dir_names) or part.endswith(".egg-info")
                        for part in rel_parts
                    ):
                        continue

                    if p.is_file():
                        out.append(p)

                return sorted(
                    out, key=lambda p: p.relative_to(root).as_posix().casefold()
                )

    # Fallback: os.walk
    files: List[Path] = []
    for dirpath, dirnames, filenames in os.walk(
        str(root), topdown=True, followlinks=False
    ):
        # prune excluded dirs
        pruned = [
            d
            for d in list(dirnames)
            if d in exclude_dir_names or d.endswith(".egg-info")
        ]
        for d in pruned:
            dirnames.remove(d)

        base = Path(dirpath)
        for name in filenames:
            files.append(base / name)

    return sorted(files, key=lambda p: p.relative_to(root).as_posix().casefold())


def write_bytes(out, data: bytes) -> Tuple[int, int]:
    out.write(data)
    return len(data), data.count(b"\n")


# ----------------------------
# Dump core
# ----------------------------


def dump_project(
    *,
    root: Path,
    dump_dir: Path,
    out_basename: str,
    single_file: bool,
    chunk_size_bytes: int,
    max_file_bytes: int,
    normalize_eol_flag: bool,
    line_numbers_flag: bool,
    redact_secrets_flag: bool,
    sanitize_paths_flag: bool,
    include_globs: List[str],
    exclude_globs: List[str],
    exclude_dir_names: Set[str],
    include_binary_metadata: bool,
    respect_gitignore_flag: bool,
    enforce_build_targets: bool,
    include_git_info_flag: bool,
    omit_timestamps_flag: bool,
    mode: str,
    focus_external_files: Optional[Set[Path]] = None,
) -> None:
    dump_dir.mkdir(parents=True, exist_ok=True)

    # Remove prior outputs for same basename
    for p in dump_dir.glob(f"{out_basename}*.txt"):
        p.unlink(missing_ok=True)
    (dump_dir / "project_manifest.txt").unlink(missing_ok=True)
    (dump_dir / "project_manifest.json").unlink(missing_ok=True)

    generated_at = (
        "1970-01-01T00:00:00+00:00" if omit_timestamps_flag else utc_now_iso()
    )

    gi: Dict[str, object] = {}
    if include_git_info_flag and not omit_timestamps_flag:
        gi = git_info(root)

    cfg = DumpConfig(
        root=str(root),
        dump_dir=str(dump_dir),
        out_basename=out_basename,
        single_file=single_file,
        chunk_size_bytes=chunk_size_bytes,
        max_file_bytes=max_file_bytes,
        normalize_eol=normalize_eol_flag,
        line_numbers=line_numbers_flag,
        redact_secrets=redact_secrets_flag,
        sanitize_paths=sanitize_paths_flag,
        include_globs=include_globs,
        exclude_globs=exclude_globs,
        exclude_dir_names=sorted(exclude_dir_names),
        include_binary_metadata=include_binary_metadata,
        respect_gitignore=respect_gitignore_flag,
        enforce_build_targets=enforce_build_targets,
        include_git_info=include_git_info_flag,
        omit_timestamps=omit_timestamps_flag,
        mode=mode,
        dump_format_version=DUMP_FORMAT_VERSION,
    )

    files = enumerate_files(
        root,
        respect_gitignore=respect_gitignore_flag,
        exclude_dir_names=exclude_dir_names,
    )

    included: List[IncludedFile] = []
    skipped: List[SkippedFile] = []
    reason_counts: Dict[str, int] = {}

    part_idx = 1

    def part_path(i: int) -> Path:
        if single_file:
            return dump_dir / f"{out_basename}.txt"
        return dump_dir / f"{out_basename}_part{i:02d}.txt"

    out_path = part_path(part_idx)
    print(f"[dump] Writing {out_path} ...")
    out = out_path.open("wb")

    bytes_in_part = 0
    lines_in_part = 0

    parts: Dict[str, Dict[str, Any]] = {}

    # Path sanitization: replace any occurrence of root absolute path with <ROOT>
    root_re = re.compile(re.escape(str(root)), re.IGNORECASE)

    def sanitize_text(text: str) -> str:
        if not sanitize_paths_flag:
            return text
        return root_re.sub("<ROOT>", text)

    def start_part() -> None:
        parts[str(part_idx)] = {"path": str(out_path), "files": []}

    def write_part_header() -> None:
        nonlocal bytes_in_part, lines_in_part
        header_obj = {
            "type": "PROJECT_DUMP_HEADER",
            "dump_format_version": DUMP_FORMAT_VERSION,
            "generated_at_utc": generated_at,
            "root": ("<ROOT>" if sanitize_paths_flag else str(root)),
            "part": part_idx,
            "single_file": single_file,
            "chunk_size_bytes": chunk_size_bytes,
            "max_file_bytes": max_file_bytes,
            "normalize_eol": normalize_eol_flag,
            "line_numbers": line_numbers_flag,
            "redact_secrets": redact_secrets_flag,
            "sanitize_paths": sanitize_paths_flag,
            "include_globs": include_globs,
            "exclude_globs": exclude_globs,
            "exclude_dir_names": sorted(exclude_dir_names),
            "include_binary_metadata": include_binary_metadata,
            "respect_gitignore": respect_gitignore_flag,
            "git": (None if not gi else gi),
            "env": {
                "python": sys.version.split()[0],
                "platform": platform.platform(),
                "system": platform.system(),
                "machine": platform.machine(),
            },
        }
        text = (
            "===== PROJECT SOURCE DUMP =====\n"
            + json.dumps(header_obj, ensure_ascii=False)
            + "\n"
            + "===============================\n\n"
        )
        b = text.encode("utf-8")
        db, dl = write_bytes(out, b)
        bytes_in_part += db
        lines_in_part += dl

    def roll_part() -> None:
        nonlocal part_idx, out_path, out, bytes_in_part, lines_in_part
        if single_file:
            return
        out.close()
        part_idx += 1
        out_path = part_path(part_idx)
        print(f"[dump] Writing {out_path} ...")
        out = out_path.open("wb")
        bytes_in_part = 0
        lines_in_part = 0
        start_part()
        write_part_header()

    start_part()
    write_part_header()

    secret_hits_total: Dict[str, List[str]] = {}

    for abs_path in files:
        rel = abs_path.relative_to(root)
        rel_posix = rel.as_posix()
        is_required_build_target = (
            enforce_build_targets and path_matches_target_roots(rel_posix)
        )

        # glob filters
        if (
            exclude_globs
            and matches_any_glob(rel_posix, exclude_globs)
            and not is_required_build_target
        ):
            skipped.append(SkippedFile(path=rel_posix, reason="excluded_by_glob"))
            continue

        # Check if file is in focus_external_files (bypass include_globs check for dependencies)
        is_focus_external = focus_external_files and abs_path in focus_external_files

        if (
            include_globs
            and not matches_any_glob(rel_posix, include_globs)
            and not is_focus_external
            and not is_required_build_target
        ):
            skipped.append(SkippedFile(path=rel_posix, reason="not_in_include_globs"))
            continue

        try:
            st = abs_path.stat()
        except OSError:
            skipped.append(SkippedFile(path=rel_posix, reason="stat_failed"))
            continue

        size = int(st.st_size)
        if size > max_file_bytes:
            skipped.append(
                SkippedFile(
                    path=rel_posix, reason=f"too_large({size} bytes)", bytes=size
                )
            )
            continue

        is_text = is_probably_text(abs_path)

        if not is_text:
            if include_binary_metadata:
                try:
                    digest = sha256_file(abs_path)
                except OSError:
                    digest = ""
                mtime_utc = (
                    "1970-01-01T00:00:00+00:00"
                    if omit_timestamps_flag
                    else datetime.fromtimestamp(
                        st.st_mtime, tz=timezone.utc
                    ).isoformat()
                )
                meta = {
                    "type": "BINARY_FILE",
                    "path": rel_posix,
                    "bytes": size,
                    "sha256": digest,
                    "mtime_utc": mtime_utc,
                    "ext": abs_path.suffix.lower(),
                }
                block = (
                    "<<<FILE_BEGIN>>>\n"
                    + json.dumps(meta, ensure_ascii=False)
                    + "\n<<<BINARY_CONTENT_OMITTED>>>\n<<<FILE_END>>>\n\n"
                )
                b = block.encode("utf-8")
                if (
                    (not single_file)
                    and (bytes_in_part + len(b) > chunk_size_bytes)
                    and bytes_in_part > 0
                ):
                    roll_part()
                offset_b = bytes_in_part
                offset_l = lines_in_part
                db, dl = write_bytes(out, b)
                bytes_in_part += db
                lines_in_part += dl
                parts[str(part_idx)]["files"].append(
                    {
                        "path": rel_posix,
                        "offset_bytes": offset_b,
                        "offset_lines": offset_l,
                    }
                )  # type: ignore[index]
            else:
                skipped.append(
                    SkippedFile(path=rel_posix, reason="binary_or_nontext", bytes=size)
                )
            continue

        # hash + read + decode
        try:
            digest = sha256_file(abs_path)
        except OSError:
            skipped.append(
                SkippedFile(path=rel_posix, reason="hash_failed", bytes=size)
            )
            continue

        try:
            raw = abs_path.read_bytes()
        except OSError:
            skipped.append(
                SkippedFile(path=rel_posix, reason="read_failed", bytes=size)
            )
            continue

        text, encoding_used = decode_bytes(raw)

        if normalize_eol_flag:
            text = normalize_eol(text)

        # detect secrets BEFORE redaction so internal mode warns accurately
        hits = find_secret_hits(text)
        if hits:
            secret_hits_total[rel_posix] = hits

        if redact_secrets_flag:
            text = redact_secrets(text)

        if sanitize_paths_flag:
            text = sanitize_text(text)

        if line_numbers_flag:
            text = add_line_numbers(text)

        lang = detect_lang(abs_path)
        mtime_utc = (
            "1970-01-01T00:00:00+00:00"
            if omit_timestamps_flag
            else datetime.fromtimestamp(st.st_mtime, tz=timezone.utc).isoformat()
        )
        gen = is_generated_file(rel_posix, text)

        content_lines = text.count("\n") + (
            0 if (text == "" or text.endswith("\n")) else 1
        )

        meta = {
            "type": "TEXT_FILE",
            "path": rel_posix,
            "bytes": size,
            "sha256": digest,
            "mtime_utc": mtime_utc,
            "encoding": encoding_used,
            "lang": lang,
            "generated": gen,
            "secret_hits": hits,
        }

        block = (
            "<<<FILE_BEGIN>>>\n"
            + json.dumps(meta, ensure_ascii=False)
            + "\n<<<CONTENT_BEGIN>>>\n"
            + text
            + ("\n" if (text and not text.endswith("\n")) else "")
            + "<<<CONTENT_END>>>\n<<<FILE_END>>>\n\n"
        )
        b = block.encode("utf-8")

        if (
            (not single_file)
            and (bytes_in_part + len(b) > chunk_size_bytes)
            and bytes_in_part > 0
        ):
            roll_part()

        offset_b = bytes_in_part
        offset_l = lines_in_part
        db, dl = write_bytes(out, b)
        bytes_in_part += db
        lines_in_part += dl

        parts[str(part_idx)]["files"].append(
            {"path": rel_posix, "offset_bytes": offset_b, "offset_lines": offset_l}
        )  # type: ignore[index]

        included.append(
            IncludedFile(
                path=rel_posix,
                bytes=size,
                sha256=digest,
                mtime_utc=mtime_utc,
                encoding=encoding_used,
                lang=lang,
                generated=gen,
                part=part_idx,
                part_file=str(out_path),
                offset_bytes=offset_b,
                offset_lines=offset_l,
                content_lines=content_lines,
                secret_hits=hits,
            )
        )

    out.close()

    for s in skipped:
        reason_counts[s.reason] = reason_counts.get(s.reason, 0) + 1

    all_files_rel = [p.relative_to(root).as_posix() for p in files]
    build_target_report = compute_build_target_completeness(
        root,
        all_files_rel=all_files_rel,
        included=included,
    )

    # Manifests
    manifest_txt = dump_dir / "project_manifest.txt"
    manifest_json = dump_dir / "project_manifest.json"

    with manifest_txt.open("w", encoding="utf-8") as mf:
        mf.write(f"ROOT: {root}\n")
        mf.write(f"DUMP_DIR: {dump_dir}\n")
        mf.write(f"GENERATED_AT_UTC: {generated_at}\n")
        mf.write(f"MODE: {mode}\n")
        mf.write(f"DUMP_FORMAT_VERSION: {DUMP_FORMAT_VERSION}\n")
        mf.write(f"SINGLE_FILE: {single_file}\n")
        mf.write(f"CHUNK_SIZE_BYTES: {chunk_size_bytes}\n")
        mf.write(f"MAX_FILE_BYTES: {max_file_bytes}\n")
        mf.write(f"NORMALIZE_EOL: {normalize_eol_flag}\n")
        mf.write(f"LINE_NUMBERS: {line_numbers_flag}\n")
        mf.write(f"REDACT_SECRETS: {redact_secrets_flag}\n")
        mf.write(f"SANITIZE_PATHS: {sanitize_paths_flag}\n")
        mf.write(f"INCLUDE_GLOBS: {include_globs}\n")
        mf.write(f"EXCLUDE_GLOBS: {exclude_globs}\n")
        mf.write(f"RESPECT_GITIGNORE: {respect_gitignore_flag}\n")
        mf.write(f"ENFORCE_BUILD_TARGETS: {enforce_build_targets}\n")
        mf.write(f"INCLUDE_BINARY_METADATA: {include_binary_metadata}\n")
        mf.write("\n")

        if gi:
            mf.write("GIT:\n")
            mf.write(f"  repo_root: {gi.get('repo_root', '')}\n")
            mf.write(f"  head: {gi.get('head', '')}\n")
            mf.write(f"  branch: {gi.get('branch', '')}\n")
            mf.write(f"  describe: {gi.get('describe', '')}\n")
            mf.write(f"  dirty: {gi.get('dirty', '')}\n")
            mf.write("\n")

        mf.write(f"PARTS ({len(parts)}):\n")
        for k in sorted(parts.keys(), key=lambda s: int(s)):
            mf.write(f"  - part{k.zfill(2)}: {parts[k]['path']}\n")
            for file_entry in parts[k]["files"]:
                mf.write(
                    f"      * {file_entry['path']} @ bytes={file_entry['offset_bytes']} lines={file_entry['offset_lines']}\n"
                )
        mf.write("\n")

        mf.write("BUILD TARGET COMPLETENESS:\n")
        for target in sorted(build_target_report.keys(), key=str.casefold):
            info = build_target_report[target]
            mf.write(
                f"  - {target}: complete={info['complete']} expected={info['expected_file_count']} "
                f"included={info['included_file_count']} missing={info['missing_file_count']}\n"
            )
            if info["missing_roots"]:
                mf.write("      missing_roots:\n")
                for mr in info["missing_roots"]:
                    mf.write(f"        * {mr}\n")
            if info["missing_files"]:
                mf.write("      missing_files:\n")
                for mf_path in info["missing_files"]:
                    mf.write(f"        * {mf_path}\n")
            if info["included_sha256"]:
                mf.write("      sha256:\n")
                for item in info["included_sha256"]:
                    mf.write(f"        * {item['path']} :: {item['sha256']}\n")
        mf.write("\n")

        mf.write(f"INCLUDED FILES ({len(included)}):\n")
        for inc in included:
            mf.write(
                f"  - {inc.path} :: bytes={inc.bytes} sha256={inc.sha256} "
                f"mtime_utc={inc.mtime_utc} enc={inc.encoding} lang={inc.lang} "
                f"generated={inc.generated} part={inc.part} "
                f"offset_bytes={inc.offset_bytes} offset_lines={inc.offset_lines} "
                f"content_lines={inc.content_lines} secret_hits={inc.secret_hits}\n"
            )

        mf.write("\n")
        mf.write(f"SKIPPED FILES ({len(skipped)}):\n")
        for skp in skipped:
            extra = f" bytes={skp.bytes}" if skp.bytes is not None else ""
            mf.write(f"  - {skp.path} :: {skp.reason}{extra}\n")

        mf.write("\nSKIP REASON COUNTS:\n")
        for reason, cnt in sorted(reason_counts.items(), key=lambda x: (-x[1], x[0])):
            mf.write(f"  - {reason}: {cnt}\n")

        if secret_hits_total:
            mf.write("\nSECRET HITS (detected patterns):\n")
            for pth in sorted(secret_hits_total.keys(), key=str.casefold):
                mf.write(f"  - {pth}: {secret_hits_total[pth]}\n")

    payload: Dict[str, Any] = {
        "config": asdict(cfg),
        "generated_at_utc": generated_at,
        "git": gi if gi else None,
        "parts": parts,
        "build_target_completeness": build_target_report,
        "included": [asdict(x) for x in included],
        "skipped": [asdict(x) for x in skipped],
        "skipped_reason_counts": reason_counts,
        "secret_hits": secret_hits_total,
    }
    with manifest_json.open("w", encoding="utf-8") as jf:
        json.dump(payload, jf, indent=2, ensure_ascii=False)

    print(f"[dump] Done. Included: {len(included)} | Skipped: {len(skipped)}")
    print(f"[dump] Manifest (txt): {manifest_txt}")
    print(f"[dump] Manifest (json): {manifest_json}")
    for target in sorted(build_target_report.keys(), key=str.casefold):
        info = build_target_report[target]
        status = "PASS" if info["complete"] else "FAIL"
        print(
            f"[dump] Build target {target}: {status} "
            f"(expected={info['expected_file_count']} included={info['included_file_count']} missing={info['missing_file_count']})"
        )

    # Loud warning if secrets were detected but not redacted (internal mode)
    if secret_hits_total and not redact_secrets_flag:
        print(
            "\n[warn] Potential secrets detected (redaction is OFF).", file=sys.stderr
        )
        print(
            "       If you're sharing this dump, re-run with: python dump_project_sources.py --mode share",
            file=sys.stderr,
        )


# ----------------------------
# CLI
# ----------------------------


def main() -> None:
    default_root = _default_root_dir()

    ap = argparse.ArgumentParser(
        description="Dump project sources into AI-friendly text parts + manifests."
    )
    ap.add_argument(
        "--root",
        type=str,
        default=str(default_root),
        help="Project root to dump. Default: repository root (auto-detected from script location).",
    )
    ap.add_argument(
        "--dump-dir",
        type=str,
        default=DEFAULT_DUMP_DIRNAME,
        help=f"Output folder name under root (default: {DEFAULT_DUMP_DIRNAME}).",
    )
    ap.add_argument(
        "--out-basename",
        type=str,
        default=DEFAULT_OUT_BASENAME,
        help=f"Base name for output dump files (default: {DEFAULT_OUT_BASENAME}).",
    )
    ap.add_argument(
        "--single-file",
        action="store_true",
        help="Write one dump file instead of chunked parts.",
    )
    ap.add_argument(
        "--chunk-mb",
        type=int,
        default=DEFAULT_CHUNK_MB,
        help=f"Max size per part in MB (default: {DEFAULT_CHUNK_MB}). Ignored with --single-file.",
    )
    ap.add_argument(
        "--max-file-mb",
        type=int,
        default=DEFAULT_MAX_FILE_MB,
        help=f"Skip any single file larger than this MB (default: {DEFAULT_MAX_FILE_MB}).",
    )

    # Defaults: normalize EOL ON, line numbers ON (10/10), gitignore ON (10/10)
    ap.add_argument(
        "--no-normalize-eol",
        action="store_true",
        help="Do NOT normalize CRLF/CR to LF.",
    )

    ap.add_argument(
        "--no-line-numbers",
        dest="line_numbers",
        action="store_false",
        help="Disable line numbers.",
    )
    ap.add_argument(
        "--line-numbers",
        dest="line_numbers",
        action="store_true",
        help="Enable line numbers.",
    )
    ap.set_defaults(line_numbers=DEFAULT_LINE_NUMBERS)

    ap.add_argument(
        "--no-respect-gitignore",
        dest="respect_gitignore",
        action="store_false",
        help="Disable gitignore-aware file listing.",
    )
    ap.add_argument(
        "--respect-gitignore",
        dest="respect_gitignore",
        action="store_true",
        help="Enable gitignore-aware file listing.",
    )
    ap.set_defaults(respect_gitignore=DEFAULT_RESPECT_GITIGNORE)

    ap.add_argument(
        "--no-enforce-build-targets",
        dest="enforce_build_targets",
        action="store_false",
        help="Do not force include/report coverage for ace_runtime and ace_tools target roots.",
    )
    ap.add_argument(
        "--enforce-build-targets",
        dest="enforce_build_targets",
        action="store_true",
        help="Force include/report coverage for ace_runtime and ace_tools target roots.",
    )
    ap.set_defaults(enforce_build_targets=True)

    ap.add_argument(
        "--redact-secrets",
        action="store_true",
        help="Redact common secret patterns from content.",
    )
    ap.add_argument(
        "--sanitize-paths",
        action="store_true",
        help="Replace absolute root path occurrences with <ROOT>.",
    )
    ap.add_argument(
        "--omit-timestamps",
        action="store_true",
        help="Omit timestamps in headers/manifests.",
    )
    ap.add_argument(
        "--include-binary-metadata",
        action="store_true",
        help="Include binary/nontext files as metadata-only blocks (content omitted).",
    )

    ap.add_argument(
        "--include-glob",
        action="append",
        default=[],
        help='Only include files matching this glob (repeatable), e.g. "coherence_lang/**".',
    )
    ap.add_argument(
        "--exclude-glob",
        action="append",
        default=[],
        help='Exclude files matching this glob (repeatable), e.g. "**/*.log".',
    )
    ap.add_argument(
        "--exclude-dir",
        action="append",
        default=[],
        help="Exclude directories by name (repeatable).",
    )

    ap.add_argument(
        "--no-git-info",
        action="store_true",
        help="Do not record git metadata in header/manifest.",
    )

    ap.add_argument(
        "--focus",
        type=str,
        default=None,
        help="Focus on a specific folder + its dependencies. E.g. --focus coherence_lang/ui_alpha. "
        "Dumps all files in the focus folder plus any external files they import.",
    )
    ap.add_argument(
        "--focus-depth",
        type=int,
        default=5,
        help="Max depth to trace dependencies from focus folder (default: 5).",
    )
    ap.add_argument(
        "--focus-no-trace",
        action="store_true",
        help="With --focus, only dump the focus folder itself without tracing dependencies.",
    )
    ap.add_argument(
        "--with-tests",
        action="store_true",
        help="With --focus, also include the matching tests folder (e.g., --focus coherence_lang/npe includes tests/npe/**).",
    )
    ap.add_argument(
        "--separate-tests",
        action="store_true",
        help="With --with-tests, output test files to separate dump file(s) (e.g., npe_tests_part01.txt).",
    )

    ap.add_argument(
        "--mode",
        choices=["internal", "share"],
        default="internal",
        help="internal (default) or share (safe: redaction + sanitization + omit timestamps + safe excludes).",
    )

    args = ap.parse_args()

    root = Path(args.root).resolve()
    if not root.exists() or not root.is_dir():
        print(
            f"[error] root does not exist or is not a directory: {root}",
            file=sys.stderr,
        )
        raise SystemExit(2)

    dump_dir = (root / args.dump_dir).resolve()

    exclude_dir_names = set(DEFAULT_EXCLUDE_DIR_NAMES)
    exclude_dir_names.add(args.dump_dir)  # always exclude output dir
    for d in args.exclude_dir:
        exclude_dir_names.add(d)

    include_globs = list(args.include_glob)
    exclude_globs = DEFAULT_EXCLUDE_GLOBS + list(args.exclude_glob)
    test_include_globs: List[str] = []  # Track test globs separately for --separate-tests

    # Handle --focus mode
    focus_external_files: Set[Path] = set()
    if args.focus:
        focus_path: Path = (root / args.focus).resolve()
        if not focus_path.exists() or not focus_path.is_dir():
            print(
                f"[error] focus path does not exist or is not a directory: {focus_path}",
                file=sys.stderr,
            )
            raise SystemExit(2)

        # Add include glob for focus folder
        focus_rel = focus_path.relative_to(root).as_posix()
        include_globs.append(f"{focus_rel}/**")

        print(f"[focus] Targeting: {focus_rel}/")

        # Extract focus folder name for later use
        focus_parts = focus_rel.split("/")
        focus_name = focus_parts[-1]  # e.g., "swarm" from "coherence_lang/npe/swarm"

        # Handle --with-tests: include matching tests folder
        if args.with_tests:

            # Build list of candidate test locations (in priority order)
            test_candidates: List[Tuple[str, str]] = []  # (tests_rel, description)

            # 1. Exact match: coherence_lang/npe/swarm -> tests/npe/swarm/
            if len(focus_parts) >= 2 and focus_parts[0] == "coherence_lang":
                exact_rel = "tests/" + "/".join(focus_parts[1:])
                test_candidates.append((exact_rel, "exact match"))

            # 2. Parent test folder: coherence_lang/npe/swarm -> tests/npe/ (with pattern matching)
            if len(focus_parts) >= 3 and focus_parts[0] == "coherence_lang":
                parent_rel = "tests/" + focus_parts[1]
                test_candidates.append((parent_rel, f"parent folder with *{focus_name}* pattern"))

            # 3. Fallback: tests/<focus_name>/
            test_candidates.append((f"tests/{focus_name}", "fallback"))

            tests_included = False
            for tests_rel, desc in test_candidates:
                tests_path = root / tests_rel
                if tests_path.exists() and tests_path.is_dir():
                    # Check if this is a parent folder case - use pattern matching
                    if "parent folder" in desc:
                        # Find test files matching the focus name pattern
                        pattern = f"*{focus_name}*"
                        matching_files = list(tests_path.glob(f"**/{pattern}.py"))
                        if matching_files:
                            # Add glob for files matching the pattern
                            test_glob = f"{tests_rel}/**/*{focus_name}*.py"
                            test_include_globs.append(test_glob)
                            if not args.separate_tests:
                                include_globs.append(test_glob)
                            print(f"[focus] Including tests: {tests_rel}/**/*{focus_name}*.py ({len(matching_files)} files)")
                            tests_included = True
                            break
                    else:
                        # Exact folder match - include everything
                        test_glob = f"{tests_rel}/**"
                        test_include_globs.append(test_glob)
                        if not args.separate_tests:
                            include_globs.append(test_glob)
                        print(f"[focus] Including tests: {tests_rel}/")
                        tests_included = True
                        break

            if not tests_included:
                print(f"[focus] No matching tests folder found for {focus_rel}")

        if not args.focus_no_trace:
            # Get all files in focus folder first
            print(f"[focus] Scanning for dependencies (depth={args.focus_depth})...")
            focus_files: List[Path] = []
            for dirpath, dirnames, filenames in os.walk(str(focus_path), topdown=True):
                # prune excluded dirs
                pruned = [
                    d
                    for d in list(dirnames)
                    if d in exclude_dir_names or d.endswith(".egg-info")
                ]
                for d in pruned:
                    dirnames.remove(d)
                base = Path(dirpath)
                for name in filenames:
                    focus_files.append(base / name)

            # Trace dependencies
            focus_external_files = trace_dependencies(
                focus_files,
                root,
                max_depth=args.focus_depth,
            )

            # Filter to only files outside focus folder
            focus_external_files = {
                f
                for f in focus_external_files
                if not str(f).startswith(str(focus_path))
            }

            if focus_external_files:
                print(
                    f"[focus] Found {len(focus_external_files)} external dependencies:"
                )
                for ext_f in sorted(
                    focus_external_files,
                    key=lambda p: p.relative_to(root).as_posix().casefold(),
                )[:10]:
                    print(f"        + {ext_f.relative_to(root).as_posix()}")
                if len(focus_external_files) > 10:
                    print(f"        ... and {len(focus_external_files) - 10} more")
            else:
                print(
                    "[focus] No external dependencies found (all imports are within focus folder or external packages)"
                )

    # Auto-generate output basename and subfolder from focus folder if not explicitly set
    out_basename = args.out_basename
    if args.focus and out_basename == DEFAULT_OUT_BASENAME:
        # Use the focus folder name as the basename (e.g., "ui_alpha" -> "ui_alpha_dump")
        out_basename = f"{focus_name}_dump"
        # Put focused dumps in a subfolder: script_dump/<focus_name>/
        dump_dir = dump_dir / focus_name
        print(f"[focus] Output folder: {dump_dir}")
        print(f"[focus] Output basename: {out_basename}")

    normalize_eol_flag = not bool(args.no_normalize_eol)
    line_numbers_flag = bool(args.line_numbers)
    respect_gitignore_flag = bool(args.respect_gitignore)
    enforce_build_targets_flag = bool(args.enforce_build_targets)

    if args.focus and enforce_build_targets_flag:
        print("[focus] disabling build-target enforcement for focus mode")
        enforce_build_targets_flag = False

    # internal defaults
    redact_flag = bool(args.redact_secrets)
    sanitize_flag = bool(args.sanitize_paths)
    omit_ts_flag = bool(args.omit_timestamps)

    # share mode forces safe behavior
    if args.mode == "share":
        redact_flag = True
        sanitize_flag = True
        omit_ts_flag = True
        exclude_globs = exclude_globs + SAFE_SHARE_EXCLUDE_GLOBS

    chunk_size_bytes = int(args.chunk_mb) * 1024 * 1024
    max_file_bytes = int(args.max_file_mb) * 1024 * 1024

    dump_project(
        root=root,
        dump_dir=dump_dir,
        out_basename=out_basename,
        single_file=bool(args.single_file),
        chunk_size_bytes=chunk_size_bytes,
        max_file_bytes=max_file_bytes,
        normalize_eol_flag=normalize_eol_flag,
        line_numbers_flag=line_numbers_flag,
        redact_secrets_flag=redact_flag,
        sanitize_paths_flag=sanitize_flag,
        include_globs=include_globs,
        exclude_globs=exclude_globs,
        exclude_dir_names=exclude_dir_names,
        include_binary_metadata=bool(args.include_binary_metadata),
        respect_gitignore_flag=respect_gitignore_flag,
        enforce_build_targets=enforce_build_targets_flag,
        include_git_info_flag=not bool(args.no_git_info),
        omit_timestamps_flag=omit_ts_flag,
        mode=args.mode,
        focus_external_files=focus_external_files if focus_external_files else None,
    )

    # If --separate-tests is used, create a separate dump for test files
    if args.separate_tests and test_include_globs:
        test_basename = out_basename.replace("_dump", "_tests")
        if test_basename == out_basename:
            test_basename = f"{out_basename}_tests"
        print(f"\n[separate-tests] Creating separate test dump: {test_basename}")
        dump_project(
            root=root,
            dump_dir=dump_dir,
            out_basename=test_basename,
            single_file=bool(args.single_file),
            chunk_size_bytes=chunk_size_bytes,
            max_file_bytes=max_file_bytes,
            normalize_eol_flag=normalize_eol_flag,
            line_numbers_flag=line_numbers_flag,
            redact_secrets_flag=redact_flag,
            sanitize_paths_flag=sanitize_flag,
            include_globs=test_include_globs,
            exclude_globs=exclude_globs,
            exclude_dir_names=exclude_dir_names,
            include_binary_metadata=bool(args.include_binary_metadata),
            respect_gitignore_flag=respect_gitignore_flag,
            enforce_build_targets=False,
            include_git_info_flag=not bool(args.no_git_info),
            omit_timestamps_flag=omit_ts_flag,
            mode=args.mode,
            focus_external_files=None,  # Tests don't need external deps
        )


if __name__ == "__main__":
    main()
