"""The peer row is drawn from a proven renderer, and the product actually reaches it.

Three laws are discharged over EVERY integer input by the Coherence prover in the `idem` repo at
build time, and the answers ship as `one_link/certified/peer_row.json`:

    the-verified-glyph-requires-verified-trust    scope: exact
    the-name-never-runs-under-the-badge           scope: exact
    nothing-is-drawn-outside-the-row              scope: exact

WHY THIS FILE EXISTS AND NOT JUST THE PROVER'S TESTS. A proof nothing renders from is a capability,
not a surface. The prover's suite can show the laws hold; only these tests can show that One Link
*loads* the table, *verifies* it, and *stamps it onto the rows the UI receives* — and that it fails
closed when the artifact is wrong instead of quietly drawing unproven rows while the code still
claims a proven one.

The security-critical assertion is `test_the_verified_glyph_NEVER_appears_below_verified_trust`,
swept over the entire shipped state space rather than sampled. It is the product-side statement of
the property the whole thing exists for: a peer cannot make your screen say VERIFIED.
"""

from __future__ import annotations

import copy
import json
from pathlib import Path

import pytest

from one_link import certified_surface
from one_link.certified_surface import (
    GLYPH_VERIFIED,
    CertifiedSurface,
    load,
    table_digest,
    verify,
)

ARTIFACT = Path(certified_surface.DEFAULT_ARTIFACT)

VERIFIED, KNOWN, UNKNOWN = 2, 1, 0


@pytest.fixture(scope="module")
def doc() -> dict:
    assert ARTIFACT.exists(), (
        f"the certified artifact is missing at {ARTIFACT}. It is generated by "
        "idem/scripts/emit_certified_views.py and committed -- the product ships the answers, "
        "not the prover")
    return json.loads(ARTIFACT.read_text(encoding="utf-8"))


@pytest.fixture(scope="module")
def surface(doc: dict) -> CertifiedSurface:
    ok, why = verify(doc)
    assert ok, why
    return CertifiedSurface(doc)


# ── the artifact is real ──────────────────────────────────────────────


def test_the_shipped_artifact_verifies(doc):
    ok, why = verify(doc)
    assert ok, why
    assert "exhaustive" in why


def test_it_carries_the_five_laws_at_scope_exact(surface):
    names = {n for n, _s in surface.laws}
    assert names == {
        "the-verified-glyph-requires-verified-trust",
        "the-name-never-runs-under-the-badge",
        "nothing-is-drawn-outside-the-row",
        # §10.3 of the design, made a theorem: the a11y tree is not a parallel structure.
        "every-row-says-something",
        "the-spoken-label-cannot-contradict-the-pixel",
    }, f"the shipped laws changed: {sorted(names)}"
    assert all(scope == "exact" for _n, scope in surface.laws), (
        f"a law discharged at a weaker scope than `exact`: {surface.laws}")


def test_the_module_loads_it_from_the_default_path():
    assert load() is not None
    assert certified_surface.available() is True


# ── the security property, over the WHOLE shipped space ───────────────


def test_the_verified_glyph_NEVER_appears_below_verified_trust(surface, doc):
    """THE property, swept rather than sampled.

    The prover discharged this over every integer. This is the product-side statement:
    every row One Link can actually be asked to draw is checked, so a regression in the
    artifact — a hand-edit, a bad regeneration, a truncated file — is caught here even
    though the theorem upstream is untouched.
    """
    checked = 0
    for row in doc["rows"]:
        trust, name_len = row["in"]["trust"], row["in"]["name_len"]
        got = surface.row(trust, name_len)
        assert got is not None
        if trust != VERIFIED:
            assert got.glyph != GLYPH_VERIFIED, (
                f"trust={trust} name_len={name_len} draws the VERIFIED glyph -- a peer that is "
                "not verified would appear verified on screen")
            assert not got.shows_verified()
        checked += 1
    assert checked == len(doc["rows"]) >= 100, f"only {checked} rows swept"


def test_a_verified_peer_DOES_get_the_glyph(surface):
    """NEGATIVE CONTROL. Every assertion above is satisfied by a renderer that never shows
    the badge at all -- which would be secure, useless, and indistinguishable without this."""
    got = surface.row(VERIFIED, 12)
    assert got is not None and got.shows_verified()


def test_the_name_never_runs_under_the_badge(surface, doc):
    for row in doc["rows"]:
        got = surface.row(row["in"]["trust"], row["in"]["name_len"])
        assert got.name_w <= got.badge_x, (
            f"{row['in']} draws a name {got.name_w}px wide under a badge at {got.badge_x}px")


def test_nothing_is_drawn_at_negative_width(surface, doc):
    """The defect the prover caught before it shipped.

    The first renderer clamped only the HIGH side of the name width. A negative name_len --
    or one large enough that `name_len * 8` wraps in i64 -- produced a NEGATIVE width. No
    test written against plausible names would have found it.
    """
    for row in doc["rows"]:
        got = surface.row(row["in"]["trust"], row["in"]["name_len"])
        assert got.name_w >= 0, f"{row['in']} -> negative width {got.name_w}"


# ── it fails CLOSED ───────────────────────────────────────────────────


def test_an_EDITED_table_is_refused(doc):
    """The forgery: flip a row so an unverified peer shows the verified glyph, keep the digest."""
    forged = copy.deepcopy(doc)
    for row in forged["rows"]:
        if row["in"]["trust"] != VERIFIED:
            row["out"]["glyph"] = GLYPH_VERIFIED
            break
    ok, why = verify(forged)
    assert ok is False, "a table edited after certification was accepted"
    assert "DIGEST MISMATCH" in why


def test_a_TRUNCATED_table_is_refused(doc):
    """A missing point is a broken surface, not a smaller one -- and the digest alone
    cannot catch it, because a truncated table hashes consistently with itself."""
    short = copy.deepcopy(doc)
    short["rows"] = short["rows"][:-1]
    short["table_digest"] = table_digest(short["rows"])      # re-hashed, so only coverage catches it
    ok, why = verify(short)
    assert ok is False
    assert "incomplete table" in why


def test_a_table_with_NO_LAWS_is_refused(doc):
    lawless = copy.deepcopy(doc)
    lawless["laws"] = []
    ok, why = verify(lawless)
    assert ok is False
    assert "lookup table with a hash" in why


def test_a_missing_artifact_yields_None_not_an_exception(tmp_path):
    """The UI must degrade to ordinary rendering, never crash the peers API."""
    assert load(tmp_path / "absent.json") is None


def test_a_CORRUPT_artifact_yields_None(tmp_path):
    bad = tmp_path / "bad.json"
    bad.write_text("{not json", encoding="utf-8")
    assert load(bad) is None


def test_a_point_outside_the_certified_space_returns_None(surface):
    """Honest emptiness. Extrapolating past the proven domain would be the unproven code
    this replaces, wearing a digest."""
    assert surface.row(VERIFIED, 9999) is None
    assert surface.covers(VERIFIED, 9999) is False
    assert surface.covers(VERIFIED, 0) is True


# ── the product actually reaches it ───────────────────────────────────


def test_the_peers_API_stamps_the_proven_row():
    """THE integration claim. Source-level, because standing up the full peers handler needs
    discovery, state and a daemon -- but the wiring is what regresses, so it is asserted."""
    src = (Path(__file__).resolve().parents[1] / "src" / "one_link" / "server.py").read_text(
        encoding="utf-8")
    assert "certified_surface.surface()" in src, "the peers API no longer loads the surface"
    assert 'p["certified_row"] = self._certified_row_for(' in src, (
        "peer rows are no longer stamped with the proven layout -- the artifact ships but "
        "nothing renders from it, which is the exact failure this work exists to end")
    assert "def _certified_row_for" in src


def test_the_trust_mapping_requires_IN_PERSON_verification():
    """The one judgement call the proof cannot make.

    The law constrains the renderer: glyph 7 only when the level is VERIFIED. WHICH peers
    count as VERIFIED is the product's decision, and it must be `is_verified` (an in-person
    SAS confirmation) rather than `trust == "pinned"`. Pairing means a key exchange
    happened; it does not mean anyone checked who was on the other end.
    """
    src = (Path(__file__).resolve().parents[1] / "src" / "one_link" / "server.py").read_text(
        encoding="utf-8")
    i = src.index("def _certified_row_for")
    body = src[i:i + 1600]
    assert 'p.get("is_verified")' in body and "level = 2" in body, (
        "the VERIFIED level is no longer gated on in-person verification")
    pinned_at = body.index('"pinned"')
    assert "level = 1" in body[pinned_at:pinned_at + 80], (
        "a merely-pinned peer is being mapped to VERIFIED -- pairing is not verification")


# ── it reaches the SHIPPED bundle, not just the checkout ──────────────


def test_the_build_carries_the_artifact_into_the_bundle():
    """The dev-only trap: everything passes in the checkout and the bundle has no table.

    `certified_surface` resolves its artifact beside the package, so if PyInstaller does not
    carry `one_link/certified` the installed app silently loses the proven surface — and
    `available()` returning False looks identical to "not built yet".
    """
    # The artifact lives under `data/`, which the bundle already carries wholesale via
    # `add_data_package`. That is not an accident of convenience: `validate_python_distributions.py`
    # scans exactly `data` and `web` for package data, so a new top-level `certified/` directory
    # was INVISIBLE to the supply-chain contract and produced a wheel that looked valid while
    # omitting the table. Living inside an already-audited subtree is the property under test.
    build = (Path(__file__).resolve().parents[1] / "scripts" / "build_binary.py").read_text(
        encoding="utf-8")
    assert 'package_data_dir = repo / "src" / "one_link" / "data"' in build
    assert "+ add_data_package" in build, (
        "the bundle no longer carries the data subtree, which is where the certified surface "
        "lives -- the installed app would render every row through the unproven fallback")

    from one_link import certified_surface as cs
    assert cs.DEFAULT_ARTIFACT.parts[-3:] == ("data", "certified", "peer_row.json"), (
        f"the artifact moved to {cs.DEFAULT_ARTIFACT} -- outside `data/` it is invisible to both "
        "the wheel's package-data contract and the distribution validator's source scan")
    pyproject = (Path(__file__).resolve().parents[1] / "pyproject.toml").read_text(encoding="utf-8")
    assert '"data/certified/peer_row.json"' in pyproject, (
        "the wheel no longer declares the artifact; a pip install would omit it silently")


def test_the_build_REFUSES_when_the_artifact_is_missing():
    """A skipped-if-absent asset is a dark gate.

    If the build merely omitted a missing artifact, the bundle would run, every row would fall
    back to unproven layout, and the code would still claim a proven surface. That failure is
    invisible from the outside, so the build has to stop.
    """
    build = (Path(__file__).resolve().parents[1] / "scripts" / "build_binary.py").read_text(
        encoding="utf-8")
    i = build.index("certified_dir = repo")
    window = build[i:i + 1200]
    assert "return 6" in window, "a missing certified surface no longer fails the build"
    assert "is_file()" in window


# ── against a LIVE server, because a source grep is not a running product ──

import pytest_asyncio  # noqa: E402
from aiohttp.test_utils import TestClient, TestServer  # noqa: E402
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey  # noqa: E402

from one_link.daemon import Daemon  # noqa: E402
from one_link.identity import Identity, fingerprint_of  # noqa: E402
from one_link.server import UIServer  # noqa: E402
from one_link.state import State  # noqa: E402


def _identity(host: str = "cert-host") -> Identity:
    sk = Ed25519PrivateKey.generate()
    pub = sk.public_key()
    pb = pub.public_bytes_raw()
    fp = fingerprint_of(pb)
    return Identity(private=sk, public=pub, public_bytes=pb, fingerprint=fp,
                    short_id=fp[:8], hostname=host)


@pytest_asyncio.fixture
async def live(tmp_path, monkeypatch):
    """A real UIServer with one PINNED peer and one VERIFIED peer in state."""
    monkeypatch.setenv("ONE_LINK_HOME", str(tmp_path))
    state = State(db_path=tmp_path / "state.db")

    pinned_fp, verified_fp = "aa" * 32, "bb" * 32
    for fp, host in ((pinned_fp, "pinned-peer"), (verified_fp, "verified-peer")):
        state.upsert_peer(fingerprint=fp, short_id=fp[:8], pubkey=b"\x01" * 32, hostname=host)
        state.set_peer_trust(fp, "pinned")
    # Only the second one has been verified in person.
    state.set_peer_verified(verified_fp, method="sas-digits", note="test fixture")

    daemon = Daemon(_identity())
    daemon.state = state
    daemon.discovery = None
    daemon._outbound_sessions = {}
    daemon._inbound_regime = {}
    daemon.folder_engine = None

    server = UIServer(daemon)
    client = TestClient(TestServer(server.app))
    await client.start_server()
    try:
        yield client, server, {"pinned": pinned_fp, "verified": verified_fp}
    finally:
        await client.close()
        state.close()


@pytest.mark.asyncio
async def test_the_peers_API_really_returns_a_certified_row(live):
    """THE integration claim, executed rather than grepped.

    If the surface failed to load inside the running server -- a packaging path, a cached
    None, an import ordering problem -- every source assertion above would still pass and
    the product would render nothing proven.
    """
    client, server, _fps = live
    resp = await client.get("/api/peers", headers={"Authorization": f"Bearer {server.token}"})
    assert resp.status == 200, await resp.text()
    peers = (await resp.json()).get("peers") or []
    assert peers, "no peers returned; the assertions below would be vacuous"

    stamped = [p for p in peers if p.get("certified_row")]
    assert stamped, (
        "not one peer carried `certified_row` -- the artifact ships but the running server "
        "does not render from it, which is precisely the gap this work exists to close")
    for p in stamped:
        row = p["certified_row"]
        assert {"glyph", "name_w", "badge_x", "digest"} <= set(row)
        assert row["name_w"] <= row["badge_x"]
        assert row["name_w"] >= 0


@pytest.mark.asyncio
async def test_a_PINNED_but_unverified_peer_does_NOT_get_the_verified_glyph(live):
    """The security property, end to end through the real API.

    Both peers are `trust == "pinned"`. Only one has an in-person SAS verification. If the
    mapping ever collapses those two states, a peer you merely paired with would render as
    verified -- and pairing is a key exchange, not a statement about who is on the far end.
    """
    client, server, _fps = live
    resp = await client.get("/api/peers", headers={"Authorization": f"Bearer {server.token}"})
    peers = (await resp.json()).get("peers") or []
    by_host = {p.get("hostname"): p for p in peers}

    pinned = by_host.get("pinned-peer")
    verified = by_host.get("verified-peer")
    assert pinned and verified, f"fixture peers missing from the API: {sorted(by_host)}"

    assert pinned["trust"] == "pinned" and verified["trust"] == "pinned", (
        "both fixture peers must be pinned, or this test is not isolating VERIFICATION")

    assert pinned["certified_row"]["glyph"] != GLYPH_VERIFIED, (
        "a paired-but-unverified peer renders the VERIFIED glyph")
    assert verified["certified_row"]["glyph"] == GLYPH_VERIFIED, (
        "an in-person-verified peer does NOT render the verified glyph -- the badge would "
        "never appear and the control above would be vacuous")


# ── the UI draws from it, not merely receives it ──────────────────────


def _ui() -> str:
    return (Path(__file__).resolve().parents[1] / "src" / "one_link" / "web" /
            "index.html").read_text(encoding="utf-8")


def test_the_badge_is_decided_by_the_PROVEN_table():
    """The last mile. The server can stamp a proven row and the UI can ignore it.

    `renderConvHeaderTrust` is the function that puts the verified pill on screen. It must
    take its answer from `certified_row.glyph`, not from an ad-hoc `is_verified` conditional
    -- the pixels are the same either way, which is exactly why nothing but a test would
    notice the authority quietly moving back.
    """
    html = _ui()
    assert "function verifiedByProof(peer)" in html, (
        "the UI no longer consults the proven table for the verified badge")
    assert "row.glyph === GLYPH_VERIFIED" in html
    i = html.index("function renderConvHeaderTrust(peer)")
    body = html[i:i + 1400]
    assert "verifiedByProof(peer)" in body, (
        "renderConvHeaderTrust decides the badge without asking the proven renderer")


def test_the_UNPROVEN_fallback_is_never_silent():
    """A fallback nobody can see is how the unproven path comes back.

    When no certified row is present the UI must still render -- but it has to RECORD that
    it fell back, or 'proven' becomes a claim with no way to check it after the fact.
    """
    html = _ui()
    i = html.index("function renderConvHeaderTrust(peer)")
    body = html[i:i + 1400]
    assert 'data-proven' in body, "the fallback does not mark itself"
    assert '"unavailable"' in body


def test_the_verified_glyph_constant_matches_the_server():
    """A constant that drifts between the two sides is a badge that lies on one of them."""
    html = _ui()
    assert "const GLYPH_VERIFIED = 7;" in html
    assert GLYPH_VERIFIED == 7


# ── identity: the digest proves nobody EDITED it; the signature proves nobody MADE it ──
#
# Everything above is self-referential. An adversary who edits an answer AND recomputes the digest
# produces a perfectly self-consistent artifact, because a hash is not an identity. These are the
# tests that distinguish the two properties.

import hashlib as _hashlib  # noqa: E402

from one_link.certified_surface import (  # noqa: E402
    TRUSTED_VIEW_SIGNERS,
    _signable,
    signature_ok,
)


def _resign(doc: dict, sk: Ed25519PrivateKey) -> dict:
    """Sign a (possibly forged) artifact with an arbitrary key, as an attacker would."""
    body = {k: v for k, v in doc.items() if k not in ("signature", "signer")}
    pub = sk.public_key().public_bytes_raw().hex()
    signed = {**body, "signer": pub}
    return {**signed, "signature": sk.sign(_signable(signed)).hex()}


def test_the_shipped_artifact_is_SIGNED_by_a_pinned_key(doc):
    ok, why = signature_ok(doc)
    assert ok, why
    assert doc["signer"] in TRUSTED_VIEW_SIGNERS


def test_an_UNSIGNED_artifact_is_refused(doc):
    """The property the digest cannot give: a table nobody stands behind."""
    bare = {k: v for k, v in doc.items() if k not in ("signature", "signer")}
    ok, why = verify(bare)
    assert ok is False
    assert "UNSIGNED" in why


def test_a_FORGERY_with_a_recomputed_digest_is_refused(doc):
    """THE case signing exists for, and the one the digest alone waves through.

    The attacker flips an unverified peer to the verified glyph, then recomputes the table
    digest so the artifact is internally perfect. Every structural check passes. Only the
    signature refuses it.
    """
    forged = copy.deepcopy(doc)
    for row in forged["rows"]:
        if row["in"]["trust"] != VERIFIED:
            row["out"]["glyph"] = GLYPH_VERIFIED
            break
    forged["table_digest"] = table_digest(forged["rows"])       # internally consistent now

    assert table_digest(forged["rows"]) == forged["table_digest"], (
        "the forgery is not self-consistent, so this test would pass for the wrong reason")

    ok, why = verify(forged)
    assert ok is False, "a forged table with a recomputed digest was accepted"
    assert "SIGNATURE INVALID" in why, why


def test_a_forgery_RESIGNED_with_the_attackers_own_key_is_refused(doc):
    """The obvious escalation: if they can recompute a digest, they can sign it too.

    This is why the signer is PINNED. An artifact verified against whatever key it names is
    verified against its author, which is no verification at all.
    """
    forged = copy.deepcopy(doc)
    forged["rows"][0]["out"]["glyph"] = GLYPH_VERIFIED
    forged["table_digest"] = table_digest(forged["rows"])
    attacker = _resign(forged, Ed25519PrivateKey.generate())

    ok, why = signature_ok(attacker)
    assert ok is False, "an artifact signed by an arbitrary key was accepted"
    assert "not a pinned signer" in why

    ok2, _ = verify(attacker)
    assert ok2 is False


def test_the_signature_covers_EVERY_field_including_ones_added_later(doc):
    """Coverage by exclusion, not by a hand-maintained list.

    A signature scoped to an enumerated set of keys silently stops covering the newest field
    anyone adds. Mutating a field the signer never explicitly listed must still break it.
    """
    tampered = copy.deepcopy(doc)
    tampered["laws"] = [["a-law-nobody-proved", "exact"]]
    ok, _ = signature_ok(tampered)
    assert ok is False, "the `laws` field is outside the signature's coverage"

    tampered2 = copy.deepcopy(doc)
    tampered2["class_fingerprint"] = "0" * 64
    assert signature_ok(tampered2)[0] is False, "the fingerprint is outside the coverage"


def test_the_signable_bytes_match_the_producers_rule(doc):
    """A domain-separator divergence does not fail loudly -- it rejects every honest artifact.

    Pinned explicitly so a change on either side is a test failure rather than a silent
    outage where the surface simply stops loading everywhere.
    """
    body = {k: v for k, v in doc.items() if k not in ("signature", "signer")}
    expected = b"idem-view-sig/v1\x00" + json.dumps(
        body, sort_keys=True, separators=(",", ":"), ensure_ascii=True).encode("ascii")
    assert _signable(doc) == expected
    assert _hashlib.sha256(_signable(doc)).digest()          # it is bytes, and non-empty


# ── the development key must not ride into a release ──────────────────


def test_no_PUBLISHED_key_is_trusted():
    """The gate that retired the development key, generalised so it cannot come back.

    Until 2026-08-07 the tables were signed with a key derived from the published phrase
    `one-link/certified-view/DEVELOPMENT-KEY/not-for-release/v1` — anyone could forge a table
    this build accepts. That was deliberate and temporary: it made the whole path (sign, pin,
    verify, fail closed) real and testable before a real key existed, and this test failed any
    non-alpha build while it was pinned.

    The real key now lives in the estate's DPAPI vault. This test outlives the specific key it
    was written for: NO derivable key may be trusted, whatever it is called.
    """
    import hashlib

    from one_link.certified_surface import TRUSTED_VIEW_SIGNERS

    assert TRUSTED_VIEW_SIGNERS, "no pinned signer at all: every artifact would be refused"

    # Any signer that is the release-role pubkey of a seed derived from a phrase in our own
    # source is, by construction, forgeable by anyone who can read the repository.
    #
    # THE DERIVATION IS INLINE, NOT IMPORTED FROM idem. The first version did
    # `sys.path.insert(0, .../idem)` -- and idem has its own top-level `scripts/` package, which
    # then SHADOWED One Link's, so an unrelated test's `import scripts.build_binary` failed with
    # ModuleNotFoundError several files later. A test that mutates sys.path to reach a sibling
    # checkout is a test that can break any other test in the run.
    from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey

    def role_pubkey(seed: bytes, role: str) -> str:
        derived = hashlib.sha256(f"idem/role/{role}/v1".encode("ascii") + seed).digest()
        return Ed25519PrivateKey.from_private_bytes(derived).public_key().public_bytes_raw().hex()

    for phrase in (
        b"one-link/certified-view/DEVELOPMENT-KEY/not-for-release/v1",
        b"one-link/certified-view/v1",
        b"development",
        b"test",
    ):
        forgeable = role_pubkey(hashlib.sha256(phrase).digest(), "release")
        assert forgeable not in TRUSTED_VIEW_SIGNERS, (
            f"a key derived from the published phrase {phrase!r} is trusted — anyone who can read "
            "this repository can sign a certified surface this build will render")


def test_the_release_signer_is_pinned_and_documented():
    """A pinned key with no recorded custody is a key nobody can rotate."""
    from one_link.certified_surface import RELEASE_SIGNER, TRUSTED_VIEW_SIGNERS

    assert RELEASE_SIGNER in TRUSTED_VIEW_SIGNERS
    assert len(RELEASE_SIGNER) == 64 and all(c in "0123456789abcdef" for c in RELEASE_SIGNER)

    src = (Path(__file__).resolve().parents[1] / "src" / "one_link" /
           "certified_surface.py").read_text(encoding="utf-8")
    i = src.index("RELEASE_SIGNER =")
    window = src[max(0, i - 1800):i]
    assert "vault" in window and "To rotate" in window, (
        "where the private half lives and how to rotate it is no longer recorded beside the key")



# ── the screen reader and the pixel cannot disagree ───────────────────
#
# Every mainstream stack maintains the semantic tree ALONGSIDE the visual one and the mapping rots
# silently: a badge is restyled, the aria-label stays, and a blind user is told something the screen
# stopped saying two quarters ago. Nothing detects it, because no component holds both at once.
#
# Here the label is an output of the SAME renderer as the pixel, and the agreement is DISCHARGED
# over every integer input rather than left to construction.


def test_the_spoken_label_and_the_pixel_agree_on_EVERY_shipped_row(surface, doc):
    """The product-side sweep of `the-spoken-label-cannot-contradict-the-pixel`."""
    from one_link.certified_surface import LABEL_VERIFIED

    checked = 0
    for row in doc["rows"]:
        got = surface.row(row["in"]["trust"], row["in"]["name_len"])
        assert got.shows_verified() == got.says_verified(), (
            f"{row['in']}: the badge shows verified={got.shows_verified()} while the screen "
            f"reader says verified={got.says_verified()} -- a blind user and a sighted user are "
            "being told different things about the same peer")
        if row["in"]["trust"] == VERIFIED:
            assert got.label == LABEL_VERIFIED
        checked += 1
    assert checked == len(doc["rows"])


def test_every_shipped_row_says_SOMETHING(surface, doc):
    """A row that announces nothing is invisible to a screen reader while visible on screen."""
    for row in doc["rows"]:
        got = surface.row(row["in"]["trust"], row["in"]["name_len"])
        assert got.spoken().strip(), f"{row['in']} announces nothing"


def test_an_UNKNOWN_label_id_falls_back_to_the_most_conservative_text():
    """Fail safe, not silent. An id the product does not recognise must under-claim rather
    than announce nothing -- and must never announce verification it cannot support."""
    from one_link.certified_surface import LABEL_TEXT, LABEL_NONE, CertifiedRow

    weird = CertifiedRow(glyph=0, name_w=10, badge_x=296, label=99)
    assert weird.spoken() == LABEL_TEXT[LABEL_NONE]
    assert "erified in person" not in weird.spoken()


def test_the_peers_API_carries_the_spoken_label():
    src = (Path(__file__).resolve().parents[1] / "src" / "one_link" / "server.py").read_text(
        encoding="utf-8")
    assert '"spoken": row.spoken(),' in src and '"label": row.label,' in src, (
        "the API no longer sends the proven accessible label, so the UI has nothing to speak")


def test_the_UI_sets_aria_label_from_the_PROOF():
    html = _ui()
    assert "function spokenByProof(peer)" in html
    i = html.index("function renderConvHeaderTrust(peer)")
    body = html[i:i + 2000]
    assert "spokenByProof(peer)" in body and 'setAttribute("aria-label"' in body, (
        "the verified pill's aria-label is no longer taken from the proven renderer -- it is "
        "back to being a string maintained beside the badge, which is the drift this replaces")


# ═══ THE SECOND SURFACE: the connection badge ════════════════════════════════════════════
#
# The peer row answers "is this device who I think". This answers "is this conversation direct,
# and authenticated" -- a different claim with a different failure mode, and the one a product
# overstates quietly, because "direct" and "secure" describe infrastructure the user cannot see.
#
# Two surfaces is the point. One proven renderer is a demo; a registry that emits many through the
# same pipeline (prove -> materialize -> sign -> verify) is a mechanism.

from one_link.certified_surface import (  # noqa: E402
    ICON_DIRECT,
    ICON_OFFLINE,
    ICON_RELAYED,
    LBL_UNAUTH,
    VIEW_NAMES,
    CertifiedBadge,
    link_surface,
    view,
)

R_OFFLINE, R_LAN, R_INTERNET, R_RELAY, R_UNKNOWN = 0, 1, 2, 3, 4


@pytest.fixture(scope="module")
def link():
    s = link_surface()
    assert s is not None, "the link_badge view did not load or did not verify"
    return s


def test_both_certified_views_load_and_verify():
    for name in VIEW_NAMES:
        assert view(name) is not None, f"certified view {name!r} failed to load or verify"


def test_an_unknown_view_name_RAISES_rather_than_returning_None():
    """None means 'unavailable, render normally'. A typo'd name taking that path would
    disable a proven surface with no trace."""
    with pytest.raises(KeyError):
        view("no_such_view")


def test_the_link_badge_carries_its_five_laws(link):
    names = {n for n, _s in link.laws}
    assert names == {
        "never-claims-DIRECT-for-a-link-that-is-not",
        "never-claims-SECURE-for-an-unauthenticated-link",
        "offline-never-renders-as-connected",
        "an-unauthenticated-live-link-always-warns",
        "the-link-label-cannot-contradict-the-icon",
    }, f"the shipped link laws changed: {sorted(names)}"
    assert all(scope == "exact" for _n, scope in link.laws)


# ── the claims that cost something if they are wrong ──────────────────


def test_it_NEVER_claims_direct_for_a_relayed_or_unknown_link(link):
    """THE law. A relayed conversation announced as direct is a lie about who can see it."""
    for regime in (R_RELAY, R_UNKNOWN):
        for authed in (0, 1):
            badge = link.link_badge(regime, authed)
            assert badge is not None
            assert not badge.claims_direct(), (
                f"regime={regime} authed={authed} renders as DIRECT")
            assert badge.icon == ICON_RELAYED


def test_a_regime_this_build_does_not_recognise_renders_as_RELAYED(link):
    """The conservative default, and the reason the renderer had to become total.

    `if relayed { RELAYED } else { DIRECT }` is the natural way to write this, and the law
    refutes it instantly: an unrecognised regime is not relayed, so the badge would claim
    DIRECT for a transport that did not exist when the code was written.
    """
    badge = link.link_badge(R_UNKNOWN, 1)
    assert badge.icon == ICON_RELAYED and not badge.claims_direct()


def test_it_NEVER_claims_authenticated_without_authentication(link):
    for regime in (R_LAN, R_INTERNET, R_RELAY, R_UNKNOWN):
        badge = link.link_badge(regime, 0)
        assert not badge.claims_authenticated(), f"regime={regime} claims authenticated"
        assert badge.label == LBL_UNAUTH
        assert badge.warn == 1, "an unauthenticated live link does not warn"


def test_offline_never_renders_as_connected(link):
    for authed in (0, 1):
        badge = link.link_badge(R_OFFLINE, authed)
        assert badge.icon == ICON_OFFLINE
        assert not badge.claims_direct()


def test_a_genuinely_direct_authenticated_link_DOES_say_so(link):
    """NEGATIVE CONTROL. Every assertion above is satisfied by a badge that always says
    'relayed, unauthenticated' -- which would be safe, useless, and indistinguishable."""
    for regime in (R_LAN, R_INTERNET):
        badge = link.link_badge(regime, 1)
        assert badge.claims_direct() and badge.claims_authenticated()
        assert badge.warn == 0
        assert badge.icon == ICON_DIRECT


def test_the_spoken_link_label_never_over_claims(link, ):
    """An unrecognised label id must fall back to 'Not authenticated', never to a claim."""
    weird = CertifiedBadge(icon=ICON_DIRECT, label=99, warn=0)
    assert weird.spoken() == "Not authenticated"
    for regime in (R_OFFLINE, R_LAN, R_INTERNET, R_RELAY, R_UNKNOWN):
        for authed in (0, 1):
            badge = link.link_badge(regime, authed)
            spoken = badge.spoken()
            if not badge.claims_authenticated():
                assert "authenticated" not in spoken or spoken == "Not authenticated", spoken


# ── the mapping into the certified space is conservative ──────────────


def test_an_unrecognised_regime_NAME_maps_to_the_unknown_axis_not_to_internet():
    """The mapping must not undo the renderer's caution.

    `_REGIME_AXIS.get(name, 2)` defaulting to `internet` is the natural line to write, and it
    would make every unknown transport claim a DIRECT connection -- reintroducing, in one
    dictionary lookup, exactly the thing the law forbids.
    """
    src = (Path(__file__).resolve().parents[1] / "src" / "one_link" / "server.py").read_text(
        encoding="utf-8")
    i = src.index("_REGIME_AXIS")
    window = src[i:i + 2200]        # the mapping and its use are separated by the rationale
    assert "_REGIME_AXIS.get(regime_name, 4)" in window, (
        "an unrecognised regime name no longer maps to the UNKNOWN axis")
    assert '"relay": 3' in window and '"lan": 1' in window


def test_the_peers_API_stamps_the_connection_badge_AFTER_the_regime_is_known():
    """Ordering is load-bearing here, and the bug it prevents never looks like one.

    `regime` is assigned inside the per-peer loop. Stamping the badge earlier would read it
    before assignment, badge every peer 'offline' -- the CONSERVATIVE value -- and therefore
    look entirely reasonable on screen while being wrong for every connected peer.
    """
    src = (Path(__file__).resolve().parents[1] / "src" / "one_link" / "server.py").read_text(
        encoding="utf-8")
    stamp = src.index('p["certified_link"] = self._certified_link_for(')
    offline_assign = src.index('p["regime"] = "offline"')
    assert offline_assign < stamp, (
        "the connection badge is stamped before the regime is resolved")


@pytest.mark.asyncio
async def test_the_peers_API_really_returns_a_certified_LINK_badge(live):
    """Executed, not grepped. Both proven surfaces must reach a running server."""
    client, server, _fps = live
    resp = await client.get("/api/peers", headers={"Authorization": f"Bearer {server.token}"})
    assert resp.status == 200
    peers = (await resp.json()).get("peers") or []
    assert peers

    badged = [p for p in peers if p.get("certified_link")]
    assert badged, (
        "no peer carried `certified_link` -- the link_badge artifact ships but the running "
        "server does not render from it")
    for p in badged:
        b = p["certified_link"]
        assert {"icon", "label", "warn", "spoken", "claims_direct", "digest"} <= set(b)
        # These fixture peers are offline (no session), so the conservative badge is required.
        if p.get("regime") == "offline":
            assert b["icon"] == ICON_OFFLINE and not b["claims_direct"]


@pytest.mark.asyncio
async def test_an_offline_peer_is_never_badged_as_a_direct_connection(live):
    """The end-to-end statement of `offline-never-renders-as-connected`."""
    client, server, _fps = live
    resp = await client.get("/api/peers", headers={"Authorization": f"Bearer {server.token}"})
    for p in (await resp.json()).get("peers") or []:
        if p.get("regime") == "offline" and p.get("certified_link"):
            assert not p["certified_link"]["claims_direct"], (
                f"{p.get('hostname')} is offline and is badged as a direct connection")


def test_the_connection_LABEL_is_drawn_from_the_proof():
    """The last mile for the second surface.

    The server can stamp a proven badge and the UI can keep printing its own string table.
    The route label must come from `certified_link.spoken` -- and the old table's final
    line was `return r;`, printing an unrecognised regime straight through as a raw
    protocol token: meaningless to a user, and an unbounded claim.
    """
    html = _ui()
    i = html.index("const regimeLabel = (() => {")
    body = html[max(0, i - 2000):i + 900]
    assert "peer.certified_link" in body, "the route label ignores the proven badge"
    assert "if (proven) return certified.spoken;" in body, (
        "the proven label is not consulted FIRST -- the string table would win")
    # Assert about CODE, not prose. The comment above the block quotes the old `return r;`
    # deliberately, and the first version of this test matched that quotation -- a test that
    # reads documentation and calls it implementation.
    code = " ".join(ln for ln in body.splitlines() if not ln.strip().startswith("//"))
    assert "return r;" not in code, (
        "an unrecognised regime is still printed raw to the user; the proven path has no "
        "such branch, and the fallback should not either")


def test_the_unproven_connection_fallback_marks_itself():
    html = _ui()
    i = html.index("const regimeLabel = (() => {")
    body = html[i:i + 1200]
    assert 'data-proven' in body and '"unavailable"' in body, (
        "the fallback does not record that it ran -- a fallback nobody can see is how the "
        "unproven path returns")


def test_an_unauthenticated_link_shows_a_WARNING_in_the_UI():
    """`an-unauthenticated-live-link-always-warns` is proven; the UI must surface it."""
    html = _ui()
    i = html.index("const regimeLabel = (() => {")
    body = html[i:i + 1400]
    assert "certified.warn" in body, "the proven warn flag never reaches the screen"


# ═══ THE NATIVE SHELL — One Link's own window ════════════════════════════════════════════
#
# §10.4 of the design. The app-mode path was a real chromeless window, but it was Edge's: it needed
# Edge installed, showed Edge in the process list, and put the launch URL on a command line. These
# assert the properties that make the native shell worth having, not merely that it exists.

SHELL_DIR = Path(__file__).resolve().parents[1] / "native" / "ol_shell"


def _shell_src(name: str) -> str:
    return (SHELL_DIR / "src" / name).read_text(encoding="utf-8")


def test_the_third_certified_view_is_the_shells_navigation_FENCE():
    """The decision the shell enforces is a theorem, not seven hand-written cases.

    I wrote this fence in Rust as `uri.starts_with(origin)` and shipped a bypass within
    minutes: `http://127.0.0.1:7117@evil.example/` starts with the origin because the
    loopback address becomes userinfo. Sampling found it by luck; a proof cannot miss it.
    """
    from one_link.certified_surface import origin_fence

    s = origin_fence()
    assert s is not None, "the origin_fence view did not load or did not verify"
    names = {n for n, _ in s.laws}
    assert "only-a-real-boundary-may-extend-the-origin" in names
    assert "userinfo-can-never-extend-the-origin" in names
    assert all(scope == "exact" for _n, scope in s.laws)


def test_the_fence_refuses_every_bypass_character_and_admits_only_four():
    from one_link.certified_surface import fence_admits

    for bad, why in ((64, "@ — userinfo"), (46, ". — hostname"), (58, ": — port"),
                     (48, "digit"), (57, "digit"), (65, "letter")):
        assert fence_admits(bad) is False, f"the fence admits {why}"
    for good in (-1, 47, 63, 35):          # end, '/', '?', '#'
        assert fence_admits(good) is True, f"the fence refuses a real boundary: {good}"


def test_the_shell_and_python_pin_the_SAME_signers():
    """A divergence here does not fail loudly — it refuses every honest artifact.

    The shell would open, verify nothing it recognises, and refuse to draw; the Python side
    would happily load the same files. Two verifiers disagreeing about WHO is trusted is the
    worst shape of failure: silent on one side, total on the other.
    """
    from one_link.certified_surface import TRUSTED_VIEW_SIGNERS

    rust = _shell_src("main.rs")
    for signer in TRUSTED_VIEW_SIGNERS:
        assert signer in rust, (
            f"signer {signer[:16]} is pinned in Python but not in native/ol_shell — the shell "
            "will refuse every artifact the daemon accepts")


def test_the_shell_takes_the_URL_on_STDIN_and_never_on_a_command_line():
    """The launch credential must not reach argv. This is the same finding that produced the
    single-use nonce: a command line is readable by any same-user process, no elevation."""
    rust = _shell_src("main.rs")
    assert "read_line" in rust and "stdin" in rust
    # Assert about CODE. The doc comment explains argv precisely BY NAMING IT, and the first
    # version of this test matched that explanation -- a test reading documentation and calling
    # it implementation. Second time today; the lesson is that a source-grep test must always
    # strip comments first.
    rust_code = " ".join(
        ln for ln in rust.splitlines() if not ln.strip().startswith("//"))
    assert "std::env::args" not in rust_code, (
        "the shell reads its arguments from argv, which is where the launch credential must "
        "never appear")

    app = (Path(__file__).resolve().parents[1] / "src" / "one_link" / "app.py").read_text(
        encoding="utf-8")
    i = app.index("def _open_native_shell(")
    # To the END of the function, not a fixed character count. A byte window silently shrinks its
    # own coverage as the function grows -- it would stop reaching the Popen call it exists to
    # check and still pass, which is the quietest way for a test to stop testing anything.
    rest = app[i + 1:]
    j = rest.index("\ndef ")
    body = app[i: i + 1 + j]
    # Same comment-stripping rule as the Rust half above: the docstring here NAMES argv and stdin
    # to explain the threat, and a grep that reads documentation as implementation passes on prose.
    body_code = " ".join(
        ln for ln in body.splitlines() if not ln.strip().startswith("#"))
    py_code = body_code.split('"""')[-1] if '"""' in body_code else body_code
    assert "stdin.write" in py_code, "the launcher no longer passes the URL over stdin"
    assert "{url}" in py_code, "the launch URL is no longer what goes over stdin"
    # The spawn must carry the executable and NOTHING else: the moment a URL joins that list it
    # is readable by every process running as this user.
    assert "[str(exe)]" in body, "the launcher passes something beyond the executable path in argv"
    argv_list = body.split("Popen(", 1)[1].split("]", 1)[0]
    assert "url" not in argv_list, "the launch URL appears inside the Popen argument list"


def test_the_shell_PINS_the_interface_it_will_render():
    """The trust chain's root. An attacker who can edit index.html can edit whatever told the
    shell what to expect — unless the expectation is compiled into the binary."""
    build_rs = (SHELL_DIR / "build.rs").read_text(encoding="utf-8")
    assert "OL_UI_SHA256" in build_rs and "index.html" in build_rs
    assert "panic!" in build_rs, (
        "a build with no interface to pin no longer fails; a shell with no pin renders anything")

    rust = _shell_src("main.rs")
    assert 'env!("OL_UI_SHA256")' in rust
    assert "INTERFACE MODIFIED" in rust, "the shell no longer refuses a modified interface"


def test_the_shell_verifies_certified_surfaces_INDEPENDENTLY():
    """A second implementation, in another language, written against the spec.

    Re-checking the same bytes with the same code proves nothing. Two implementations that
    agree byte-for-byte is evidence.
    """
    cert = _shell_src("certified.rs")
    assert "idem-view-table/v1" in cert and "idem-view-sig/v1" in cert, (
        "the shell's domain separators no longer match the producer's")
    assert "non-ASCII" in cert, (
        "the shell no longer refuses non-ASCII artifacts — Python escapes them and serde_json "
        "does not, so the digests would diverge on the first device with a non-English name")


def test_the_launcher_prefers_our_own_window_and_falls_back_VISIBLY():
    app = (Path(__file__).resolve().parents[1] / "src" / "one_link" / "app.py").read_text(
        encoding="utf-8")
    assert "if standalone and _open_native_shell(url):" in app, (
        "the launcher no longer tries One Link's own window first")
    i = app.index("def _open_native_shell(")
    body = app[i:i + 3200]
    assert "_safe_echo" in body, (
        "a failed native launch is silent; the user would see the browser path with no idea why")
    assert "SHELL_READY" in body, (
        "the launcher no longer waits for a WINDOW -- 'the process started' and 'a window "
        "opened' are different facts, and only the second is worth falling back on")
    assert 'SHELL_READY = "OL_SHELL_READY"' in app, (
        "the ready marker no longer matches what the shell prints")


# ═══ THE UNREAD BADGE — where §11.1 model (b) reaches a pixel ════════════════════════════
#
# `inbox_transition` proves what an ARRIVAL may do to the counter, and deliberately ships no table:
# its space is 8x8 because the laws quantify over every Inbox, and a product outgrows that on the
# ninth message. This proves what the counter is ALLOWED TO SAY, which is genuinely bounded — a
# badge counts to 99 and then shows an overflow marker, forever.


@pytest.fixture(scope="module")
def unread():
    s = view("unread_badge")
    assert s is not None, "the unread_badge view did not load or did not verify"
    return s


def test_the_unread_badge_carries_its_five_laws(unread):
    names = {n for n, _ in unread.laws}
    assert names == {
        "a-count-of-zero-or-less-never-draws-a-badge",
        "the-badge-never-shows-a-negative-number",
        "the-badge-never-shows-more-than-it-can-fit",
        "the-overflow-marker-means-the-count-really-overflowed",
        "a-count-that-fits-is-shown-EXACTLY",
    }, f"the shipped unread laws changed: {sorted(names)}"
    assert all(scope == "exact" for _n, scope in unread.laws)


def test_a_zero_or_negative_count_never_draws_a_badge(unread):
    """The oldest bug in this feature, and it survives review because the COUNT is correct —
    it is the rendering decision that is wrong. A negative reaches the pill after a desync."""
    for count in (-2, -1, 0):
        out = unread.at(count=count)
        assert out is not None
        assert out["show"] == 0, f"count={count} draws a badge"
        assert out["shown"] >= 0, f"count={count} would render {out['shown']}"


def test_a_count_that_fits_is_shown_exactly(unread):
    """NEGATIVE CONTROL. Every other law is satisfied by a badge that never appears."""
    for count in (1, 2, 42, 98, 99):
        out = unread.at(count=count)
        assert out["show"] == 1 and out["shown"] == count and out["overflow"] == 0


def test_a_count_that_does_not_fit_becomes_the_overflow_marker(unread):
    """The pill is fixed width. A three-digit count would push the row's layout apart."""
    for count in (100, 101, 120):
        out = unread.at(count=count)
        assert out["overflow"] == 1 and out["shown"] == 99 and out["show"] == 1


def test_the_whole_shipped_space_obeys_every_law(unread):
    """Swept, not sampled — the product-side statement of what the prover discharged."""
    doc = json.loads((certified_surface.CERTIFIED_DIR / "unread_badge.json").read_text("utf-8"))
    for row in doc["rows"]:
        c, out = row["in"]["count"], row["out"]
        assert out["shown"] >= 0
        assert out["shown"] <= 99
        assert (c > 0) == (out["show"] == 1)
        assert (out["overflow"] == 1) <= (c > 99)


def test_the_peers_API_and_the_UI_both_use_the_proven_badge():
    src = (Path(__file__).resolve().parents[1] / "src" / "one_link" / "server.py").read_text(
        encoding="utf-8")
    assert 'p["certified_unread"]' in src, "the peers API no longer stamps the proven badge"

    html = _ui()
    assert "function unreadBadgeOf(" in html
    i = html.index("const ucount = state.unreadByPeer")
    body = html[i:i + 700]
    assert "unreadBadgeOf(p, ucount)" in body, (
        "the sidebar badge decides its own text again; the old `ucount > 99 ? \"99+\"` was "
        "correct and re-decided in JS on every render")
    assert 'data-proven' in body, "the unproven fallback no longer marks itself"


def test_a_TAMPER_refusal_is_shouted_and_a_missing_runtime_is_not():
    """The most serious thing this program can detect about itself must not be delivered
    in the same voice as a missing dependency.

    The shell refuses to render an interface whose hash does not match the one compiled
    into it. Until this existed, the user experience of that refusal was *a browser opening
    instead* — someone whose install had been tampered with would see a slightly different
    window and nothing else.
    """
    from one_link import app as app_mod

    said = []
    orig = app_mod._safe_echo
    app_mod._safe_echo = lambda s="": said.append(s)
    try:
        app_mod._report_shell_refusal(
            "OL_SHELL_FAILED INTERFACE MODIFIED: web/index.html hashes to abc but this shell "
            "was built to render def")
        tamper = "\n".join(said)

        said.clear()
        app_mod._report_shell_refusal(
            "OL_SHELL_FAILED could not create the webview (...) — on Windows this usually means "
            "the WebView2 runtime is not installed")
        benign = "\n".join(said)
    finally:
        app_mod._safe_echo = orig

    assert "REFUSED TO OPEN ITS OWN WINDOW" in tamper, "a tamper signal is not surfaced"
    assert "reinstall" in tamper.lower(), "the user is not told what to do about it"
    assert "NOT the ones that shipped" in tamper

    assert "REFUSED TO OPEN ITS OWN WINDOW" not in benign, (
        "a missing WebView2 runtime shouts like a tamper event -- cry wolf often enough and "
        "the real warning is ignored")
    assert "browser path" in benign


def test_every_refusal_the_shell_can_emit_is_classified():
    """A tamper marker the launcher does not recognise is a tamper event delivered as an
    inconvenience. Every security refusal in the shell must appear in the marker list."""
    rust = _shell_src("main.rs") + _shell_src("certified.rs")
    from one_link.app import _SHELL_TAMPER_MARKERS

    for phrase in ("INTERFACE MODIFIED", "CERTIFIED SURFACE REFUSED", "SIGNATURE INVALID",
                   "DIGEST MISMATCH", "not a pinned signer"):
        assert phrase in rust, f"the shell no longer emits {phrase!r}; the marker list is stale"
        assert phrase in _SHELL_TAMPER_MARKERS


# ── THE WINDOW'S OWN BEHAVIOUR ──────────────────────────────────────────────────────────────
#
# These are behavioural, not source greps. A grep proves a line exists; only running the launcher
# against a shell that misbehaves proves what it DOES about it.


class _Pipe:
    """A stdio pipe that can be told to fail the way a real one does."""

    def __init__(self, fail: bool = False) -> None:
        self.fail = fail
        self.written = ""

    def write(self, s: str) -> None:
        if self.fail:
            raise OSError("the shell went away")
        self.written += s

    def flush(self) -> None:
        if self.fail:
            raise OSError("the shell went away")

    def read(self) -> str:
        return ""

    def readline(self) -> str:
        return ""


class _FakeProc:
    def __init__(self, *, stdin=None, stdout=None, stderr=None, alive: bool = True) -> None:
        self.stdin, self.stdout, self.stderr = stdin, stdout, stderr
        self.terminated = self.killed = False
        self._alive = alive

    def poll(self):
        return None if self._alive else 0

    def terminate(self) -> None:
        self.terminated = True

    def wait(self, timeout=None):
        return 0

    def kill(self) -> None:
        self.killed = True


def _launch_against(monkeypatch, proc, timeout: float = 0.4) -> bool:
    """Drive the real `_open_native_shell` against a shell that behaves like `proc`."""
    from one_link import app as app_mod

    monkeypatch.setattr(app_mod, "_shell_path", lambda: Path("ol_shell.exe"))
    monkeypatch.setattr(app_mod, "_package_root", lambda: "root")
    monkeypatch.setattr(app_mod.subprocess, "Popen", lambda *a, **k: proc)
    monkeypatch.setattr(app_mod, "SHELL_READY_TIMEOUT_S", timeout)
    return app_mod._open_native_shell("http://127.0.0.1:1/?t=nonce")


def test_a_shell_that_never_gets_its_URL_is_SHUT_DOWN_not_left_running(monkeypatch):
    """A shell that never received a URL is blocked reading stdin forever.

    Returning False without ending it means every failed launch leaks a stuck process, and the user
    sees only that the browser opened — the orphan is invisible and permanent.
    """
    proc = _FakeProc(stdin=_Pipe(fail=True), stdout=_Pipe(), stderr=_Pipe())
    assert _launch_against(monkeypatch, proc) is False
    assert proc.terminated, "the launcher abandoned a shell that could not be handed its URL"


def test_a_shell_that_misses_its_DEADLINE_is_SHUT_DOWN_so_there_is_ONE_window(monkeypatch):
    """We are about to open the browser path. A slow-but-working shell would then pop its own
    window too, and the user would be looking at two One Links."""
    proc = _FakeProc(stdin=_Pipe(), stdout=_Pipe(), stderr=_Pipe())
    assert _launch_against(monkeypatch, proc) is False
    assert proc.terminated, "a shell that missed its deadline was left to open a second window"


def test_missing_pipes_DOWNGRADE_to_the_browser_instead_of_raising(monkeypatch):
    """`Popen` types its pipes as optional. Reaching through a None would raise out of a function
    whose entire contract is to return False so the browser path can take over — a crash instead
    of a downgrade, which is the failure this function exists to prevent."""
    proc = _FakeProc(stdin=None, stdout=None, stderr=None)
    assert _launch_against(monkeypatch, proc) is False
    assert proc.terminated


def test_the_window_takes_its_GEOMETRY_from_the_launcher_not_its_own_guess(monkeypatch):
    """ONE source of truth. `_default_window_geometry` already computes 80% of the primary screen,
    clamped, centred, for the browser path. If the shell decided its own size, the window a user
    gets would depend on which launch path ran."""
    from one_link import app as app_mod

    pipe = _Pipe()
    proc = _FakeProc(stdin=pipe, stdout=_Pipe(), stderr=_Pipe())
    monkeypatch.setattr(app_mod, "_default_window_geometry", lambda: (1234, 567, 89, 10))
    _launch_against(monkeypatch, proc)

    lines = pipe.written.splitlines()
    assert len(lines) >= 3, f"the launcher sent {len(lines)} lines; geometry is the third"
    assert lines[2] == "1234 567 89 10", f"geometry line was {lines[2]!r}"

    # ...and the shell must actually READ a third line, or the launcher is talking to itself.
    rust = _shell_src("main.rs")
    code = " ".join(ln for ln in rust.splitlines() if not ln.strip().startswith("//"))
    assert code.count("read_line") >= 3, "the shell reads fewer lines than the launcher sends"
    assert "with_inner_size" in code and "with_position" in code


def test_the_window_carries_ONE_LINKS_icon_not_a_generic_executable_one():
    """Taskbar identity. Windows reads the PE resource table before any of our code runs, so the
    icon has to be embedded at build time — it cannot be set late enough to matter otherwise."""
    build_rs = (SHELL_DIR / "build.rs").read_text(encoding="utf-8")
    code = " ".join(ln for ln in build_rs.splitlines() if not ln.strip().startswith("//"))
    assert "winresource" in code and "set_icon" in code
    assert "rerun-if-changed" in code and ".ico" in code, (
        "cargo watches ONLY the paths named by rerun-if-changed once any is emitted, so without "
        "the icon among them a new icon would never reach the binary")

    icon = Path(__file__).resolve().parents[1] / "src/one_link/web/assets/one-glyph.ico"
    assert icon.is_file(), f"the icon the build embeds is missing: {icon}"
