"""The peer row is drawn from a proven renderer, and the product actually reaches it.

Three laws are discharged over EVERY integer input by the Coherence prover in the `idem` repo at
build time, and the answers ship as `one_link/certified/peer_row.json`:

    the-verified-glyph-requires-verified-trust    scope: exact
    the-name-never-runs-under-the-badge           scope: exact
    nothing-is-drawn-outside-the-row              scope: exact

WHY THIS FILE EXISTS AND NOT JUST THE PROVER'S TESTS. A proof nothing renders from is a capability,
not a surface. The prover's suite can show the laws hold; only these tests can show that One Link
*loads* the table, *verifies* it, and *stamps it onto the rows the UI receives* — and that it fails
closed when the artifact is wrong instead of quietly drawing unproven rows while the code still
claims a proven one.

The security-critical assertion is `test_the_verified_glyph_NEVER_appears_below_verified_trust`,
swept over the entire shipped state space rather than sampled. It is the product-side statement of
the property the whole thing exists for: a peer cannot make your screen say VERIFIED.
"""

from __future__ import annotations

import copy
import json
from pathlib import Path

import pytest

from one_link import certified_surface
from one_link.certified_surface import (
    GLYPH_VERIFIED,
    CertifiedSurface,
    load,
    table_digest,
    verify,
)

ARTIFACT = Path(certified_surface.DEFAULT_ARTIFACT)

VERIFIED, KNOWN, UNKNOWN = 2, 1, 0


@pytest.fixture(scope="module")
def doc() -> dict:
    assert ARTIFACT.exists(), (
        f"the certified artifact is missing at {ARTIFACT}. It is generated by "
        "idem/scripts/emit_peer_row_view.py and committed -- the product ships the answers, "
        "not the prover")
    return json.loads(ARTIFACT.read_text(encoding="utf-8"))


@pytest.fixture(scope="module")
def surface(doc: dict) -> CertifiedSurface:
    ok, why = verify(doc)
    assert ok, why
    return CertifiedSurface(doc)


# ── the artifact is real ──────────────────────────────────────────────


def test_the_shipped_artifact_verifies(doc):
    ok, why = verify(doc)
    assert ok, why
    assert "exhaustive" in why


def test_it_carries_the_five_laws_at_scope_exact(surface):
    names = {n for n, _s in surface.laws}
    assert names == {
        "the-verified-glyph-requires-verified-trust",
        "the-name-never-runs-under-the-badge",
        "nothing-is-drawn-outside-the-row",
        # §10.3 of the design, made a theorem: the a11y tree is not a parallel structure.
        "every-row-says-something",
        "the-spoken-label-cannot-contradict-the-pixel",
    }, f"the shipped laws changed: {sorted(names)}"
    assert all(scope == "exact" for _n, scope in surface.laws), (
        f"a law discharged at a weaker scope than `exact`: {surface.laws}")


def test_the_module_loads_it_from_the_default_path():
    assert load() is not None
    assert certified_surface.available() is True


# ── the security property, over the WHOLE shipped space ───────────────


def test_the_verified_glyph_NEVER_appears_below_verified_trust(surface, doc):
    """THE property, swept rather than sampled.

    The prover discharged this over every integer. This is the product-side statement:
    every row One Link can actually be asked to draw is checked, so a regression in the
    artifact — a hand-edit, a bad regeneration, a truncated file — is caught here even
    though the theorem upstream is untouched.
    """
    checked = 0
    for row in doc["rows"]:
        trust, name_len = row["in"]["trust"], row["in"]["name_len"]
        got = surface.row(trust, name_len)
        assert got is not None
        if trust != VERIFIED:
            assert got.glyph != GLYPH_VERIFIED, (
                f"trust={trust} name_len={name_len} draws the VERIFIED glyph -- a peer that is "
                "not verified would appear verified on screen")
            assert not got.shows_verified()
        checked += 1
    assert checked == len(doc["rows"]) >= 100, f"only {checked} rows swept"


def test_a_verified_peer_DOES_get_the_glyph(surface):
    """NEGATIVE CONTROL. Every assertion above is satisfied by a renderer that never shows
    the badge at all -- which would be secure, useless, and indistinguishable without this."""
    got = surface.row(VERIFIED, 12)
    assert got is not None and got.shows_verified()


def test_the_name_never_runs_under_the_badge(surface, doc):
    for row in doc["rows"]:
        got = surface.row(row["in"]["trust"], row["in"]["name_len"])
        assert got.name_w <= got.badge_x, (
            f"{row['in']} draws a name {got.name_w}px wide under a badge at {got.badge_x}px")


def test_nothing_is_drawn_at_negative_width(surface, doc):
    """The defect the prover caught before it shipped.

    The first renderer clamped only the HIGH side of the name width. A negative name_len --
    or one large enough that `name_len * 8` wraps in i64 -- produced a NEGATIVE width. No
    test written against plausible names would have found it.
    """
    for row in doc["rows"]:
        got = surface.row(row["in"]["trust"], row["in"]["name_len"])
        assert got.name_w >= 0, f"{row['in']} -> negative width {got.name_w}"


# ── it fails CLOSED ───────────────────────────────────────────────────


def test_an_EDITED_table_is_refused(doc):
    """The forgery: flip a row so an unverified peer shows the verified glyph, keep the digest."""
    forged = copy.deepcopy(doc)
    for row in forged["rows"]:
        if row["in"]["trust"] != VERIFIED:
            row["out"]["glyph"] = GLYPH_VERIFIED
            break
    ok, why = verify(forged)
    assert ok is False, "a table edited after certification was accepted"
    assert "DIGEST MISMATCH" in why


def test_a_TRUNCATED_table_is_refused(doc):
    """A missing point is a broken surface, not a smaller one -- and the digest alone
    cannot catch it, because a truncated table hashes consistently with itself."""
    short = copy.deepcopy(doc)
    short["rows"] = short["rows"][:-1]
    short["table_digest"] = table_digest(short["rows"])      # re-hashed, so only coverage catches it
    ok, why = verify(short)
    assert ok is False
    assert "incomplete table" in why


def test_a_table_with_NO_LAWS_is_refused(doc):
    lawless = copy.deepcopy(doc)
    lawless["laws"] = []
    ok, why = verify(lawless)
    assert ok is False
    assert "lookup table with a hash" in why


def test_a_missing_artifact_yields_None_not_an_exception(tmp_path):
    """The UI must degrade to ordinary rendering, never crash the peers API."""
    assert load(tmp_path / "absent.json") is None


def test_a_CORRUPT_artifact_yields_None(tmp_path):
    bad = tmp_path / "bad.json"
    bad.write_text("{not json", encoding="utf-8")
    assert load(bad) is None


def test_a_point_outside_the_certified_space_returns_None(surface):
    """Honest emptiness. Extrapolating past the proven domain would be the unproven code
    this replaces, wearing a digest."""
    assert surface.row(VERIFIED, 9999) is None
    assert surface.covers(VERIFIED, 9999) is False
    assert surface.covers(VERIFIED, 0) is True


# ── the product actually reaches it ───────────────────────────────────


def test_the_peers_API_stamps_the_proven_row():
    """THE integration claim. Source-level, because standing up the full peers handler needs
    discovery, state and a daemon -- but the wiring is what regresses, so it is asserted."""
    src = (Path(__file__).resolve().parents[1] / "src" / "one_link" / "server.py").read_text(
        encoding="utf-8")
    assert "certified_surface.surface()" in src, "the peers API no longer loads the surface"
    assert 'p["certified_row"] = self._certified_row_for(' in src, (
        "peer rows are no longer stamped with the proven layout -- the artifact ships but "
        "nothing renders from it, which is the exact failure this work exists to end")
    assert "def _certified_row_for" in src


def test_the_trust_mapping_requires_IN_PERSON_verification():
    """The one judgement call the proof cannot make.

    The law constrains the renderer: glyph 7 only when the level is VERIFIED. WHICH peers
    count as VERIFIED is the product's decision, and it must be `is_verified` (an in-person
    SAS confirmation) rather than `trust == "pinned"`. Pairing means a key exchange
    happened; it does not mean anyone checked who was on the other end.
    """
    src = (Path(__file__).resolve().parents[1] / "src" / "one_link" / "server.py").read_text(
        encoding="utf-8")
    i = src.index("def _certified_row_for")
    body = src[i:i + 1600]
    assert 'p.get("is_verified")' in body and "level = 2" in body, (
        "the VERIFIED level is no longer gated on in-person verification")
    pinned_at = body.index('"pinned"')
    assert "level = 1" in body[pinned_at:pinned_at + 80], (
        "a merely-pinned peer is being mapped to VERIFIED -- pairing is not verification")


# ── it reaches the SHIPPED bundle, not just the checkout ──────────────


def test_the_build_carries_the_artifact_into_the_bundle():
    """The dev-only trap: everything passes in the checkout and the bundle has no table.

    `certified_surface` resolves its artifact beside the package, so if PyInstaller does not
    carry `one_link/certified` the installed app silently loses the proven surface — and
    `available()` returning False looks identical to "not built yet".
    """
    # The artifact lives under `data/`, which the bundle already carries wholesale via
    # `add_data_package`. That is not an accident of convenience: `validate_python_distributions.py`
    # scans exactly `data` and `web` for package data, so a new top-level `certified/` directory
    # was INVISIBLE to the supply-chain contract and produced a wheel that looked valid while
    # omitting the table. Living inside an already-audited subtree is the property under test.
    build = (Path(__file__).resolve().parents[1] / "scripts" / "build_binary.py").read_text(
        encoding="utf-8")
    assert 'package_data_dir = repo / "src" / "one_link" / "data"' in build
    assert "+ add_data_package" in build, (
        "the bundle no longer carries the data subtree, which is where the certified surface "
        "lives -- the installed app would render every row through the unproven fallback")

    from one_link import certified_surface as cs
    assert cs.DEFAULT_ARTIFACT.parts[-3:] == ("data", "certified", "peer_row.json"), (
        f"the artifact moved to {cs.DEFAULT_ARTIFACT} -- outside `data/` it is invisible to both "
        "the wheel's package-data contract and the distribution validator's source scan")
    pyproject = (Path(__file__).resolve().parents[1] / "pyproject.toml").read_text(encoding="utf-8")
    assert '"data/certified/peer_row.json"' in pyproject, (
        "the wheel no longer declares the artifact; a pip install would omit it silently")


def test_the_build_REFUSES_when_the_artifact_is_missing():
    """A skipped-if-absent asset is a dark gate.

    If the build merely omitted a missing artifact, the bundle would run, every row would fall
    back to unproven layout, and the code would still claim a proven surface. That failure is
    invisible from the outside, so the build has to stop.
    """
    build = (Path(__file__).resolve().parents[1] / "scripts" / "build_binary.py").read_text(
        encoding="utf-8")
    i = build.index("certified_dir = repo")
    window = build[i:i + 1200]
    assert "return 6" in window, "a missing certified surface no longer fails the build"
    assert "is_file()" in window


# ── against a LIVE server, because a source grep is not a running product ──

import pytest_asyncio  # noqa: E402
from aiohttp.test_utils import TestClient, TestServer  # noqa: E402
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey  # noqa: E402

from one_link.daemon import Daemon  # noqa: E402
from one_link.identity import Identity, fingerprint_of  # noqa: E402
from one_link.server import UIServer  # noqa: E402
from one_link.state import State  # noqa: E402


def _identity(host: str = "cert-host") -> Identity:
    sk = Ed25519PrivateKey.generate()
    pub = sk.public_key()
    pb = pub.public_bytes_raw()
    fp = fingerprint_of(pb)
    return Identity(private=sk, public=pub, public_bytes=pb, fingerprint=fp,
                    short_id=fp[:8], hostname=host)


@pytest_asyncio.fixture
async def live(tmp_path, monkeypatch):
    """A real UIServer with one PINNED peer and one VERIFIED peer in state."""
    monkeypatch.setenv("ONE_LINK_HOME", str(tmp_path))
    state = State(db_path=tmp_path / "state.db")

    pinned_fp, verified_fp = "aa" * 32, "bb" * 32
    for fp, host in ((pinned_fp, "pinned-peer"), (verified_fp, "verified-peer")):
        state.upsert_peer(fingerprint=fp, short_id=fp[:8], pubkey=b"\x01" * 32, hostname=host)
        state.set_peer_trust(fp, "pinned")
    # Only the second one has been verified in person.
    state.set_peer_verified(verified_fp, method="sas-digits", note="test fixture")

    daemon = Daemon(_identity())
    daemon.state = state
    daemon.discovery = None
    daemon._outbound_sessions = {}
    daemon._inbound_regime = {}
    daemon.folder_engine = None

    server = UIServer(daemon)
    client = TestClient(TestServer(server.app))
    await client.start_server()
    try:
        yield client, server, {"pinned": pinned_fp, "verified": verified_fp}
    finally:
        await client.close()
        state.close()


@pytest.mark.asyncio
async def test_the_peers_API_really_returns_a_certified_row(live):
    """THE integration claim, executed rather than grepped.

    If the surface failed to load inside the running server -- a packaging path, a cached
    None, an import ordering problem -- every source assertion above would still pass and
    the product would render nothing proven.
    """
    client, server, _fps = live
    resp = await client.get("/api/peers", headers={"Authorization": f"Bearer {server.token}"})
    assert resp.status == 200, await resp.text()
    peers = (await resp.json()).get("peers") or []
    assert peers, "no peers returned; the assertions below would be vacuous"

    stamped = [p for p in peers if p.get("certified_row")]
    assert stamped, (
        "not one peer carried `certified_row` -- the artifact ships but the running server "
        "does not render from it, which is precisely the gap this work exists to close")
    for p in stamped:
        row = p["certified_row"]
        assert {"glyph", "name_w", "badge_x", "digest"} <= set(row)
        assert row["name_w"] <= row["badge_x"]
        assert row["name_w"] >= 0


@pytest.mark.asyncio
async def test_a_PINNED_but_unverified_peer_does_NOT_get_the_verified_glyph(live):
    """The security property, end to end through the real API.

    Both peers are `trust == "pinned"`. Only one has an in-person SAS verification. If the
    mapping ever collapses those two states, a peer you merely paired with would render as
    verified -- and pairing is a key exchange, not a statement about who is on the far end.
    """
    client, server, _fps = live
    resp = await client.get("/api/peers", headers={"Authorization": f"Bearer {server.token}"})
    peers = (await resp.json()).get("peers") or []
    by_host = {p.get("hostname"): p for p in peers}

    pinned = by_host.get("pinned-peer")
    verified = by_host.get("verified-peer")
    assert pinned and verified, f"fixture peers missing from the API: {sorted(by_host)}"

    assert pinned["trust"] == "pinned" and verified["trust"] == "pinned", (
        "both fixture peers must be pinned, or this test is not isolating VERIFICATION")

    assert pinned["certified_row"]["glyph"] != GLYPH_VERIFIED, (
        "a paired-but-unverified peer renders the VERIFIED glyph")
    assert verified["certified_row"]["glyph"] == GLYPH_VERIFIED, (
        "an in-person-verified peer does NOT render the verified glyph -- the badge would "
        "never appear and the control above would be vacuous")


# ── the UI draws from it, not merely receives it ──────────────────────


def _ui() -> str:
    return (Path(__file__).resolve().parents[1] / "src" / "one_link" / "web" /
            "index.html").read_text(encoding="utf-8")


def test_the_badge_is_decided_by_the_PROVEN_table():
    """The last mile. The server can stamp a proven row and the UI can ignore it.

    `renderConvHeaderTrust` is the function that puts the verified pill on screen. It must
    take its answer from `certified_row.glyph`, not from an ad-hoc `is_verified` conditional
    -- the pixels are the same either way, which is exactly why nothing but a test would
    notice the authority quietly moving back.
    """
    html = _ui()
    assert "function verifiedByProof(peer)" in html, (
        "the UI no longer consults the proven table for the verified badge")
    assert "row.glyph === GLYPH_VERIFIED" in html
    i = html.index("function renderConvHeaderTrust(peer)")
    body = html[i:i + 1400]
    assert "verifiedByProof(peer)" in body, (
        "renderConvHeaderTrust decides the badge without asking the proven renderer")


def test_the_UNPROVEN_fallback_is_never_silent():
    """A fallback nobody can see is how the unproven path comes back.

    When no certified row is present the UI must still render -- but it has to RECORD that
    it fell back, or 'proven' becomes a claim with no way to check it after the fact.
    """
    html = _ui()
    i = html.index("function renderConvHeaderTrust(peer)")
    body = html[i:i + 1400]
    assert 'data-proven' in body, "the fallback does not mark itself"
    assert '"unavailable"' in body


def test_the_verified_glyph_constant_matches_the_server():
    """A constant that drifts between the two sides is a badge that lies on one of them."""
    html = _ui()
    assert "const GLYPH_VERIFIED = 7;" in html
    assert GLYPH_VERIFIED == 7


# ── identity: the digest proves nobody EDITED it; the signature proves nobody MADE it ──
#
# Everything above is self-referential. An adversary who edits an answer AND recomputes the digest
# produces a perfectly self-consistent artifact, because a hash is not an identity. These are the
# tests that distinguish the two properties.

import hashlib as _hashlib  # noqa: E402

from cryptography.hazmat.primitives.asymmetric.ed25519 import (  # noqa: E402
    Ed25519PrivateKey,
)

from one_link.certified_surface import (  # noqa: E402
    DEVELOPMENT_SIGNER,
    TRUSTED_VIEW_SIGNERS,
    _signable,
    signature_ok,
)


def _resign(doc: dict, sk: Ed25519PrivateKey) -> dict:
    """Sign a (possibly forged) artifact with an arbitrary key, as an attacker would."""
    body = {k: v for k, v in doc.items() if k not in ("signature", "signer")}
    pub = sk.public_key().public_bytes_raw().hex()
    signed = {**body, "signer": pub}
    return {**signed, "signature": sk.sign(_signable(signed)).hex()}


def test_the_shipped_artifact_is_SIGNED_by_a_pinned_key(doc):
    ok, why = signature_ok(doc)
    assert ok, why
    assert doc["signer"] in TRUSTED_VIEW_SIGNERS


def test_an_UNSIGNED_artifact_is_refused(doc):
    """The property the digest cannot give: a table nobody stands behind."""
    bare = {k: v for k, v in doc.items() if k not in ("signature", "signer")}
    ok, why = verify(bare)
    assert ok is False
    assert "UNSIGNED" in why


def test_a_FORGERY_with_a_recomputed_digest_is_refused(doc):
    """THE case signing exists for, and the one the digest alone waves through.

    The attacker flips an unverified peer to the verified glyph, then recomputes the table
    digest so the artifact is internally perfect. Every structural check passes. Only the
    signature refuses it.
    """
    forged = copy.deepcopy(doc)
    for row in forged["rows"]:
        if row["in"]["trust"] != VERIFIED:
            row["out"]["glyph"] = GLYPH_VERIFIED
            break
    forged["table_digest"] = table_digest(forged["rows"])       # internally consistent now

    assert table_digest(forged["rows"]) == forged["table_digest"], (
        "the forgery is not self-consistent, so this test would pass for the wrong reason")

    ok, why = verify(forged)
    assert ok is False, "a forged table with a recomputed digest was accepted"
    assert "SIGNATURE INVALID" in why, why


def test_a_forgery_RESIGNED_with_the_attackers_own_key_is_refused(doc):
    """The obvious escalation: if they can recompute a digest, they can sign it too.

    This is why the signer is PINNED. An artifact verified against whatever key it names is
    verified against its author, which is no verification at all.
    """
    forged = copy.deepcopy(doc)
    forged["rows"][0]["out"]["glyph"] = GLYPH_VERIFIED
    forged["table_digest"] = table_digest(forged["rows"])
    attacker = _resign(forged, Ed25519PrivateKey.generate())

    ok, why = signature_ok(attacker)
    assert ok is False, "an artifact signed by an arbitrary key was accepted"
    assert "not a pinned signer" in why

    ok2, _ = verify(attacker)
    assert ok2 is False


def test_the_signature_covers_EVERY_field_including_ones_added_later(doc):
    """Coverage by exclusion, not by a hand-maintained list.

    A signature scoped to an enumerated set of keys silently stops covering the newest field
    anyone adds. Mutating a field the signer never explicitly listed must still break it.
    """
    tampered = copy.deepcopy(doc)
    tampered["laws"] = [["a-law-nobody-proved", "exact"]]
    ok, _ = signature_ok(tampered)
    assert ok is False, "the `laws` field is outside the signature's coverage"

    tampered2 = copy.deepcopy(doc)
    tampered2["class_fingerprint"] = "0" * 64
    assert signature_ok(tampered2)[0] is False, "the fingerprint is outside the coverage"


def test_the_signable_bytes_match_the_producers_rule(doc):
    """A domain-separator divergence does not fail loudly -- it rejects every honest artifact.

    Pinned explicitly so a change on either side is a test failure rather than a silent
    outage where the surface simply stops loading everywhere.
    """
    body = {k: v for k, v in doc.items() if k not in ("signature", "signer")}
    expected = b"idem-view-sig/v1\x00" + json.dumps(
        body, sort_keys=True, separators=(",", ":"), ensure_ascii=True).encode("ascii")
    assert _signable(doc) == expected
    assert _hashlib.sha256(_signable(doc)).digest()          # it is bytes, and non-empty


# ── the development key must not ride into a release ──────────────────


def test_a_RELEASE_build_must_not_pin_the_development_key():
    """THE gate that stops this being security theatre.

    The pinned key is derived from a published phrase, so anyone can produce a table this
    build accepts. That is fine for making the path real and testable now — and it must not
    survive into a release. If this fails, generate a release key, pin its pubkey, and drop
    `DEVELOPMENT_SIGNER`.
    """
    from one_link import __version__

    prerelease = any(tag in __version__ for tag in ("alpha", "beta", "rc", "dev"))
    if not prerelease:
        assert DEVELOPMENT_SIGNER not in TRUSTED_VIEW_SIGNERS, (
            f"version {__version__} looks like a RELEASE and still trusts the development "
            "signing key. Anyone can forge a certified surface this build will accept. "
            "Generate a release key, pin its pubkey in TRUSTED_VIEW_SIGNERS, and remove "
            "DEVELOPMENT_SIGNER.")
    assert TRUSTED_VIEW_SIGNERS, "no pinned signer at all: every artifact would be refused"


def test_the_development_key_is_labelled_as_one_in_the_source():
    """A published key that does not say so is the dangerous kind."""
    src = (Path(__file__).resolve().parents[1] / "src" / "one_link" /
           "certified_surface.py").read_text(encoding="utf-8")
    i = src.index("DEVELOPMENT_SIGNER")
    window = src[max(0, i - 1400):i]
    assert "DEVELOPMENT KEY" in window and "not-for-release" in window, (
        "the development key is no longer marked as one where a reader would see it")


# ── the screen reader and the pixel cannot disagree ───────────────────
#
# Every mainstream stack maintains the semantic tree ALONGSIDE the visual one and the mapping rots
# silently: a badge is restyled, the aria-label stays, and a blind user is told something the screen
# stopped saying two quarters ago. Nothing detects it, because no component holds both at once.
#
# Here the label is an output of the SAME renderer as the pixel, and the agreement is DISCHARGED
# over every integer input rather than left to construction.


def test_the_spoken_label_and_the_pixel_agree_on_EVERY_shipped_row(surface, doc):
    """The product-side sweep of `the-spoken-label-cannot-contradict-the-pixel`."""
    from one_link.certified_surface import LABEL_VERIFIED

    checked = 0
    for row in doc["rows"]:
        got = surface.row(row["in"]["trust"], row["in"]["name_len"])
        assert got.shows_verified() == got.says_verified(), (
            f"{row['in']}: the badge shows verified={got.shows_verified()} while the screen "
            f"reader says verified={got.says_verified()} -- a blind user and a sighted user are "
            "being told different things about the same peer")
        if row["in"]["trust"] == VERIFIED:
            assert got.label == LABEL_VERIFIED
        checked += 1
    assert checked == len(doc["rows"])


def test_every_shipped_row_says_SOMETHING(surface, doc):
    """A row that announces nothing is invisible to a screen reader while visible on screen."""
    for row in doc["rows"]:
        got = surface.row(row["in"]["trust"], row["in"]["name_len"])
        assert got.spoken().strip(), f"{row['in']} announces nothing"


def test_an_UNKNOWN_label_id_falls_back_to_the_most_conservative_text():
    """Fail safe, not silent. An id the product does not recognise must under-claim rather
    than announce nothing -- and must never announce verification it cannot support."""
    from one_link.certified_surface import LABEL_TEXT, LABEL_NONE, CertifiedRow

    weird = CertifiedRow(glyph=0, name_w=10, badge_x=296, label=99)
    assert weird.spoken() == LABEL_TEXT[LABEL_NONE]
    assert "erified in person" not in weird.spoken()


def test_the_peers_API_carries_the_spoken_label():
    src = (Path(__file__).resolve().parents[1] / "src" / "one_link" / "server.py").read_text(
        encoding="utf-8")
    assert '"spoken": row.spoken(),' in src and '"label": row.label,' in src, (
        "the API no longer sends the proven accessible label, so the UI has nothing to speak")


def test_the_UI_sets_aria_label_from_the_PROOF():
    html = _ui()
    assert "function spokenByProof(peer)" in html
    i = html.index("function renderConvHeaderTrust(peer)")
    body = html[i:i + 2000]
    assert "spokenByProof(peer)" in body and 'setAttribute("aria-label"' in body, (
        "the verified pill's aria-label is no longer taken from the proven renderer -- it is "
        "back to being a string maintained beside the badge, which is the drift this replaces")
