"""The peer row is drawn from a proven renderer, and the product actually reaches it.

Three laws are discharged over EVERY integer input by the Coherence prover in the `idem` repo at
build time, and the answers ship as `one_link/certified/peer_row.json`:

    the-verified-glyph-requires-verified-trust    scope: exact
    the-name-never-runs-under-the-badge           scope: exact
    nothing-is-drawn-outside-the-row              scope: exact

WHY THIS FILE EXISTS AND NOT JUST THE PROVER'S TESTS. A proof nothing renders from is a capability,
not a surface. The prover's suite can show the laws hold; only these tests can show that One Link
*loads* the table, *verifies* it, and *stamps it onto the rows the UI receives* — and that it fails
closed when the artifact is wrong instead of quietly drawing unproven rows while the code still
claims a proven one.

The security-critical assertion is `test_the_verified_glyph_NEVER_appears_below_verified_trust`,
swept over the entire shipped state space rather than sampled. It is the product-side statement of
the property the whole thing exists for: a peer cannot make your screen say VERIFIED.
"""

from __future__ import annotations

import copy
import json
from pathlib import Path

import pytest

from one_link import certified_surface
from one_link.certified_surface import (
    GLYPH_VERIFIED,
    CertifiedSurface,
    load,
    table_digest,
    verify,
)

ARTIFACT = Path(certified_surface.DEFAULT_ARTIFACT)

VERIFIED, KNOWN, UNKNOWN = 2, 1, 0


@pytest.fixture(scope="module")
def doc() -> dict:
    assert ARTIFACT.exists(), (
        f"the certified artifact is missing at {ARTIFACT}. It is generated by "
        "idem/scripts/emit_peer_row_view.py and committed -- the product ships the answers, "
        "not the prover")
    return json.loads(ARTIFACT.read_text(encoding="utf-8"))


@pytest.fixture(scope="module")
def surface(doc: dict) -> CertifiedSurface:
    ok, why = verify(doc)
    assert ok, why
    return CertifiedSurface(doc)


# ── the artifact is real ──────────────────────────────────────────────


def test_the_shipped_artifact_verifies(doc):
    ok, why = verify(doc)
    assert ok, why
    assert "exhaustive" in why


def test_it_carries_the_three_laws_at_scope_exact(surface):
    names = {n for n, _s in surface.laws}
    assert names == {
        "the-verified-glyph-requires-verified-trust",
        "the-name-never-runs-under-the-badge",
        "nothing-is-drawn-outside-the-row",
    }, f"the shipped laws changed: {sorted(names)}"
    assert all(scope == "exact" for _n, scope in surface.laws), (
        f"a law discharged at a weaker scope than `exact`: {surface.laws}")


def test_the_module_loads_it_from_the_default_path():
    assert load() is not None
    assert certified_surface.available() is True


# ── the security property, over the WHOLE shipped space ───────────────


def test_the_verified_glyph_NEVER_appears_below_verified_trust(surface, doc):
    """THE property, swept rather than sampled.

    The prover discharged this over every integer. This is the product-side statement:
    every row One Link can actually be asked to draw is checked, so a regression in the
    artifact — a hand-edit, a bad regeneration, a truncated file — is caught here even
    though the theorem upstream is untouched.
    """
    checked = 0
    for row in doc["rows"]:
        trust, name_len = row["in"]["trust"], row["in"]["name_len"]
        got = surface.row(trust, name_len)
        assert got is not None
        if trust != VERIFIED:
            assert got.glyph != GLYPH_VERIFIED, (
                f"trust={trust} name_len={name_len} draws the VERIFIED glyph -- a peer that is "
                "not verified would appear verified on screen")
            assert not got.shows_verified()
        checked += 1
    assert checked == len(doc["rows"]) >= 100, f"only {checked} rows swept"


def test_a_verified_peer_DOES_get_the_glyph(surface):
    """NEGATIVE CONTROL. Every assertion above is satisfied by a renderer that never shows
    the badge at all -- which would be secure, useless, and indistinguishable without this."""
    got = surface.row(VERIFIED, 12)
    assert got is not None and got.shows_verified()


def test_the_name_never_runs_under_the_badge(surface, doc):
    for row in doc["rows"]:
        got = surface.row(row["in"]["trust"], row["in"]["name_len"])
        assert got.name_w <= got.badge_x, (
            f"{row['in']} draws a name {got.name_w}px wide under a badge at {got.badge_x}px")


def test_nothing_is_drawn_at_negative_width(surface, doc):
    """The defect the prover caught before it shipped.

    The first renderer clamped only the HIGH side of the name width. A negative name_len --
    or one large enough that `name_len * 8` wraps in i64 -- produced a NEGATIVE width. No
    test written against plausible names would have found it.
    """
    for row in doc["rows"]:
        got = surface.row(row["in"]["trust"], row["in"]["name_len"])
        assert got.name_w >= 0, f"{row['in']} -> negative width {got.name_w}"


# ── it fails CLOSED ───────────────────────────────────────────────────


def test_an_EDITED_table_is_refused(doc):
    """The forgery: flip a row so an unverified peer shows the verified glyph, keep the digest."""
    forged = copy.deepcopy(doc)
    for row in forged["rows"]:
        if row["in"]["trust"] != VERIFIED:
            row["out"]["glyph"] = GLYPH_VERIFIED
            break
    ok, why = verify(forged)
    assert ok is False, "a table edited after certification was accepted"
    assert "DIGEST MISMATCH" in why


def test_a_TRUNCATED_table_is_refused(doc):
    """A missing point is a broken surface, not a smaller one -- and the digest alone
    cannot catch it, because a truncated table hashes consistently with itself."""
    short = copy.deepcopy(doc)
    short["rows"] = short["rows"][:-1]
    short["table_digest"] = table_digest(short["rows"])      # re-hashed, so only coverage catches it
    ok, why = verify(short)
    assert ok is False
    assert "incomplete table" in why


def test_a_table_with_NO_LAWS_is_refused(doc):
    lawless = copy.deepcopy(doc)
    lawless["laws"] = []
    ok, why = verify(lawless)
    assert ok is False
    assert "lookup table with a hash" in why


def test_a_missing_artifact_yields_None_not_an_exception(tmp_path):
    """The UI must degrade to ordinary rendering, never crash the peers API."""
    assert load(tmp_path / "absent.json") is None


def test_a_CORRUPT_artifact_yields_None(tmp_path):
    bad = tmp_path / "bad.json"
    bad.write_text("{not json", encoding="utf-8")
    assert load(bad) is None


def test_a_point_outside_the_certified_space_returns_None(surface):
    """Honest emptiness. Extrapolating past the proven domain would be the unproven code
    this replaces, wearing a digest."""
    assert surface.row(VERIFIED, 9999) is None
    assert surface.covers(VERIFIED, 9999) is False
    assert surface.covers(VERIFIED, 0) is True


# ── the product actually reaches it ───────────────────────────────────


def test_the_peers_API_stamps_the_proven_row():
    """THE integration claim. Source-level, because standing up the full peers handler needs
    discovery, state and a daemon -- but the wiring is what regresses, so it is asserted."""
    src = (Path(__file__).resolve().parents[1] / "src" / "one_link" / "server.py").read_text(
        encoding="utf-8")
    assert "certified_surface.surface()" in src, "the peers API no longer loads the surface"
    assert 'p["certified_row"] = self._certified_row_for(' in src, (
        "peer rows are no longer stamped with the proven layout -- the artifact ships but "
        "nothing renders from it, which is the exact failure this work exists to end")
    assert "def _certified_row_for" in src


def test_the_trust_mapping_requires_IN_PERSON_verification():
    """The one judgement call the proof cannot make.

    The law constrains the renderer: glyph 7 only when the level is VERIFIED. WHICH peers
    count as VERIFIED is the product's decision, and it must be `is_verified` (an in-person
    SAS confirmation) rather than `trust == "pinned"`. Pairing means a key exchange
    happened; it does not mean anyone checked who was on the other end.
    """
    src = (Path(__file__).resolve().parents[1] / "src" / "one_link" / "server.py").read_text(
        encoding="utf-8")
    i = src.index("def _certified_row_for")
    body = src[i:i + 1600]
    assert 'p.get("is_verified")' in body and "level = 2" in body, (
        "the VERIFIED level is no longer gated on in-person verification")
    pinned_at = body.index('"pinned"')
    assert "level = 1" in body[pinned_at:pinned_at + 80], (
        "a merely-pinned peer is being mapped to VERIFIED -- pairing is not verification")


# ── it reaches the SHIPPED bundle, not just the checkout ──────────────


def test_the_build_carries_the_artifact_into_the_bundle():
    """The dev-only trap: everything passes in the checkout and the bundle has no table.

    `certified_surface` resolves its artifact beside the package, so if PyInstaller does not
    carry `one_link/certified` the installed app silently loses the proven surface — and
    `available()` returning False looks identical to "not built yet".
    """
    # The artifact lives under `data/`, which the bundle already carries wholesale via
    # `add_data_package`. That is not an accident of convenience: `validate_python_distributions.py`
    # scans exactly `data` and `web` for package data, so a new top-level `certified/` directory
    # was INVISIBLE to the supply-chain contract and produced a wheel that looked valid while
    # omitting the table. Living inside an already-audited subtree is the property under test.
    build = (Path(__file__).resolve().parents[1] / "scripts" / "build_binary.py").read_text(
        encoding="utf-8")
    assert 'package_data_dir = repo / "src" / "one_link" / "data"' in build
    assert "+ add_data_package" in build, (
        "the bundle no longer carries the data subtree, which is where the certified surface "
        "lives -- the installed app would render every row through the unproven fallback")

    from one_link import certified_surface as cs
    assert cs.DEFAULT_ARTIFACT.parts[-3:] == ("data", "certified", "peer_row.json"), (
        f"the artifact moved to {cs.DEFAULT_ARTIFACT} -- outside `data/` it is invisible to both "
        "the wheel's package-data contract and the distribution validator's source scan")
    pyproject = (Path(__file__).resolve().parents[1] / "pyproject.toml").read_text(encoding="utf-8")
    assert '"data/certified/peer_row.json"' in pyproject, (
        "the wheel no longer declares the artifact; a pip install would omit it silently")


def test_the_build_REFUSES_when_the_artifact_is_missing():
    """A skipped-if-absent asset is a dark gate.

    If the build merely omitted a missing artifact, the bundle would run, every row would fall
    back to unproven layout, and the code would still claim a proven surface. That failure is
    invisible from the outside, so the build has to stop.
    """
    build = (Path(__file__).resolve().parents[1] / "scripts" / "build_binary.py").read_text(
        encoding="utf-8")
    i = build.index("certified_dir = repo")
    window = build[i:i + 1200]
    assert "return 6" in window, "a missing certified surface no longer fails the build"
    assert "is_file()" in window


# ── against a LIVE server, because a source grep is not a running product ──

import pytest_asyncio  # noqa: E402
from aiohttp.test_utils import TestClient, TestServer  # noqa: E402
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey  # noqa: E402

from one_link.daemon import Daemon  # noqa: E402
from one_link.identity import Identity, fingerprint_of  # noqa: E402
from one_link.server import UIServer  # noqa: E402
from one_link.state import State  # noqa: E402


def _identity(host: str = "cert-host") -> Identity:
    sk = Ed25519PrivateKey.generate()
    pub = sk.public_key()
    pb = pub.public_bytes_raw()
    fp = fingerprint_of(pb)
    return Identity(private=sk, public=pub, public_bytes=pb, fingerprint=fp,
                    short_id=fp[:8], hostname=host)


@pytest_asyncio.fixture
async def live(tmp_path, monkeypatch):
    """A real UIServer with one PINNED peer and one VERIFIED peer in state."""
    monkeypatch.setenv("ONE_LINK_HOME", str(tmp_path))
    state = State(db_path=tmp_path / "state.db")

    pinned_fp, verified_fp = "aa" * 32, "bb" * 32
    for fp, host in ((pinned_fp, "pinned-peer"), (verified_fp, "verified-peer")):
        state.upsert_peer(fingerprint=fp, short_id=fp[:8], pubkey=b"\x01" * 32, hostname=host)
        state.set_peer_trust(fp, "pinned")
    # Only the second one has been verified in person.
    state.set_peer_verified(verified_fp, method="sas-digits", note="test fixture")

    daemon = Daemon(_identity())
    daemon.state = state
    daemon.discovery = None
    daemon._outbound_sessions = {}
    daemon._inbound_regime = {}
    daemon.folder_engine = None

    server = UIServer(daemon)
    client = TestClient(TestServer(server.app))
    await client.start_server()
    try:
        yield client, server, {"pinned": pinned_fp, "verified": verified_fp}
    finally:
        await client.close()
        state.close()


@pytest.mark.asyncio
async def test_the_peers_API_really_returns_a_certified_row(live):
    """THE integration claim, executed rather than grepped.

    If the surface failed to load inside the running server -- a packaging path, a cached
    None, an import ordering problem -- every source assertion above would still pass and
    the product would render nothing proven.
    """
    client, server, _fps = live
    resp = await client.get("/api/peers", headers={"Authorization": f"Bearer {server.token}"})
    assert resp.status == 200, await resp.text()
    peers = (await resp.json()).get("peers") or []
    assert peers, "no peers returned; the assertions below would be vacuous"

    stamped = [p for p in peers if p.get("certified_row")]
    assert stamped, (
        "not one peer carried `certified_row` -- the artifact ships but the running server "
        "does not render from it, which is precisely the gap this work exists to close")
    for p in stamped:
        row = p["certified_row"]
        assert {"glyph", "name_w", "badge_x", "digest"} <= set(row)
        assert row["name_w"] <= row["badge_x"]
        assert row["name_w"] >= 0


@pytest.mark.asyncio
async def test_a_PINNED_but_unverified_peer_does_NOT_get_the_verified_glyph(live):
    """The security property, end to end through the real API.

    Both peers are `trust == "pinned"`. Only one has an in-person SAS verification. If the
    mapping ever collapses those two states, a peer you merely paired with would render as
    verified -- and pairing is a key exchange, not a statement about who is on the far end.
    """
    client, server, _fps = live
    resp = await client.get("/api/peers", headers={"Authorization": f"Bearer {server.token}"})
    peers = (await resp.json()).get("peers") or []
    by_host = {p.get("hostname"): p for p in peers}

    pinned = by_host.get("pinned-peer")
    verified = by_host.get("verified-peer")
    assert pinned and verified, f"fixture peers missing from the API: {sorted(by_host)}"

    assert pinned["trust"] == "pinned" and verified["trust"] == "pinned", (
        "both fixture peers must be pinned, or this test is not isolating VERIFICATION")

    assert pinned["certified_row"]["glyph"] != GLYPH_VERIFIED, (
        "a paired-but-unverified peer renders the VERIFIED glyph")
    assert verified["certified_row"]["glyph"] == GLYPH_VERIFIED, (
        "an in-person-verified peer does NOT render the verified glyph -- the badge would "
        "never appear and the control above would be vacuous")


# ── the UI draws from it, not merely receives it ──────────────────────


def _ui() -> str:
    return (Path(__file__).resolve().parents[1] / "src" / "one_link" / "web" /
            "index.html").read_text(encoding="utf-8")


def test_the_badge_is_decided_by_the_PROVEN_table():
    """The last mile. The server can stamp a proven row and the UI can ignore it.

    `renderConvHeaderTrust` is the function that puts the verified pill on screen. It must
    take its answer from `certified_row.glyph`, not from an ad-hoc `is_verified` conditional
    -- the pixels are the same either way, which is exactly why nothing but a test would
    notice the authority quietly moving back.
    """
    html = _ui()
    assert "function verifiedByProof(peer)" in html, (
        "the UI no longer consults the proven table for the verified badge")
    assert "row.glyph === GLYPH_VERIFIED" in html
    i = html.index("function renderConvHeaderTrust(peer)")
    body = html[i:i + 1400]
    assert "verifiedByProof(peer)" in body, (
        "renderConvHeaderTrust decides the badge without asking the proven renderer")


def test_the_UNPROVEN_fallback_is_never_silent():
    """A fallback nobody can see is how the unproven path comes back.

    When no certified row is present the UI must still render -- but it has to RECORD that
    it fell back, or 'proven' becomes a claim with no way to check it after the fact.
    """
    html = _ui()
    i = html.index("function renderConvHeaderTrust(peer)")
    body = html[i:i + 1400]
    assert 'data-proven' in body, "the fallback does not mark itself"
    assert '"unavailable"' in body


def test_the_verified_glyph_constant_matches_the_server():
    """A constant that drifts between the two sides is a badge that lies on one of them."""
    html = _ui()
    assert "const GLYPH_VERIFIED = 7;" in html
    assert GLYPH_VERIFIED == 7
