"""Type stubs for the ``one_link_native`` pyo3 extension (PEP 561 stub package).

Hand-written stubs that mirror the runtime surface so mypy / pyright
give callers correct types across the FFI boundary. Stubs only —
the compiled extension lives in the matching ``one_link_native``
runtime package next to this one.

Regeneration policy: whenever a pyo3 binding gains or loses a method
or argument, update the matching ``*.pyi`` here. The
``tests/unit/test_phase_c3_native_smoke.py`` smoke + the
``test_*_migration.py`` integration tests exercise every binding the
stubs declare; mismatches surface there.
"""

# Re-export submodule namespaces so `from one_link_native import capability`
# sees the right type surface.
from . import aead as aead
from . import bandit as bandit
from . import capability as capability
from . import crdt as crdt
from . import hwkey as hwkey
from . import onion as onion
from . import pair_qr as pair_qr
from . import pqkem as pqkem
from . import ratchet as ratchet

# Top-level exception hierarchy.
class OlError(Exception): ...
class OlChunkError(OlError): ...
class OlAeadError(OlError): ...
class OlWalError(OlError): ...
class OlChunkStoreError(OlError): ...
class OlQuicError(OlError): ...
class OlBloomError(OlError): ...
class OlFountainError(OlError): ...
class OlFecError(OlError): ...
class OlRatchetError(OlError): ...
class OlPqKemError(OlError): ...
class OlErasureError(OlError): ...
class OlBanditError(OlError): ...
class OlCapabilityError(OlError): ...
class OlCrdtError(OlError): ...
class OlHwKeyError(OlError): ...

__version__: str
chunk_version: str
