"""Type stubs for ``one_link_native.bandit`` (ADR-0019)."""

from typing import List, Tuple

__version__: str


class Bandit:
    def __init__(self, n_arms: int, seed: int = ...) -> None: ...

    n_arms: int

    def select(self) -> int: ...
    def update(self, arm_idx: int, reward: float) -> None: ...
    def best_arm(self) -> int: ...
    def arms(self) -> List[Tuple[float, float]]: ...
    def reseed(self, seed: int) -> None: ...
