"""Type stubs for ``one_link_native.crdt`` (ADR-0022)."""

from typing import Tuple


class Folder:
    def __init__(self) -> None: ...

    def add_file(
        self,
        replica: bytes,
        file_id: bytes,
        display_name: str,
        size_bytes: int,
        last_modified_ms: int,
    ) -> None: ...
    def remove_file(self, replica: bytes, file_id: bytes) -> None: ...
    def contains(self, file_id: bytes) -> bool: ...
    def merge(self, other: "Folder") -> None: ...
    def len(self) -> int: ...
    def entries(self) -> list[Tuple[bytes, str, int, int]]: ...
