"""Type stubs for ``one_link_native.hwkey`` (ADR-0023)."""


class TofuStore:
    def __init__(self, root: bytes) -> None: ...

    def guarantee(self) -> str: ...
    def get_or_create(self, label: str) -> str: ...
    def public_key(self, label: str) -> bytes: ...
    def check_tofu(self, label: str, presented: bytes) -> bool: ...
