"""Type stubs for one_link_native.obfs (row 7 pluggable transport)."""

OBFS_KEY_LEN: int
OBFS_NONCE_LEN: int

def obfuscate(key: bytes, nonce: bytes, data: bytes) -> bytes: ...
def deobfuscate(key: bytes, nonce: bytes, data: bytes) -> bytes: ...
def derive_nonce(conn_id: int, packet_counter: int) -> bytes: ...
