"""Type stubs for one_link_native.obfs (row 7 pluggable transport)."""

from typing import Tuple

OBFS_KEY_LEN: int
OBFS_NONCE_LEN: int
BRIDGE_PUBKEY_LEN: int
BRIDGE_SECRET_LEN: int
BRIDGE_ID_LEN: int
HANDSHAKE_LEN: int
HANDSHAKE_MAC_LEN: int
HANDSHAKE_EPOCH_SECS: int
SESSION_KEY_LEN: int

def obfuscate(key: bytes, nonce: bytes, data: bytes) -> bytes: ...
def deobfuscate(key: bytes, nonce: bytes, data: bytes) -> bytes: ...
def derive_nonce(conn_id: int, packet_counter: int) -> bytes: ...
def generate_bridge_keypair() -> Tuple[bytes, bytes, bytes]: ...
def server_accept(
    bridge_secret: bytes,
    bridge_id: bytes,
    client_first_message: bytes,
    now_unix: int,
) -> Tuple[bytes, "Session"]: ...

class ClientHandshake:
    def __init__(
        self, bridge_public: bytes, bridge_id: bytes, now_unix: int
    ) -> None: ...
    def first_message(self) -> bytes: ...
    def finish(self, server_reply: bytes) -> "Session": ...

class Session:
    def seal_outbound(self, plaintext: bytes, counter: int) -> bytes: ...
    def open_inbound(self, ciphertext: bytes, counter: int) -> bytes: ...
    def close(self) -> None: ...
    def is_open(self) -> bool: ...
