"""Type stubs for one_link_native.pair_qr (Phase F2)."""

from typing import Optional, Tuple

SAS_WORD_COUNT: int
SAS_BITS: int
CHAIN_KEY_LEN: int
INVITE_NONCE_LEN: int
INVITE_MAX_BYTES: int
INVITE_VERSION: int

class Inviter:
    def __init__(
        self,
        id_seed: bytes,
        expiry_unix: int,
        scope: Optional[bytes] = ...,
    ) -> None: ...
    def invite_bytes(self) -> bytes: ...
    def id_pubkey(self) -> bytes: ...
    def state(self) -> str: ...
    def receive_response(self, response_bytes: bytes) -> str: ...
    def sas(self) -> Optional[str]: ...
    def confirm(self) -> Tuple[bytes, bytes]: ...
    def confirm_with_factor2(
        self, factor2_key: bytes
    ) -> Tuple[bytes, bytes]: ...
    def abort(self) -> None: ...

class Scanner:
    @staticmethod
    def scan(
        id_seed: bytes,
        invite_bytes: bytes,
        now_unix: int,
    ) -> Tuple["Scanner", bytes]: ...
    def sas(self) -> str: ...
    def inviter_pubkey(self) -> bytes: ...
    def state(self) -> str: ...
    def receive_confirm(self, confirm_bytes: bytes) -> bytes: ...
    def receive_confirm_with_factor2(
        self, confirm_bytes: bytes, factor2_key: bytes
    ) -> bytes: ...
    def abort(self) -> None: ...

def decode_invite(
    invite_bytes: bytes,
) -> Tuple[bytes, bytes, bytes, int, bytes]: ...
def sas_from_transcript(transcript: bytes) -> str: ...

# Note: render_invite_qr_svg lives in src/one_link/pair_qr_native.py
# (Python-side wrapper using the qrcode dep), NOT in the native
# extension — so it's not exposed as a function on this stub
# module.
