"""Type stubs for ``one_link_native.ratchet`` (ADR-0020)."""

__version__: str
DEFAULT_SKIPPED_CAP: int


class Chain:
    @staticmethod
    def from_shared_secret(shared_secret: bytes) -> "Chain": ...

    def next_message_key(self) -> bytes: ...
    def peek_message_key(self, target_step: int) -> bytes: ...


class SkippedKeyStore:
    def __init__(self, cap: int) -> None: ...
    def insert(self, idx: int, key: bytes) -> None: ...
    def take(self, idx: int) -> bytes | None: ...
