"""Type stubs for ``one_link_native.routing`` (ADR-0028)."""

from typing import List, Tuple

__version__: str


class AdjacencyGraph:
    def __init__(self) -> None: ...

    def add_edge(self, from_: str, to: str, cost: float) -> None: ...
    def neighbors(self, node: str) -> List[Tuple[str, float]]: ...
    def node_count(self) -> int: ...
    def shortest_path(self, start: str, goal: str) -> Tuple[List[str], float]: ...


def edge_weight(tau_c_s: float, dist_m: float) -> float: ...
def loss_penalty(loss_rate: float) -> float: ...
def edge_cost(tau_c_s: float, dist_m: float, loss_rate: float) -> float: ...
def prefer_first(cost_a: float, cost_b: float) -> bool: ...
def should_swap_hop(
    current_cost: float, candidate_cost: float, hysteresis_factor: float
) -> bool: ...
def max_byzantine_count(n_total: int) -> int: ...
def quorum_safe(n_total: int, f_faulty: int) -> bool: ...
def rgg_mean_degree(n_nodes: int, radius: float) -> float: ...
def rgg_connectivity_radius(n_nodes: int) -> float: ...
def tau_claim_corroborated(
    claimed_tau_c_s: float, observed_success_rate: float, tolerance: float
) -> bool: ...
