"""Build a single-file standalone binary of the one-link CLI.

Works on Windows (produces one-link.exe), macOS (produces one-link), and Linux.
Requires PyInstaller in the active environment:

    pip install pyinstaller

Usage:

    python scripts/build_binary.py
    python scripts/build_binary.py --gui          # windowed (no console)
    python scripts/build_binary.py --no-ml        # skip ONNX/scipy
                                                  # for a tiny binary

Output goes to dist/one-link[.exe] at the repo root.

ML model bundling:

This script auto-detects ``assets/models/*/checkpoint.onnx`` files and
bundles them into the exe. Combined with onnxruntime (autocollected
when installed), the bundled binary runs the Tier ζ/η/θ semantic
codecs without a separate ``pip install torch`` (~200 MB savings).

Native (Rust) module bundling:

This script auto-detects whether one_link_native is installed in
the active environment. When present, `--collect-all one_link_native`
is added to the PyInstaller arg list so the .pyd / .so / .dylib
files are bundled into the exe; the produced binary then realizes
the Phase A1/A2 gains (CDC, AEAD, QUIC, coherence-field) without
needing a separate `pip install`.

When one_link_native is NOT installed, the build proceeds without
it — the resulting exe still works, falling back to the pure-Python
transport paths. Users who want the native fast path on a binary
build should run, before this script:

    pip install one_link_native --find-links \\
      https://github.com/IamOneYouAreOneWeAreOne/one-link/releases/latest

The release.yml workflow already publishes the native wheels per
OS to GitHub Releases (Phase 1 of the production-install plan).
"""

from __future__ import annotations

import argparse
import platform
import shutil
import subprocess
import sys
from pathlib import Path



def _remove_tree_best_effort(path: Path) -> None:
    """Remove a build directory, but do not crash on Windows file locks.

    PyInstaller/Defender can briefly hold ``*.pkg`` files after a build.
    A locked stale build directory should not prevent the next invocation
    from reaching PyInstaller's own ``--clean`` path.
    """
    try:
        shutil.rmtree(path)
    except PermissionError as exc:
        print(f"[build] warning: could not fully remove {path}: {exc}")


def _split_pyinstaller_pairs(items: list[str], sep: str) -> list[tuple[str, str]]:
    """Convert CLI-style --add-data/--add-binary args into spec tuples."""
    out: list[tuple[str, str]] = []
    pending_flag = False
    for item in items:
        if item in {"--add-data", "--add-binary"}:
            pending_flag = True
            continue
        if sep not in item:
            if pending_flag:
                pending_flag = False
            continue
        src, dest = item.split(sep, 1)
        if src and dest:
            out.append((src.replace("\\", "/"), dest.replace("\\", "/")))
        pending_flag = False
    return out


def _render_spec(
    *,
    name: str,
    entry: str,
    excludes: list[str],
    collect_submodules: list[str],
    collect_all: list[str],
    add_data_args: list[str],
    add_binary_args: list[str],
    hook_paths: list[str],
    icon: str,
    console: bool,
    forbidden_path_fragments: list[str],
) -> str:
    sep = ";" if platform.system() == "Windows" else ":"
    datas = _split_pyinstaller_pairs(add_data_args, sep)
    binaries = _split_pyinstaller_pairs(add_binary_args, sep)

    lines: list[str] = [
        "# Auto-generated by scripts/build_binary.py. Do not edit by hand.",
        "# This spec wraps PyInstaller Analysis with a post-filter",
        "# that strips heavy training/GPU dependencies discovered transitively.",
        "# -*- mode: python ; coding: utf-8 -*-",
        "",
        "from PyInstaller.utils.hooks import collect_submodules, collect_all",
        "",
        "block_cipher = None",
        "",
        f"datas = {datas!r}",
        f"binaries = {binaries!r}",
        "hiddenimports = []",
        "",
    ]
    for module in collect_submodules:
        lines.append(f"hiddenimports += collect_submodules({module!r})")
    for module in collect_all:
        lines.extend([
            f"_d, _b, _h = collect_all({module!r})",
            "datas += _d",
            "binaries += _b",
            "hiddenimports += _h",
        ])
    lines.extend([
        "",
        "a = Analysis(",
        f"    [{entry!r}],",
        "    pathex=[],",
        "    binaries=binaries,",
        "    datas=datas,",
        "    hiddenimports=hiddenimports,",
        f"    hookspath={hook_paths!r},",
        "    runtime_hooks=[],",
        f"    excludes={excludes!r},",
        "    win_no_prefer_redirects=False,",
        "    win_private_assemblies=False,",
        "    cipher=block_cipher,",
        "    noarchive=False,",
        ")",
        "",
        f"_FORBIDDEN = {forbidden_path_fragments!r}",
        "def _allowed(entry):",
        "    src = entry[1] if len(entry) > 1 else ''",
        "    norm = src.replace('\\\\', '/')",
        "    return not any(f in norm or f.replace('/', '\\\\') in src for f in _FORBIDDEN)",
        "",
        "_orig_bin = list(a.binaries)",
        "_orig_dat = list(a.datas)",
        "a.binaries = [e for e in a.binaries if _allowed(e)]",
        "a.datas = [e for e in a.datas if _allowed(e)]",
        "print(f'[build/spec] post-filter dropped {len(_orig_bin) - len(a.binaries)} binaries '",
        "      f'+ {len(_orig_dat) - len(a.datas)} datas (heavy-deps filter)')",
        "",
        "pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)",
        "",
        "exe = EXE(",
        "    pyz,",
        "    a.scripts,",
        "    a.binaries,",
        "    a.zipfiles,",
        "    a.datas,",
        "    [],",
        f"    name={name!r},",
        "    debug=False,",
        "    bootloader_ignore_signals=False,",
        "    strip=False,",
        "    upx=False,",
        "    upx_exclude=[],",
        "    runtime_tmpdir=None,",
        f"    console={console!r},",
        "    disable_windowed_traceback=False,",
        "    argv_emulation=False,",
        "    target_arch=None,",
        "    codesign_identity=None,",
        "    entitlements_file=None,",
        f"    icon={icon!r}," if icon else "    icon=None,",
        ")",
        "",
    ])
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    # GUI/windowed is the default: end-user clicks the desktop icon, the
    # daemon should run silently in the background — no black console
    # window flashing up. Developers wanting a console for debugging
    # pass --console.
    parser.add_argument(
        "--gui", action="store_true", default=True,
        help="Build a windowed binary (no console window). DEFAULT.",
    )
    parser.add_argument(
        "--console", dest="gui", action="store_false",
        help="Build a console binary (visible stdout/stderr). For "
             "debugging only; end users want --gui.",
    )
    parser.add_argument(
        "--no-ml", action="store_true",
        help="Skip bundling ONNX models + onnxruntime. Produces a much "
             "smaller binary; Tier ζ/η/θ codecs won't work in the result.",
    )
    args = parser.parse_args(list(argv or ()))

    repo = Path(__file__).resolve().parent.parent
    entry = repo / "src" / "one_link" / "__main__.py"

    # Make sure we have a __main__.py for `python -m one_link` and PyInstaller's
    # entrypoint discovery to use.
    if not entry.exists():
        entry.write_text(
            "from one_link.cli import main\n"
            "if __name__ == '__main__':\n"
            "    raise SystemExit(main() or 0)\n",
            encoding="utf-8",
        )

    try:
        import PyInstaller  # noqa: F401
    except ImportError:
        print("PyInstaller is not installed. Run:  pip install pyinstaller")
        return 2

    suffix = ".exe" if platform.system() == "Windows" else ""
    name = "one-link"
    out_name = f"{name}{suffix}"

    build = repo / "build"
    dist = repo / "dist"
    spec = repo / f"{name}.spec"

    for p in (build, dist):
        if p.exists():
            _remove_tree_best_effort(p)
    if spec.exists():
        spec.unlink()
    # PyInstaller 6.x on Python 3.14 has a race where it tries to
    # open build/<name>/base_library.zip for writing without first
    # creating the parent directory. Pre-create it so we never hit
    # that path.
    (build / name).mkdir(parents=True, exist_ok=True)

    native_build = subprocess.run(
        [sys.executable, str(repo / "scripts" / "build_native_cdc.py")],
        cwd=repo,
    )
    if native_build.returncode != 0:
        print(f"[build] native CDC build failed: exit {native_build.returncode}")
        return native_build.returncode

    # PyInstaller's --add-data uses ';' on Windows, ':' elsewhere.
    sep = ";" if platform.system() == "Windows" else ":"
    web_dir = repo / "src" / "one_link" / "web"
    add_data_web = f"{web_dir}{sep}one_link/web"
    native_dir = repo / "src" / "one_link" / "native"
    add_native: list[str] = []
    if native_dir.is_dir() and any(p.is_file() for p in native_dir.rglob("*")):
        add_native = ["--add-binary", f"{native_dir}{sep}one_link/native"]

    # Tier ζ/η/θ ML models — bundle every ONNX checkpoint + its
    # config. Torch .pt files are skipped to keep the binary lean;
    # the ONNX oracle factory falls back to torch only when ONNX is
    # missing, which won't happen in the bundled distribution.
    add_models: list[str] = []
    models_dir = repo / "assets" / "models"
    if not args.no_ml and models_dir.is_dir():
        for ckpt in models_dir.rglob("checkpoint.onnx"):
            rel = ckpt.parent.relative_to(repo).as_posix()
            add_models.extend([
                "--add-data", f"{ckpt}{sep}{rel}",
            ])
        for cfg in models_dir.rglob("config.json"):
            rel = cfg.parent.relative_to(repo).as_posix()
            add_models.extend([
                "--add-data", f"{cfg}{sep}{rel}",
            ])
        if add_models:
            print(f"[build] bundling {len(add_models) // 2} model file(s) from {models_dir}")

    onnx_collect: list[str] = []
    if not args.no_ml:
        try:
            import onnxruntime  # noqa: F401
            onnx_collect = ["--collect-all", "onnxruntime"]
            print("[build] onnxruntime detected — bundling for ONNX codecs")
        except ImportError:
            print("[build] onnxruntime not installed — ML codecs will not "
                  "work in the bundled binary. pip install onnxruntime first.")

    icon_arg: list[str] = []
    if platform.system() == "Windows":
        ico = web_dir / "assets" / "one-glyph.ico"
        if ico.is_file():
            icon_arg = ["--icon", str(ico)]
    elif platform.system() == "Darwin":
        # PyInstaller can take .icns on Mac; .ico is also accepted in recent versions.
        ico = web_dir / "assets" / "one-glyph.ico"
        if ico.is_file():
            icon_arg = ["--icon", str(ico)]

    # v0.21.x: include the Rust-built native extension (one_link_native)
    # so the bundled binary gets the QUIC + coherence-field fast paths.
    # If the wheel isn't installed in the active env, PyInstaller will
    # log a warning and the resulting exe will fall back to pure-Python
    # paths — same behavior as before this change, no regression.
    try:
        import one_link_native  # noqa: F401
        native_collect = ["--collect-all", "one_link_native"]
        print("[build] one_link_native detected — bundling into exe")
    except ImportError:
        native_collect = []
        print(
            "[build] one_link_native not installed in this env — building "
            "without native fast path. To include it: install the wheel "
            "first via `pip install one_link_native --find-links "
            "https://github.com/IamOneYouAreOneWeAreOne/one-link/releases/latest`"
        )

    # GUI mode = no console window. Use --windowed on Mac/Win, no-op on Linux.
    console_flag = "--windowed" if args.gui and platform.system() != "Linux" else "--console"

    # NOTE: --clean is intentionally NOT passed. We've already wiped
    # build/ + dist/ above, and PyInstaller's own --clean step has a
    # known bug on Python 3.14 where it deletes base_library.zip's
    # parent directory mid-write. Pre-wiping has the same effect.
    #
    # The runtime does NOT need torch — ONNX Runtime is the inference
    # engine in the bundle. torch is only used in scripts/export_ml_to_onnx.py
    # to produce the .onnx files from .pt at build time. Exclude
    # explicitly to avoid pulling ~2 GB of CUDA libs into the
    # release artifact.
    exclude_modules = [
        # ML / training-only — daemon uses ONNX Runtime instead.
        "torch", "torchvision", "torchaudio",
        "tensorflow", "tensorflow_intel",
        "jax", "jaxlib",
        # GPU compute / numba / llvmlite — not needed at runtime.
        # PyInstaller's binary analyzer picks up torch's CUDA DLLs
        # via these transitive deps; excluding them shrinks the
        # bundle by ~1.6 GB.
        "numba", "cupy", "llvmlite", "nvidia",
        "torch.cuda", "torch.distributed", "torch.backends",
        # Heavy scientific stack the daemon doesn't import.
        "matplotlib", "pandas", "sympy",
        # PIL/Pillow used by build scripts only.
        "PIL", "Pillow",
        # Dev / notebook deps.
        "IPython", "jupyter", "notebook",
        # Test deps.
        "test", "tests", "pytest",
        # Training-time subpackages of one_link (use torch + scipy).
        # Daemon path imports nothing from one_link.ml at runtime.
        "one_link.ml",
    ]
    excludes = []
    for m in exclude_modules:
        excludes.extend(["--exclude-module", m])

    # Path patterns that must NEVER end up in the bundle. PyInstaller's
    # binary analyzer recursively follows DLL imports and pulls in CUDA
    # libraries (torch/lib/*.dll, cupy/cuda/*, nvidia/*) via transitive
    # deps even when --exclude-module names the parent. We post-filter
    # the Analysis result via a generated .spec file.
    forbidden_paths = [
        "torch/lib/", "torch\\lib\\",
        "torchvision/", "torchvision\\",
        "torchaudio/", "torchaudio\\",
        "cupy/cuda/", "cupy\\cuda\\",
        "cupy_backends/", "cupy_backends\\",
        "numba/", "numba\\",
        "llvmlite/binding/", "llvmlite\\binding\\",
        "nvidia/", "nvidia\\",
        "tensorflow/", "tensorflow\\",
        "tensorflow_intel/", "tensorflow_intel\\",
        "jax/", "jax\\",
        "jaxlib/", "jaxlib\\",
        "matplotlib/", "matplotlib\\",
        "pandas/", "pandas\\",
        "sympy/", "sympy\\",
        "scipy/", "scipy\\",
        "IPython/", "IPython\\",
        "jupyter/", "jupyter\\",
        "notebook/", "notebook\\",
    ]
    spec_path = build / f"{name}.spec"
    spec_path.parent.mkdir(parents=True, exist_ok=True)
    # `add_native` and `add_models` are PyInstaller CLI-form lists
    # (alternating "--add-data"/"--add-binary" flag tokens and their
    # path arguments). For spec generation we only want the path
    # arguments — strip every other token starting at index 0.
    add_data_args = [add_data_web] + list(add_models[1::2])
    add_binary_args = list(add_native[1::2])
    # Generate a self-contained spec file. We do this rather than
    # using the CLI so we can post-filter Analysis.binaries by path.
    spec_path.write_text(_render_spec(
        name=name,
        entry=str(entry).replace("\\", "/"),
        excludes=exclude_modules,
        collect_submodules=["zeroconf", "cryptography", "aiohttp"],
        collect_all=(
            (["onnxruntime"] if onnx_collect else []) +
            (["one_link_native"] if native_collect else [])
        ),
        add_data_args=add_data_args,
        add_binary_args=add_binary_args,
        hook_paths=[
            str((repo / "scripts" / "pyinstaller_hooks")).replace("\\", "/"),
        ] if (repo / "scripts" / "pyinstaller_hooks").is_dir() else [],
        icon=str(icon_arg[1]).replace("\\", "/") if icon_arg else "",
        console=("--console" == console_flag),
        forbidden_path_fragments=forbidden_paths,
    ), encoding="utf-8")

    # Note: --clean intentionally omitted. PyInstaller's own --clean
    # has a Python 3.14 bug where it deletes localpycs/struct.pyc
    # mid-write. We pre-wipe build/ + dist/ above, which has the
    # same effect without triggering the bug.
    cmd = [
        sys.executable,
        "-m",
        "PyInstaller",
        "--noconfirm",
        "--distpath",
        str(dist),
        "--workpath",
        str(build),
        str(spec_path),
    ]
    print("[build] running:", " ".join(cmd))
    res = subprocess.run(cmd, cwd=repo)
    if res.returncode != 0:
        print(f"[build] PyInstaller failed: exit {res.returncode}")
        return res.returncode

    final = dist / out_name
    if not final.exists():
        print(f"[build] expected output not found: {final}")
        return 3
    print(f"[build] OK -> {final}  ({final.stat().st_size:,} bytes)")

    print("[build] smoke test: one-link --version")
    try:
        smoke = subprocess.run(
            [str(final), "--version"], capture_output=True, text=True, timeout=15
        )
        print("  stdout:", smoke.stdout.strip())
        if smoke.stderr.strip():
            print("  stderr:", smoke.stderr.strip())
        if smoke.returncode != 0:
            print(f"[build] smoke non-zero ({smoke.returncode}); binary still produced")
        else:
            print("[build] smoke OK")
    except (OSError, subprocess.TimeoutExpired) as e:
        # On Windows, freshly-built unsigned exes can be blocked by
        # Defender/Application Control before they ever run. The binary is
        # still valid; ship it and let the user retry. This is informational,
        # not a build failure.
        print(f"[build] smoke step could not run: {e}")
        print(
            "[build] this is typically Windows Defender / Application Control "
            "blocking a fresh unsigned binary; the exe itself is fine."
        )
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
