"""SDP + ICE signaling layer on top of the call lifecycle.

The base :mod:`call_signaling` module handles the *phase* transitions
(INVITE → RING → ACTIVE → …). It deliberately doesn't carry the
WebRTC negotiation payload because the FSM is media-agnostic.

This module is the small structured layer that carries the actual
WebRTC SDP + ICE exchange between two browsers, brokered by their
daemons:

  - ``CALL_INVITE`` may now include an ``sdp_offer`` field (the
    originator's SDP offer, generated by their browser via
    ``RTCPeerConnection.createOffer``).
  - ``CALL_ACCEPT`` carries the recipient's ``sdp_answer`` (generated
    via ``createAnswer`` after setting the remote description).
  - ``CALL_ICE`` is a new message type carrying one trickled ICE
    candidate at a time, either direction. Trickling avoids stalling
    the offer/answer on slow STUN gathers.

The format is JSON-friendly and version-tagged so older clients
that don't speak it ignore the extra fields and fall back to
audio-via-existing-channels (or fail gracefully on the FSM side).

The browser-side driver in ``index.html`` calls into these helpers
via the ``/api/v1/calls`` HTTP surface (action=initiate_sdp,
accept_sdp, ice_candidate). The daemon parses + forwards.

Pure module — no I/O, no daemon imports. Tests construct payloads
+ verify parse/build round-trip.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from enum import IntEnum
from typing import Any, Optional


# ---------------------------------------------------------------------------
# Wire message types
# ---------------------------------------------------------------------------

CALL_INVITE_SDP_V1 = 1   # schema version embedded in messages so older
                         # peers can refuse cleanly.

CALL_ICE = "CALL_ICE"     # individual ICE candidate, either direction.

MAX_SDP_BYTES = 128 * 1024
MAX_ICE_CANDIDATE_CHARS = 4 * 1024
MAX_SDP_MID_CHARS = 256
_SDP_FIELDS = frozenset({"schema", "kind", "sdp"})
_ICE_FIELDS = frozenset({
    "schema", "candidate", "sdpMid", "sdpMLineIndex", "endOfCandidates",
})
_CALL_ID_RE = re.compile(r"\A[A-Za-z0-9][A-Za-z0-9._:-]{0,127}\Z")


# ---------------------------------------------------------------------------
# SDP types
# ---------------------------------------------------------------------------

class SdpKind(IntEnum):
    """Standard WebRTC SDP role tags. The browser-side
    ``RTCSessionDescription.type`` field maps directly."""

    OFFER     = 0
    ANSWER    = 1
    PRANSWER  = 2
    ROLLBACK  = 3

    @classmethod
    def from_str(cls, s: str) -> "SdpKind":
        return {
            "offer":     cls.OFFER,
            "answer":    cls.ANSWER,
            "pranswer":  cls.PRANSWER,
            "rollback":  cls.ROLLBACK,
        }[s.lower()]

    def to_str(self) -> str:
        return {
            SdpKind.OFFER:    "offer",
            SdpKind.ANSWER:   "answer",
            SdpKind.PRANSWER: "pranswer",
            SdpKind.ROLLBACK: "rollback",
        }[self]


# ---------------------------------------------------------------------------
# Structured payloads
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class SdpPayload:
    """One side's SDP. Carried inside a CALL_INVITE (offer) or
    CALL_ACCEPT (answer)."""

    schema: int       # protocol version
    kind: SdpKind
    sdp: str

    def __post_init__(self) -> None:
        _validate_schema(self.schema, label="sdp")
        if not isinstance(self.kind, SdpKind):
            raise ValueError("sdp kind must be a SdpKind")
        if not isinstance(self.sdp, str) or not self.sdp:
            raise ValueError("sdp body required")
        if len(self.sdp.encode("utf-8")) > MAX_SDP_BYTES:
            raise ValueError("sdp body too large")
        if "\x00" in self.sdp or not looks_like_sdp(self.sdp):
            raise ValueError("sdp body is malformed")

    def to_wire(self) -> dict[str, Any]:
        return {
            "schema": self.schema,
            "kind":   self.kind.to_str(),
            "sdp":    self.sdp,
        }

    @classmethod
    def from_wire(cls, d: Any) -> "SdpPayload":
        if not isinstance(d, dict):
            raise ValueError("sdp payload must be a dict")
        _reject_unknown_fields(d, _SDP_FIELDS, label="sdp")
        schema = _validate_schema(d.get("schema"), label="sdp")
        kind_str = d.get("kind")
        if not isinstance(kind_str, str):
            raise ValueError("sdp kind must be string")
        if kind_str not in {"offer", "answer", "pranswer", "rollback"}:
            raise ValueError(f"unknown sdp kind: {kind_str!r}")
        try:
            kind = SdpKind.from_str(kind_str)
        except KeyError as exc:
            raise ValueError(f"unknown sdp kind: {kind_str!r}") from exc
        sdp = d.get("sdp")
        if not isinstance(sdp, str) or not sdp:
            raise ValueError("sdp body required")
        return cls(schema=schema, kind=kind, sdp=sdp)


@dataclass(frozen=True)
class IceCandidatePayload:
    """One trickled ICE candidate. The browser's
    ``RTCPeerConnection.onicecandidate`` event emits these as they
    are gathered; we ship each one separately so the negotiation
    can begin without waiting for the full gather to complete."""

    schema: int
    candidate: str    # the SDP-fragment-style candidate line
    sdp_mid: Optional[str]
    sdp_m_line_index: Optional[int]
    # Special-case: an empty candidate signals "ICE gathering
    # complete." We carry it explicitly so both sides know when
    # no more candidates are coming.
    end_of_candidates: bool = False

    def __post_init__(self) -> None:
        _validate_schema(self.schema, label="ice")
        if not isinstance(self.candidate, str):
            raise ValueError("ice candidate must be string")
        if len(self.candidate) > MAX_ICE_CANDIDATE_CHARS:
            raise ValueError("ice candidate too large")
        if any(ord(ch) < 0x20 or ord(ch) > 0x7E for ch in self.candidate):
            raise ValueError("ice candidate contains invalid characters")
        if not isinstance(self.end_of_candidates, bool):
            raise ValueError("endOfCandidates must be boolean")
        if self.end_of_candidates:
            if self.candidate:
                raise ValueError("end-of-candidates sentinel must be empty")
        elif not self.candidate.startswith("candidate:"):
            raise ValueError("ice candidate must start with candidate:")
        if self.sdp_mid is not None:
            if (
                not isinstance(self.sdp_mid, str)
                or len(self.sdp_mid) > MAX_SDP_MID_CHARS
                or any(ord(ch) < 0x20 or ord(ch) > 0x7E for ch in self.sdp_mid)
            ):
                raise ValueError("sdpMid must be bounded ASCII text or null")
        if self.sdp_m_line_index is not None and (
            isinstance(self.sdp_m_line_index, bool)
            or not isinstance(self.sdp_m_line_index, int)
            or not 0 <= self.sdp_m_line_index <= 1024
        ):
            raise ValueError("sdpMLineIndex out of range")

    def to_wire(self) -> dict[str, Any]:
        return {
            "schema":            self.schema,
            "candidate":         self.candidate,
            "sdpMid":            self.sdp_mid,
            "sdpMLineIndex":     self.sdp_m_line_index,
            "endOfCandidates":   self.end_of_candidates,
        }

    @classmethod
    def from_wire(cls, d: Any) -> "IceCandidatePayload":
        if not isinstance(d, dict):
            raise ValueError("ice payload must be a dict")
        _reject_unknown_fields(d, _ICE_FIELDS, label="ice")
        schema = _validate_schema(d.get("schema"), label="ice")
        candidate = d.get("candidate")
        if not isinstance(candidate, str):
            raise ValueError("ice candidate must be string")
        sdp_mid = d.get("sdpMid")
        if sdp_mid is not None and not isinstance(sdp_mid, str):
            raise ValueError("sdpMid must be string or null")
        idx_raw = d.get("sdpMLineIndex")
        if idx_raw is None:
            sdp_m_line_index: Optional[int] = None
        else:
            if isinstance(idx_raw, bool) or not isinstance(idx_raw, int):
                raise ValueError("sdpMLineIndex not an int")
            sdp_m_line_index = idx_raw
            if sdp_m_line_index < 0 or sdp_m_line_index > 1024:
                raise ValueError("sdpMLineIndex out of range")
        end_of_candidates = d.get("endOfCandidates", False)
        if not isinstance(end_of_candidates, bool):
            raise ValueError("endOfCandidates must be boolean")
        return cls(
            schema=schema,
            candidate=candidate,
            sdp_mid=sdp_mid,
            sdp_m_line_index=sdp_m_line_index,
            end_of_candidates=end_of_candidates,
        )


# ---------------------------------------------------------------------------
# CALL_INVITE / CALL_ACCEPT envelope helpers
# ---------------------------------------------------------------------------

def attach_offer_to_invite(
    invite_payload: dict[str, Any],
    *,
    sdp: str,
) -> dict[str, Any]:
    """Add an SDP offer field to a CALL_INVITE payload. Used by
    the daemon when relaying an originator's outbound INVITE."""
    out = dict(invite_payload)
    out["sdp_offer"] = SdpPayload(
        schema=CALL_INVITE_SDP_V1,
        kind=SdpKind.OFFER,
        sdp=sdp,
    ).to_wire()
    return out


def attach_answer_to_accept(
    accept_payload: dict[str, Any],
    *,
    sdp: str,
) -> dict[str, Any]:
    """Add an SDP answer field to a CALL_ACCEPT payload."""
    out = dict(accept_payload)
    out["sdp_answer"] = SdpPayload(
        schema=CALL_INVITE_SDP_V1,
        kind=SdpKind.ANSWER,
        sdp=sdp,
    ).to_wire()
    return out


def extract_offer(invite_payload: dict[str, Any]) -> Optional[SdpPayload]:
    """Return the SDP offer carried in a CALL_INVITE, or None if
    the message has no offer attached (older client, or audio-only
    fallback)."""
    raw = invite_payload.get("sdp_offer")
    if raw is None:
        return None
    parsed = SdpPayload.from_wire(raw)
    if parsed.kind != SdpKind.OFFER:
        raise ValueError("sdp_offer must carry offer kind")
    return parsed


def extract_answer(accept_payload: dict[str, Any]) -> Optional[SdpPayload]:
    """Return the SDP answer carried in a CALL_ACCEPT, or None."""
    raw = accept_payload.get("sdp_answer")
    if raw is None:
        return None
    parsed = SdpPayload.from_wire(raw)
    if parsed.kind != SdpKind.ANSWER:
        raise ValueError("sdp_answer must carry answer kind")
    return parsed


# ---------------------------------------------------------------------------
# CALL_ICE message helpers
# ---------------------------------------------------------------------------

def build_ice_message(
    *,
    call_id: str,
    candidate: IceCandidatePayload,
) -> dict[str, Any]:
    """Construct the body of a CALL_ICE wire message (without the
    standard envelope fields that ``make_msg`` adds)."""
    return {
        "call_id":   call_id,
        "candidate": candidate.to_wire(),
    }


def parse_ice_message(payload: dict[str, Any]) -> tuple[str, IceCandidatePayload]:
    """Parse a CALL_ICE payload. Returns ``(call_id, candidate)``.
    Raises ``ValueError`` on malformed input. Caller (the daemon's
    dispatch) catches + drops silently."""
    call_id = payload.get("call_id")
    if not isinstance(call_id, str) or _CALL_ID_RE.fullmatch(call_id) is None:
        raise ValueError("ICE missing call_id")
    raw = payload.get("candidate")
    if raw is None:
        raise ValueError("ICE missing candidate")
    return call_id, IceCandidatePayload.from_wire(raw)


def end_of_candidates(call_id: str) -> dict[str, Any]:
    """Build the sentinel 'no more candidates' message. Both sides
    use this to know ICE gathering is done."""
    return build_ice_message(
        call_id=call_id,
        candidate=IceCandidatePayload(
            schema=CALL_INVITE_SDP_V1,
            candidate="",
            sdp_mid=None,
            sdp_m_line_index=None,
            end_of_candidates=True,
        ),
    )


# ---------------------------------------------------------------------------
# Validation helpers
# ---------------------------------------------------------------------------

# Minimal SDP-shape sanity check. We don't try to parse SDP — that's
# the browser's job — but a string that's obviously not SDP (e.g.,
# binary garbage, or a malicious all-spaces blob) should be refused
# at the daemon edge to prevent it from being forwarded to a peer.

def looks_like_sdp(s: str) -> bool:
    """Cheap structural test. Real SDPs always start with 'v=0' as
    the first line. We accept leading whitespace + line-ending
    variations."""
    if not isinstance(s, str):
        return False
    if not s or "\x00" in s:
        return False
    try:
        if len(s.encode("utf-8")) > MAX_SDP_BYTES:
            return False
    except UnicodeEncodeError:
        return False
    stripped = s.lstrip()
    if not stripped.startswith("v=0"):
        return False
    # Must contain at least one 'm=' (media) line — even DataChannel
    # SDPs have m=application.
    if "\nm=" not in s and "\rm=" not in s:
        return False
    return True


def _validate_schema(value: object, *, label: str) -> int:
    if isinstance(value, bool) or not isinstance(value, int):
        raise ValueError(f"{label} schema not an int")
    if value != CALL_INVITE_SDP_V1:
        raise ValueError(
            f"unsupported {label} schema {value}; expected {CALL_INVITE_SDP_V1}"
        )
    return value


def _reject_unknown_fields(
    value: dict[str, Any], expected: frozenset[str], *, label: str,
) -> None:
    keys = frozenset(value)
    extra = keys - expected
    if extra:
        raise ValueError(f"{label} payload has unknown fields: {', '.join(sorted(extra))}")
