"""SDP + ICE signaling layer on top of the call lifecycle.

The base :mod:`call_signaling` module handles the *phase* transitions
(INVITE → RING → ACTIVE → …). It deliberately doesn't carry the
WebRTC negotiation payload because the FSM is media-agnostic.

This module is the small structured layer that carries the actual
WebRTC SDP + ICE exchange between two browsers, brokered by their
daemons:

  - ``CALL_INVITE`` may now include an ``sdp_offer`` field (the
    originator's SDP offer, generated by their browser via
    ``RTCPeerConnection.createOffer``).
  - ``CALL_ACCEPT`` carries the recipient's ``sdp_answer`` (generated
    via ``createAnswer`` after setting the remote description).
  - ``CALL_ICE`` is a new message type carrying one trickled ICE
    candidate at a time, either direction. Trickling avoids stalling
    the offer/answer on slow STUN gathers.

The format is JSON-friendly and version-tagged so older clients
that don't speak it ignore the extra fields and fall back to
audio-via-existing-channels (or fail gracefully on the FSM side).

The browser-side driver in ``index.html`` calls into these helpers
via the ``/api/v1/calls`` HTTP surface (action=initiate_sdp,
accept_sdp, ice_candidate). The daemon parses + forwards.

Pure module — no I/O, no daemon imports. Tests construct payloads
+ verify parse/build round-trip.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import IntEnum
from typing import Any, Optional


# ---------------------------------------------------------------------------
# Wire message types
# ---------------------------------------------------------------------------

CALL_INVITE_SDP_V1 = 1   # schema version embedded in messages so older
                         # peers can refuse cleanly.

CALL_ICE = "CALL_ICE"     # individual ICE candidate, either direction.


# ---------------------------------------------------------------------------
# SDP types
# ---------------------------------------------------------------------------

class SdpKind(IntEnum):
    """Standard WebRTC SDP role tags. The browser-side
    ``RTCSessionDescription.type`` field maps directly."""

    OFFER     = 0
    ANSWER    = 1
    PRANSWER  = 2
    ROLLBACK  = 3

    @classmethod
    def from_str(cls, s: str) -> "SdpKind":
        return {
            "offer":     cls.OFFER,
            "answer":    cls.ANSWER,
            "pranswer":  cls.PRANSWER,
            "rollback":  cls.ROLLBACK,
        }[s.lower()]

    def to_str(self) -> str:
        return {
            SdpKind.OFFER:    "offer",
            SdpKind.ANSWER:   "answer",
            SdpKind.PRANSWER: "pranswer",
            SdpKind.ROLLBACK: "rollback",
        }[self]


# ---------------------------------------------------------------------------
# Structured payloads
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class SdpPayload:
    """One side's SDP. Carried inside a CALL_INVITE (offer) or
    CALL_ACCEPT (answer)."""

    schema: int       # protocol version
    kind: SdpKind
    sdp: str

    def to_wire(self) -> dict[str, Any]:
        return {
            "schema": self.schema,
            "kind":   self.kind.to_str(),
            "sdp":    self.sdp,
        }

    @classmethod
    def from_wire(cls, d: Any) -> "SdpPayload":
        if not isinstance(d, dict):
            raise ValueError("sdp payload must be a dict")
        try:
            schema = int(d.get("schema") or 0)
        except (TypeError, ValueError) as exc:
            raise ValueError(f"sdp schema not an int: {exc}") from exc
        if schema != CALL_INVITE_SDP_V1:
            raise ValueError(
                f"unsupported sdp schema {schema}; expected "
                f"{CALL_INVITE_SDP_V1}"
            )
        kind_str = d.get("kind")
        if not isinstance(kind_str, str):
            raise ValueError("sdp kind must be string")
        try:
            kind = SdpKind.from_str(kind_str)
        except KeyError as exc:
            raise ValueError(f"unknown sdp kind: {kind_str!r}") from exc
        sdp = d.get("sdp")
        if not isinstance(sdp, str) or not sdp:
            raise ValueError("sdp body required")
        # Reasonable cap so a peer can't fill our memory with one
        # malicious SDP. 128 KiB is more than ample for any real
        # WebRTC offer (typical ~5 KiB).
        if len(sdp) > 128 * 1024:
            raise ValueError("sdp body too large")
        return cls(schema=schema, kind=kind, sdp=sdp)


@dataclass(frozen=True)
class IceCandidatePayload:
    """One trickled ICE candidate. The browser's
    ``RTCPeerConnection.onicecandidate`` event emits these as they
    are gathered; we ship each one separately so the negotiation
    can begin without waiting for the full gather to complete."""

    schema: int
    candidate: str    # the SDP-fragment-style candidate line
    sdp_mid: Optional[str]
    sdp_m_line_index: Optional[int]
    # Special-case: an empty candidate signals "ICE gathering
    # complete." We carry it explicitly so both sides know when
    # no more candidates are coming.
    end_of_candidates: bool = False

    def to_wire(self) -> dict[str, Any]:
        return {
            "schema":            self.schema,
            "candidate":         self.candidate,
            "sdpMid":            self.sdp_mid,
            "sdpMLineIndex":     self.sdp_m_line_index,
            "endOfCandidates":   self.end_of_candidates,
        }

    @classmethod
    def from_wire(cls, d: Any) -> "IceCandidatePayload":
        if not isinstance(d, dict):
            raise ValueError("ice payload must be a dict")
        try:
            schema = int(d.get("schema") or 0)
        except (TypeError, ValueError) as exc:
            raise ValueError(f"ice schema not an int: {exc}") from exc
        if schema != CALL_INVITE_SDP_V1:
            raise ValueError(
                f"unsupported ice schema {schema}; expected "
                f"{CALL_INVITE_SDP_V1}"
            )
        candidate = d.get("candidate")
        if not isinstance(candidate, str):
            raise ValueError("ice candidate must be string")
        if len(candidate) > 4 * 1024:
            raise ValueError("ice candidate too large")
        sdp_mid = d.get("sdpMid")
        if sdp_mid is not None and not isinstance(sdp_mid, str):
            raise ValueError("sdpMid must be string or null")
        idx_raw = d.get("sdpMLineIndex")
        if idx_raw is None:
            sdp_m_line_index: Optional[int] = None
        else:
            try:
                sdp_m_line_index = int(idx_raw)
            except (TypeError, ValueError) as exc:
                raise ValueError(
                    f"sdpMLineIndex not an int: {exc}"
                ) from exc
            if sdp_m_line_index < 0 or sdp_m_line_index > 1024:
                raise ValueError("sdpMLineIndex out of range")
        end_of_candidates = bool(d.get("endOfCandidates"))
        return cls(
            schema=schema,
            candidate=candidate,
            sdp_mid=sdp_mid,
            sdp_m_line_index=sdp_m_line_index,
            end_of_candidates=end_of_candidates,
        )


# ---------------------------------------------------------------------------
# CALL_INVITE / CALL_ACCEPT envelope helpers
# ---------------------------------------------------------------------------

def attach_offer_to_invite(
    invite_payload: dict[str, Any],
    *,
    sdp: str,
) -> dict[str, Any]:
    """Add an SDP offer field to a CALL_INVITE payload. Used by
    the daemon when relaying an originator's outbound INVITE."""
    out = dict(invite_payload)
    out["sdp_offer"] = SdpPayload(
        schema=CALL_INVITE_SDP_V1,
        kind=SdpKind.OFFER,
        sdp=sdp,
    ).to_wire()
    return out


def attach_answer_to_accept(
    accept_payload: dict[str, Any],
    *,
    sdp: str,
) -> dict[str, Any]:
    """Add an SDP answer field to a CALL_ACCEPT payload."""
    out = dict(accept_payload)
    out["sdp_answer"] = SdpPayload(
        schema=CALL_INVITE_SDP_V1,
        kind=SdpKind.ANSWER,
        sdp=sdp,
    ).to_wire()
    return out


def extract_offer(invite_payload: dict[str, Any]) -> Optional[SdpPayload]:
    """Return the SDP offer carried in a CALL_INVITE, or None if
    the message has no offer attached (older client, or audio-only
    fallback)."""
    raw = invite_payload.get("sdp_offer")
    if raw is None:
        return None
    return SdpPayload.from_wire(raw)


def extract_answer(accept_payload: dict[str, Any]) -> Optional[SdpPayload]:
    """Return the SDP answer carried in a CALL_ACCEPT, or None."""
    raw = accept_payload.get("sdp_answer")
    if raw is None:
        return None
    return SdpPayload.from_wire(raw)


# ---------------------------------------------------------------------------
# CALL_ICE message helpers
# ---------------------------------------------------------------------------

def build_ice_message(
    *,
    call_id: str,
    candidate: IceCandidatePayload,
) -> dict[str, Any]:
    """Construct the body of a CALL_ICE wire message (without the
    standard envelope fields that ``make_msg`` adds)."""
    return {
        "call_id":   call_id,
        "candidate": candidate.to_wire(),
    }


def parse_ice_message(payload: dict[str, Any]) -> tuple[str, IceCandidatePayload]:
    """Parse a CALL_ICE payload. Returns ``(call_id, candidate)``.
    Raises ``ValueError`` on malformed input. Caller (the daemon's
    dispatch) catches + drops silently."""
    call_id = payload.get("call_id")
    if not isinstance(call_id, str) or not call_id:
        raise ValueError("ICE missing call_id")
    raw = payload.get("candidate")
    if raw is None:
        raise ValueError("ICE missing candidate")
    return call_id, IceCandidatePayload.from_wire(raw)


def end_of_candidates(call_id: str) -> dict[str, Any]:
    """Build the sentinel 'no more candidates' message. Both sides
    use this to know ICE gathering is done."""
    return build_ice_message(
        call_id=call_id,
        candidate=IceCandidatePayload(
            schema=CALL_INVITE_SDP_V1,
            candidate="",
            sdp_mid=None,
            sdp_m_line_index=None,
            end_of_candidates=True,
        ),
    )


# ---------------------------------------------------------------------------
# Validation helpers
# ---------------------------------------------------------------------------

# Minimal SDP-shape sanity check. We don't try to parse SDP — that's
# the browser's job — but a string that's obviously not SDP (e.g.,
# binary garbage, or a malicious all-spaces blob) should be refused
# at the daemon edge to prevent it from being forwarded to a peer.

def looks_like_sdp(s: str) -> bool:
    """Cheap structural test. Real SDPs always start with 'v=0' as
    the first line. We accept leading whitespace + line-ending
    variations."""
    if not isinstance(s, str):
        return False
    stripped = s.lstrip()
    if not stripped.startswith("v=0"):
        return False
    # Must contain at least one 'm=' (media) line — even DataChannel
    # SDPs have m=application.
    if "\nm=" not in s and "\rm=" not in s:
        return False
    return True
